using System.Text.Json;
using System.Text.Json.Nodes;
namespace Mgo2Mt.WpnEditor;
internal sealed partial class MainForm
{
    private bool verifying;
    private static void Tone(string file){const int n=22050;using var b=new BinaryWriter(File.Create(file));b.Write("RIFF"u8);b.Write(36+n*2);b.Write("WAVEfmt "u8);b.Write(16);b.Write((short)1);b.Write((short)1);b.Write(44100);b.Write(88200);b.Write((short)2);b.Write((short)16);b.Write("data"u8);b.Write(n*2);for(int i=0;i<n;i++)b.Write((short)(Math.Sin(i*Math.Tau*440/44100)*1700*Math.Min(1,(n-i)/1000.0)));}
    private async Task Verify(string output)
    {
        verifying=true;int checks=0;void Check(bool v,string message){checks++;if(!v)throw new InvalidOperationException(message);}output=Path.GetFullPath(output);Directory.CreateDirectory(output);
        try
        {
            int fi=Array.IndexOf(args,"--fixture");if(fi<0||fi+1>=args.Length)throw new ArgumentException("--fixture gameplay.json required");
            var root=Path.Combine(output,"data");Directory.CreateDirectory(root);var source=Document.Parse(File.ReadAllText(args[fi+1]));source["resources"]!.AsObject().Remove("weaponEffectsManifest");string gp=Path.Combine(root,"gameplay.json");File.WriteAllText(gp,source.ToJsonString(Document.JsonOptions));File.WriteAllText(Path.Combine(root,"assets.sha256"),Document.Hash(gp)+"  gameplay.json\n");LoadFile(gp);Check(doc!.Weapons.Count>0,"weapons loaded");weaponId=doc.Weapons.Any(w=>w?["id"]?.GetValue<int>()==25)?25:doc.Weapons[0]!["id"]!.GetValue<int>();RefreshList();RefreshFields();
            var png=Path.Combine(output,"authored-atlas.png");using(var image=new Bitmap(256,64)){using var g=Graphics.FromImage(image);g.Clear(Color.Transparent);for(int i=0;i<4;i++){using var p=new System.Drawing.Drawing2D.GraphicsPath();p.AddEllipse(i*64+3,3,58,58);using var b=new System.Drawing.Drawing2D.PathGradientBrush(p){CenterColor=Color.White,SurroundColors=[Color.Transparent]};g.FillPath(b,p);}image.Save(png,System.Drawing.Imaging.ImageFormat.Png);}string rel=doc.Import(png,false);
            var wav=Path.Combine(output,"authored-tone.wav");Tone(wav);Native.Wave(wav);string soundPath=doc.Import(wav,true);
            Change(()=>{var a=EnsureLayers();a.Clear();a.Add(new JsonObject{["texture"]=rel,["count"]=6,["radius"]=140,["lifetimeMs"]=950,["emissionMs"]=150,["speed"]=180,["spread"]=.9,["color"]=new JsonArray(1,.65,.2,1),["atlas"]=new JsonObject{["columns"]=4,["rows"]=1,["frames"]=4,["fps"]=8},["sizeCurve"]=new JsonArray(new JsonArray(0,.2),new JsonArray(.2,1),new JsonArray(1,.1)),["alphaCurve"]=new JsonArray(new JsonArray(0,1),new JsonArray(1,0))});var l=EnsureEvent("lights","shot");l["durationMs"]=1000;l["intensity"]=4;var s=EnsureEvent("sounds","shot");s["enabled"]=true;s["path"]=soundPath;s["delayMs"]=40;});Check(doc.Dirty,"effects dirty");
            Change(()=>{var r=EnsureReticle();r["color"]=new JsonArray(.2,.9,1,1);r["minGap"]=12;r["length"]=14;});
            var samples=Native.Sample(doc.Effects.ToJsonString(),weaponId,"muzzle",300);Check(samples.Length==6,"shared samples");Check(samples.All(p=>p.Radius>0&&p.A>0&&p.U1>p.U0),"sample size alpha atlas");Check(Native.Sample(doc.Effects.ToJsonString(),weaponId,"muzzle",300).SequenceEqual(samples),"deterministic shared evaluator");Check(Native.Sample(doc.Effects.ToJsonString(),weaponId,"muzzle",2000).Length==0,"particles expire");
            var commonTest=Document.NewEffects();commonTest["defaults"]=new JsonObject{["particles"]=new JsonObject{["muzzle"]=LayerArray()!.DeepClone()}};Check(Native.Sample(commonTest.ToJsonString(),0,"muzzle",300).Length==6,"defaults-only native preview");
            var damage=doc.Weapon(weaponId)["parameters"]!["damage"]!.GetValue<int>();Change(()=>doc.Weapon(weaponId)["parameters"]!["damage"]=damage+1);Undo();Check(doc.Weapon(weaponId)["parameters"]!["damage"]!.GetValue<int>()==damage,"GUI undo");Redo();Check(doc.Weapon(weaponId)["parameters"]!["damage"]!.GetValue<int>()==damage+1,"GUI redo");
            Check(Save(),"native validation and atomic save");Check(!doc.Dirty&&File.Exists(gp+".bak"),"backup and clean");Check(File.ReadAllText(Path.Combine(root,"assets.sha256")).Contains(Document.Hash(doc.EffectsPath)+"  weapon_effects.json"),"effect integrity entry");var old=File.ReadAllText(gp);Change(()=>doc.Weapon(weaponId)["parameters"]!["magazine"]=1001);Check(!Save(),"native reject illegal magazine");Check(File.ReadAllText(gp)==old,"invalid save leaves file intact");Undo();
            var textureFull=Paths.Resolve(root,rel);File.Move(textureFull,textureFull+".held");Check(!Save(),"missing texture refuses save");File.Move(textureFull+".held",textureFull);Check(Save(),"resource restored permits save");
            preview.ReloadImages();preview.TimeMs=300;timeline.Value=300;await Task.Delay(120);Refresh();using(var bitmap=new Bitmap(Width,Height)){DrawToBitmap(bitmap,new(0,0,Width,Height));bitmap.Save(Path.Combine(output,"01-weapon-and-particles.png"));}Check(preview.SampleCount==6&&preview.Error.Length==0,"GUI original alpha atlas drawing");
            var tab=Controls.OfType<TabControl>().Single();
            int oi=Array.IndexOf(args,"--original-data");bool originalPreview=false;if(oi>=0&&oi+1<args.Length)
            {
                string fx=Path.Combine(root,"fx");Directory.CreateDirectory(fx);var sourceFx=Path.Combine(Path.GetFullPath(args[oi+1]),"fx");var copied=new List<object>();foreach(var bundle in Directory.GetFiles(sourceFx,"*.gwfx")){var dest=Path.Combine(fx,Path.GetFileName(bundle));File.Copy(bundle,dest,true);Check(Document.Hash(bundle)==Document.Hash(dest),"original bundle byte identity");copied.Add(new{source=bundle,sha256=Document.Hash(bundle)});}File.WriteAllText(Path.Combine(output,"original-preview-provenance.json"),JsonSerializer.Serialize(copied,Document.JsonOptions));preview.ReloadImages();Check(preview.OriginalImages.ContainsKey(0x668997),"actual original blood image available");channel.SelectedIndex=5;
                Change(()=>{var a=EnsureLayers();a.Clear();a.Add(new JsonObject{["texture"]=0x668997,["count"]=8,["radius"]=250,["lifetimeMs"]=500,["speed"]=1500,["spread"]=1.0,["rotationRandom"]=3.0,["color"]=new JsonArray(.65,.025,.02,1),["atlas"]=new JsonObject{["columns"]=4,["rows"]=4,["frames"]=16,["fps"]=32}});EnsureEvent("lights","shot")["enabled"]=false;});Check(Save(),"original blood effect saved");preview.TimeMs=130;timeline.Value=130;originalPreview=true;
            }
            Check(((Choice)channel.SelectedItem!).Key==(originalPreview?"humanBlood":"muzzle")&&layers.SelectedIndex==0,"dropdown selection values correct");
            tab.SelectedTab=tab.TabPages.Cast<TabPage>().Single(t=>t.Text=="粒子");await Task.Delay(80);Refresh();using(var bitmap=new Bitmap(Width,Height)){DrawToBitmap(bitmap,new(0,0,Width,Height));bitmap.Save(Path.Combine(output,"02-effect-properties.png"));}if(originalPreview)Check(preview.SampleCount==8&&preview.Error.Length==0,"original blood atlas rendered");
            tab.SelectedTab=tab.TabPages.Cast<TabPage>().Single(t=>t.Text=="音");await Task.Delay(80);Refresh();using(var bitmap=new Bitmap(Width,Height)){DrawToBitmap(bitmap,new(0,0,Width,Height));bitmap.Save(Path.Combine(output,"03-sound-settings.png"));}
            string iconSource=png;if(oi>=0&&oi+1<args.Length)
            {
                var originalIconIndex=Path.Combine(args[oi+1],"weapon-icons/index.tsv");if(File.Exists(originalIconIndex)){var row=File.ReadAllLines(originalIconIndex).Skip(1).Select(s=>s.Split('\t')).FirstOrDefault(r=>r.Length==3&&r[1]==weaponId.ToString());if(row is not null){iconSource=Path.Combine(Path.GetDirectoryName(originalIconIndex)!,row[2]);File.WriteAllText(Path.Combine(output,"icon-preview-provenance.json"),JsonSerializer.Serialize(new{source=iconSource,sha256=Document.Hash(iconSource)},Document.JsonOptions));}}
            }
            var beforeIcon=WeaponIcons.Override(doc.Weapon(weaponId));ImportIconFile(iconSource);var customIcon=WeaponIcons.Override(doc.Weapon(weaponId));Check(customIcon is not null&&customIcon.StartsWith("weapon_editor_assets/icons/",StringComparison.Ordinal),"icon imported into data relative JSON path");Check(iconPreview.Image is not null,"icon alpha preview loaded");Undo();Check(WeaponIcons.Override(doc.Weapon(weaponId))==beforeIcon,"icon undo");Redo();Check(WeaponIcons.Override(doc.Weapon(weaponId))==customIcon,"icon redo");Check(Save(),"native accepts icon JSON");Check(Document.Open(gp).Weapon(weaponId)["visual"]?["iconPath"]?.GetValue<string>()==customIcon,"saved icon path reopens");
            string fullIcon=Paths.Resolve(root,customIcon!);var accepted=File.ReadAllText(gp);File.Move(fullIcon,fullIcon+".held");Check(!Save(),"missing icon refuses save");Check(File.ReadAllText(gp)==accepted,"missing icon retains accepted settings");File.Move(fullIcon+".held",fullIcon);Check(Save(),"restored icon saves");Check(File.ReadAllText(Path.Combine(root,"assets.sha256")).Contains(Document.Hash(fullIcon)+"  "+customIcon),"icon integrity hash updated");
            tab.SelectedTab=tab.TabPages.Cast<TabPage>().Single(t=>t.Text=="アイコン");await Task.Delay(80);Refresh();using(var bitmap=new Bitmap(Width,Height)){DrawToBitmap(bitmap,new(0,0,Width,Height));bitmap.Save(Path.Combine(output,"04-weapon-icon.png"));}
            timeline.Value=0;Play();await Task.Delay(140);Check(playing&&preview.TimeMs>0,"playback clock");Stop();Check(!playing,"stop playback");audio.Play(Paths.Resolve(root,soundPath),.3);await Task.Delay(100);audio.Stop();checks++;
            File.WriteAllText(Path.Combine(output,"gui-results.json"),JsonSerializer.Serialize(new{passed=true,checks,app=typeof(Native).Assembly.Location,sharedDllSha256=Document.Hash(Path.Combine(AppContext.BaseDirectory,"MGO2MTWpnEffects.dll")),originalPreview,originalAssetsBundled=false},Document.JsonOptions));Environment.ExitCode=0;
        }
        catch(Exception ex){File.WriteAllText(Path.Combine(output,"gui-results.json"),JsonSerializer.Serialize(new{passed=false,checks,error=ex.ToString()},Document.JsonOptions));Environment.ExitCode=1;}
        finally{Close();}
    }
}
