using System.Text.Json.Nodes;
namespace Mgo2Mt.WpnEditor;
public sealed record Field(string Key,string Label,object Default,double Min=double.MinValue,double Max=double.MaxValue,string Help="")
{
    public Type Type=>Default.GetType();
}
public static class Fields
{
    public static double Number(JsonNode n)=>double.Parse(n.ToJsonString(),System.Globalization.CultureInfo.InvariantCulture);
    public static JsonNode? Read(JsonNode node,string key){foreach(var part in key.Split('.')){if(node is JsonArray a){if(!int.TryParse(part,out var i)||i<0||i>=a.Count)return null;node=a[i]!;}else node=node[part]!;if(node is null)return null;}return node;}
    public static object Get(JsonNode node,Field f){var n=Read(node,f.Key);if(n is null)return f.Default;if(f.Type==typeof(bool))return n.GetValue<bool>();if(f.Type==typeof(int))return checked((int)Number(n));if(f.Type==typeof(double))return Number(n);return n is JsonValue v&&v.TryGetValue<string>(out var s)?s:n.ToJsonString();}
    public static void Set(JsonObject node,Field field,object? value)
    {
        object converted=field.Type==typeof(string)?Convert.ToString(value,System.Globalization.CultureInfo.InvariantCulture)??"":Convert.ChangeType(value!,field.Type,System.Globalization.CultureInfo.InvariantCulture);
        if(converted is int or double){var d=Convert.ToDouble(converted);if(!double.IsFinite(d)||d<field.Min||d>field.Max)throw new InvalidDataException($"{field.Label} は {field.Min} ～ {field.Max} で指定してください。");}
        var parts=field.Key.Split('.');JsonNode parent=node;for(int i=0;i<parts.Length-1;i++){if(parent is JsonArray a){parent=a[int.Parse(parts[i])]!;}else{var o=parent.AsObject();o[parts[i]]??=int.TryParse(parts[i+1],out _)?new JsonArray():new JsonObject();parent=o[parts[i]]!;}}
        JsonNode? json=System.Text.Json.JsonSerializer.SerializeToNode(converted);if(field.Key=="texture"&&converted is string text&&uint.TryParse(text.StartsWith("0x",StringComparison.OrdinalIgnoreCase)?text[2..]:text,text.StartsWith("0x",StringComparison.OrdinalIgnoreCase)?System.Globalization.NumberStyles.HexNumber:System.Globalization.NumberStyles.Integer,System.Globalization.CultureInfo.InvariantCulture,out var key))json=JsonValue.Create(key);
        if(parent is JsonArray ar){int i=int.Parse(parts[^1]);while(ar.Count<=i)ar.Add(1.0);ar[i]=json;}else parent[parts[^1]]=json;
    }
    public static readonly Field[] Mechanics=[new("damage","HPダメージ",0,0,1000000),new("staminaDamage","スタミナダメージ",0,0,1000000),new("magazine","マガジン容量",30,0,1000),new("reserve","予備弾数",90,0,10000),new("intervalMs","発射間隔（ms）",0,0,60000,"変更すると原tick指定を解除します。0は原tick指定時のみ有効。"),new("fireIntervalTicks","原発射間隔（tick）",0,0,18000,"正の値へ変更するとms指定を解除します。"),new("reloadMs","リロード時間（ms）",0,0,60000,"正の値へ変更すると原リロードモーション時間指定を解除します。"),new("reloadRefillMs","弾の補充時点（ms）",0,0,60000),new("range","射程（ゲーム単位）",200000.0,0,1000000),new("automatic","押し続けて連射",false),new("tuning.chamberCapacity","薬室容量",0,0,8),new("tuning.weightKg","重量（kg）",0.0,0,100,"移動倍率=指定倍率÷(1+0.02×kg)。原作の重量計算式ではありません。"),new("tuning.moveSpeedScale","移動速度倍率",1.0,.1,2),new("tuning.reloadSpeedScale","リロード速度倍率",1.0,.1,5)];
    public static readonly Field[] Accuracy=[new("tuning.accuracy.base","基本のばらつき（µrad）",3000,0,100000),new("tuning.accuracy.maximum","最大のばらつき（µrad）",30000,0,100000),new("tuning.accuracy.perShot","1発ごとの増加（µrad）",4000,1,100000),new("tuning.accuracy.recovery","毎秒の回復（µrad）",12000,1,1000000),new("tuning.accuracy.movingMultiplier","移動時倍率",1.0,1,8),new("tuning.accuracy.crouchMultiplier","しゃがみ時倍率",1.0,.1,1),new("tuning.accuracy.proneMultiplier","伏せ時倍率",1.0,.1,1),new("tuning.accuracy.pellets","1射あたりの散弾数",1,1,32)];
    public static readonly Field[] Visual=[new("modelPath","武器モデル", ""),new("secondaryModelPath","補助モデル", ""),new("motionId","原モーションID",25,0,511),new("effectId","原エフェクトID",25,0,511),new("autoAim","AUTO AIM",true),new("tracer","曳光弾",false),new("flashTexture","閃光の原画像ID",0,0,16777215),new("smokeTexture","煙の原画像ID",0,0,16777215),new("lockRange","ロック距離",8000.0,0,1000000),new("lockWidth","ロック幅",500.0,0,1000000),new("lockYaw","ロック角度（rad）",.087266,0,3.1415927)];
    public static readonly Field[] Cues=[new("shotCue","発射の原音ID",0,0,1000000),new("impactCue","着弾の原音ID",0,0,1000000),new("bodyCue","身体命中の原音ID",0,0,1000000)];
    public static readonly Field[] Particle=[new("enabled","この層を表示",true),new("texture","画像パス / 原画像ID", "",Help:"data相対パス、または整数/0x形式の原画像ID。元画像には対応GWFXが必要です。"),new("count","粒子数",1,1,32),new("delayMs","開始を遅らせる（ms）",0,0,10000),new("emissionMs","放出を続ける時間（ms）",0,0,10000),new("lifetimeMs","1粒の寿命（ms）",500,1,60000),new("radius","基本の半径",100.0,.01,20000),new("additive","加算発光",false),new("stretch.0","横の伸び",1.0,.01,16),new("stretch.1","縦の伸び",1.0,.01,16),new("color.0","色：赤",1.0,0,1),new("color.1","色：緑",1.0,0,1),new("color.2","色：青",1.0,0,1),new("color.3","色：不透明度",1.0,0,1),new("velocity.0","速度 X",0.0,-50000,50000),new("velocity.1","速度 Y",0.0,-50000,50000),new("velocity.2","速度 Z",0.0,-50000,50000),new("speed","放出速度",0.0,0,50000),new("spread","放出角（rad）",0.0,0,Math.PI),new("gravity","重力",0.0,-50000,50000),new("rotation","初期回転（rad）",0.0,-100,100),new("rotationSpeed","回転速度（rad/s）",0.0,-100,100),new("sizeRandom","大きさのランダム幅",0.0,0,1),new("stretchRandom","伸びのランダム幅",0.0,0,1),new("alphaRandom","透明度のランダム幅",0.0,0,1),new("rotationRandom","回転のランダム幅",0.0,0,Math.PI),new("atlas.columns","アトラス：横のコマ数",1,1,64),new("atlas.rows","アトラス：縦のコマ数",1,1,64),new("atlas.frames","アトラス：使用コマ数",1,1,4096),new("atlas.fps","アトラス：毎秒のコマ数",0.0,0,240),new("atlas.loop","アトラス：繰り返す",false),new("atlas.randomStart","アトラス：開始コマをランダム",false)];
    public static readonly Field[] Light=[new("enabled","発光を有効",true),new("delayMs","開始を遅らせる（ms）",0,0,10000),new("durationMs","発光時間（ms）",80,1,60000),new("radius","照らす半径",2600.0,1,100000),new("intensity","明るさ",2.0,0,16),new("color.0","色：赤",1.0,0,1),new("color.1","色：緑",.64,0,1),new("color.2","色：青",.25,0,1)];
    public static readonly Field[] Sound=[new("enabled","音を有効",true),new("path","WAVの相対パス",""),new("cue","原音ID",0,0,1000000),new("delayMs","開始を遅らせる（ms）",0,0,60000),new("gain","音量倍率",1.0,0,4)];
    public static readonly Field[] Reticle=[new("enabled","照準を表示",true),new("color.0","照準色：赤",1.0,0,1),new("color.1","照準色：緑",.65,0,1),new("color.2","照準色：青",.17,0,1),new("color.3","照準の不透明度",1.0,0,1),new("thickness","線の太さ（px）",2.0,.5,16),new("length","線の長さ（px）",10.0,1,100),new("centerDot","中心の点を表示",true),new("minGap","最小の間隔（px）",6.0,0,100)];
}
