#include "multi_ui.h"
#include "multi_ui_audio.h"
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace mgo2mt::multi_ui;
namespace {
int checks=0;void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}
struct Fake final:AudioBackend {uint64_t token=0;unsigned starts=0,stops=0;bool fail=false,muted=false;std::vector<AudioNotification> events;
 bool start(const std::filesystem::path&,float,uint64_t t,std::string&e)override{++starts;token=t;if(fail)e="fixture load failure";return !fail;}
 std::vector<AudioNotification> poll()override{auto v=events;events.clear();return v;}void stop()override{++stops;}void mute(bool v)override{muted=v;}
 void report(AudioResult r,uint64_t t=0){events.push_back({t?t:token,r,r==AudioResult::failed?"fixture decoder failure":""});}
};
std::string layout(bool wait=true){return std::string(R"({"format":"MGO2MT.UI_LAYOUT.1","width":1280,"height":720,"elements":[{"id":"button","kind":"panel","screen":"title","x":10,"y":20,"width":100,"height":50,"onClick":[{"type":"playSound","sound":"sound.wav","waitForEnd":)")+(wait?"true":"false")+R"(},{"type":"setVariable","name":"message","value":"ready"},{"type":"setVisible","target":"after","visible":true},{"type":"emitEvent","name":"finish"}]},{"id":"after","kind":"panel","screen":"title","x":200,"y":20,"width":100,"height":50,"visible":false,"color":[255,0,0,255]}]})";}
bool has(const std::vector<ActionEvent>&v,std::string_view k){for(const auto&e:v)if(e.kind==k)return true;return false;}
std::string replace(std::string s,std::string_view a,std::string_view b){auto at=s.find(a);if(at==s.npos)throw std::runtime_error("fixture replacement");s.replace(at,a.size(),b);return s;}
}
int main(int argc,char**argv){try{check(argc==2,"fixture directory required");std::filesystem::path root=argv[1];std::filesystem::create_directories(root);{std::ofstream f(root/"sound.wav");f<<"fake backend fixture";}
 auto backend=std::make_unique<Fake>();auto*f=backend.get();Runtime runtime(std::move(backend));Context c;c.screen="title";c.state="idle";check(runtime.load_json(layout(),root),runtime.error().c_str());runtime.update(c,true,false);check(!runtime.click(9,20,c),"outside button passes through");check(runtime.click(20,30,c),"button consumes click");check(f->muted&&f->starts==1&&runtime.busy(),"muted native sound still controls completion");runtime.take_events();check(runtime.click(20,30,c)&&f->starts==1,"repeated button ignored while busy");runtime.update(c);check(runtime.take_events().empty(),"waiting has no fabricated timer completion");f->report(AudioResult::started);runtime.update(c);check(!has(runtime.take_events(),"event"),"started is not ended");f->report(AudioResult::completed,f->token+1);runtime.update(c);check(runtime.busy()&&runtime.take_events().empty(),"stale sound token ignored");f->report(AudioResult::completed);runtime.update(c);auto events=runtime.take_events();check(has(events,"event")&&has(events,"completed")&&!runtime.busy(),"ended releases subsequent actions");check(events.front().kind=="soundCompleted"&&events.back().kind=="completed","ordered completion sequence");std::vector<uint8_t> pixels(1280*720*4);check(runtime.paint(pixels,1280,720,c)&&pixels[(25*1280+205)*4]==255,"setVisible changes rendered pixels");
 check(runtime.trigger("button",c),"start another sequence");runtime.take_events();runtime.update(c,false);check(!runtime.busy()&&has(runtime.take_events(),"cancelled"),"focus loss cancels");f->report(AudioResult::completed);runtime.update(c,true);check(!has(runtime.take_events(),"event"),"cancelled late end cannot dispatch");
 check(runtime.trigger("button",c),"third sequence");runtime.take_events();auto changed=c;changed.state="loading";runtime.update(changed);check(!runtime.busy()&&has(runtime.take_events(),"cancelled"),"page/state change cancels");pixels.assign(pixels.size(),0);check(runtime.paint(pixels,1280,720,changed)&&pixels[(25*1280+205)*4+3]==0,"scope clears temporary visibility");
 check(runtime.load_json(layout(),root),"reload fixture");f->fail=true;check(runtime.trigger("button",c),"failed button consumed");events=runtime.take_events();check(has(events,"failed")&&!has(events,"event")&&!runtime.busy(),"synchronous load failure stops all remaining actions");f->fail=false;check(runtime.trigger("button",c),"asynchronous failure setup");runtime.take_events();f->report(AudioResult::failed);runtime.update(c);events=runtime.take_events();check(has(events,"failed")&&!has(events,"event"),"decoder failure cannot run event");
 check(runtime.load_json(layout(false),root),"nonwait fixture");check(runtime.trigger("button",c),"nonwait click");check(!has(runtime.take_events(),"event"),"nonwait still waits for real playback start");f->report(AudioResult::started);runtime.update(c);check(has(runtime.take_events(),"event")&&runtime.busy(),"nonwait proceeds after started while sound remains");f->report(AudioResult::completed);runtime.update(c);check(!runtime.busy(),"nonwait sound drains");
 for(const auto& bad:{replace(layout(),"sound.wav","../sound.wav"),replace(layout(),"sound.wav","https://host/sound.mp3"),replace(layout(),"sound.wav","missing.wav"),replace(layout(),"\"target\":\"after\"","\"target\":\"missing\""),replace(layout(),"\"type\":\"emitEvent\"","\"type\":\"execute\""),replace(layout(),"\"waitForEnd\":true","\"waitForEnd\":true,\"loop\":true")})check(!runtime.load_json(bad,root)&&!runtime.ready(),"unsafe/unsupported layout rejected atomically");
 check(runtime.load_json(replace(layout(),"\"x\":10","\"visible\":false,\"x\":10"),root),"hidden button fixture");check(!runtime.click(20,30,c)&&!runtime.trigger("button",c),"hidden button cannot trigger");
 std::cout<<"PASS "<<checks<<" shared UI audio action ordering/cancel/failure/scope/pointer/render checks\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
