#include "character_renderer.h"
#include <algorithm>
#include <fstream>
#include <iostream>
using namespace mgo2mt;using Microsoft::WRL::ComPtr;
namespace {
void check(bool b,const char*m){if(!b)throw std::runtime_error(m);}
void ok(HRESULT h){check(SUCCEEDED(h),"WARP call");}
std::vector<uint8_t> pixels(ID3D11Device*d,ID3D11DeviceContext*c,const CharacterRenderer&r){ComPtr<ID3D11Resource> resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D> texture;ok(resource.As(&texture));D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> staging;ok(d->CreateTexture2D(&desc,nullptr,&staging));c->CopyResource(staging.Get(),texture.Get());D3D11_MAPPED_SUBRESOURCE m{};ok(c->Map(staging.Get(),0,D3D11_MAP_READ,0,&m));std::vector<uint8_t> result(desc.Width*desc.Height*4);for(size_t y=0;y<desc.Height;++y)std::copy_n(static_cast<uint8_t*>(m.pData)+y*m.RowPitch,desc.Width*4,result.data()+y*desc.Width*4);c->Unmap(staging.Get(),0);return result;}
CharacterModel panel(float z){CharacterModel m;m.bounds={-10000,-10000,z,10000,10000,z};for(auto p:std::array<std::array<float,2>,4>{{{-10000,-10000},{10000,-10000},{10000,10000},{-10000,10000}}}){ModelVertex v{};v.x=p[0];v.y=p[1];v.z=z;v.nz=-1;v.lr=v.lg=v.lb=.1f;v.lit=1;m.vertices.push_back(v);}m.indices={0,1,2,0,2,3};m.parts.push_back({0,6,0,0});m.textures.push_back({4,4,9,{255,255,255,255,0,0,0,0}});return m;}
}
int main(){try{
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;ok(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));
 auto bright=panel(2000);for(auto&v:bright.vertices)v.lr=v.lg=v.lb=.8f;
 CharacterRenderer surface(d.Get(),panel(10000)),body(d.Get(),bright),wall(d.Get(),panel(1000)),behind(d.Get(),panel(3000));WorldView view{{0,0,0},{0,0,1}};
 auto clear=[&]{surface.render(c.Get(),0,false,&view);return pixels(d.Get(),c.Get(),surface);};auto base=clear();
 auto draw=[&](float alpha){body.render(c.Get(),0,false,&view,&surface,nullptr,{},nullptr,nullptr,nullptr,alpha);return pixels(d.Get(),c.Get(),surface);};auto full=draw(1);clear();auto half=draw(.5f);const size_t center=(392/2*616+616/2)*4;
 for(unsigned i=0;i<3;++i)check(std::abs(int(half[center+i])-int((unsigned(full[center+i])+base[center+i])/2))<=2,"Half body opacity blends with world pixels");
 base=clear();check(draw(0)==base,"Invisible body changes neither pixels nor depth");draw(.5f);behind.render(c.Get(),0,false,&view,&surface);auto after=pixels(d.Get(),c.Get(),surface);clear();behind.render(c.Get(),0,false,&view,&surface);check(after==pixels(d.Get(),c.Get(),surface),"Fading body does not write opaque depth");
 clear();wall.render(c.Get(),0,false,&view,&surface);base=pixels(d.Get(),c.Get(),surface);check(draw(.5f)==base,"Wall still occludes transparent body");
 clear();draw(.5f);check(draw(1)==full,"Next opaque arm or weapon draw restores opaque state");
 auto overlay=bright;overlay.parts[0].surfaceAlpha=1;overlay.textures[0]={4,4,11,{64,64,0,0,0,0,0,0,255,255,255,255,0,0,0,0}};for(auto&v:overlay.vertices)v.aa=.5f;CharacterRenderer decal(d.Get(),overlay);
 base=clear();decal.render(c.Get(),0,false,&view,&surface);auto blended=pixels(d.Get(),c.Get(),surface);for(unsigned i=0;i<3;++i){const float expected=base[center+i]+(full[center+i]-base[center+i])*(64.f/255.f)*.5f;check(std::abs(float(blended[center+i])-expected)<2,"Original surface multiplies image and vertex alpha");}
 auto combined=overlay;auto background=panel(10000);for(auto v:background.vertices)combined.vertices.push_back(v);for(auto index:background.indices)combined.indices.push_back(index+4);combined.parts.push_back({6,6,0,0});CharacterRenderer layers(d.Get(),combined);layers.render(c.Get(),0,false,&view);auto sorted=pixels(d.Get(),c.Get(),layers);check(sorted==blended,"Opaque surface rendered before earlier-listed alpha overlay");
 layers.render(c.Get(),0,false,&view,nullptr,nullptr,{},nullptr,nullptr,nullptr,1.f,CharacterPass::opaque);auto actorModel=panel(3000);for(auto&v:actorModel.vertices)v.lr=v.lg=v.lb=.4f;CharacterRenderer actor(d.Get(),actorModel);actor.render(c.Get(),0,false,&view,&layers);auto actorPixels=pixels(d.Get(),c.Get(),layers);layers.render(c.Get(),0,false,&view,&layers,nullptr,{},nullptr,nullptr,nullptr,1.f,CharacterPass::alpha);auto composited=pixels(d.Get(),c.Get(),layers);for(unsigned i=0;i<3;++i){const float expected=actorPixels[center+i]+(full[center+i]-actorPixels[center+i])*(64.f/255.f)*.5f;check(std::abs(float(composited[center+i])-expected)<2,"Deferred stage alpha correctly overlays actor behind cloth");}
 CharacterRenderer blank(d.Get(),panel(-10000));auto clouds=panel(20000);clouds.parts[0].materialShader=0x100064;clouds.textures={{4,4,9,{0,248,0,248,0,0,0,0}},{4,4,9,{31,0,31,0,0,0,0,0}},{4,4,9,{224,7,224,7,0,0,0,0}}};clouds.parts[0].original.textures.resize(2);clouds.parts[0].original.textures[0].image=0;clouds.parts[0].original.textures[1].image=1;for(auto&v:clouds.vertices){v.ar=.5f;v.ag=.75f;v.ab=1;v.aa=.25f;}SkyFrame skyDraw;skyDraw.color={.8f,.7f,.6f};skyDraw.fogColor={.2f,.4f,.6f};skyDraw.fog=.177f;
 for(bool third:{false,true}){if(third){clouds.parts[0].materialShader=0x100067;clouds.parts[0].original.textures.resize(3);clouds.parts[0].original.textures[2].image=2;}CharacterRenderer sky(d.Get(),clouds,true);blank.render(c.Get(),0,false,&view);sky.render(c.Get(),0,false,&view,&blank,nullptr,{},nullptr,nullptr,nullptr,1.f,CharacterPass::all,&skyDraw);auto image=pixels(d.Get(),c.Get(),blank);const std::array<float,3> authored{.3f,third?.525f:0.f,.15f};for(unsigned i=0;i<3;++i){const float expected=(authored[i]*(1-.177f)+skyDraw.fogColor[i]*.177f)*255;check(std::abs(float(image[center+i])-expected)<2,"Original sky crossfade, optional third layer, authored color and fog composition");}check(image[center+3]==255,"Sky vertex alpha mixes textures, never punches transparent holes");}
 bool rejected=false;try{draw(-1);}catch(const std::invalid_argument&){rejected=true;}check(rejected,"Invalid opacity rejected");
 std::cout<<"Body alpha interpolation, full disappearance, depth, occlusion and opaque-state restore PASS\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
