#include "combat_debug_flights.h"
#include "host_protocol.h"
#include <iostream>
#include <limits>
using namespace mgo2mt;using namespace combat;
namespace {void check(bool b,const char*m){if(!b)throw std::runtime_error(m);}bool rejected(const wire::Record&r){try{wire::encode(r);return false;}catch(const wire::Invalid&){return true;}}}
int main(){try{
 projectile::Pool pool;pool.reset({9,3});projectile::Owner owner{0,1,100,1};projectile::Shot shot{{9,3},owner,77,52,{0,1000,0},{1,0,0}};auto profile=projectile::native_throw(52);check(pool.spawn(shot,profile,100)==projectile::Submit::accepted,"Spawn real grenade");Vec3 actualFrom{},actualTo{};pool.advance(120,[&](Vec3 p,Vec3 d,float length,projectile::Owner){actualFrom=p;for(unsigned j=0;j<3;++j)actualTo[j]=p[j]+d[j]*length;return std::optional<projectile::Contact>{{length*.5f,{-1,0,0},{},0}};});auto flight=pool.debug_flights();check(flight.size()==1&&flight[0].traceFrom==actualFrom&&flight[0].traceTo==actualTo&&flight[0].simulatedAt==120,"Last exact HOST trace, not inferred path");check(flight[0].position!=flight[0].traceTo,"Bounce position distinct from queried segment");
 wire::DebugFlights message{9,3,{0,1,100},1,1,10,120,false,flight};auto bytes=wire::encode(message);check(std::get<wire::DebugFlights>(wire::decode(bytes))==message,"Debug roundtrip");for(unsigned i=1;i<16;++i){auto f=flight[0];f.shot+=i;message.flights.push_back(f);}bytes=wire::encode(message);check(bytes.size()==1092&&bytes.size()<=1152,"Maximum list fits application payload");host::Message payload;payload.channel=1;payload.reliable=true;payload.payload=bytes;check(host::encode({0,{payload}},{123,456}).size()<=1172,"Real encrypted transport packet fits datagram");
 auto bad=message;bad.flights.push_back(flight[0]);check(rejected(bad),"Seventeenth entry rejected");bad=message;bad.flights[1].shot=bad.flights[0].shot;check(rejected(bad),"Duplicate flight rejected");bad=message;bad.flights[0].position[0]=std::numeric_limits<float>::quiet_NaN();check(rejected(bad),"Nonfinite state rejected");bad=message;bad.flights[0].simulatedAt=121;check(rejected(bad),"Future simulation timestamp rejected");bytes=wire::encode(message);bytes[51]=17;bool invalid=false;try{wire::decode(bytes);}catch(const wire::Invalid&){invalid=true;}check(invalid,"Oversized wire count rejected before allocation");
 wire::Input input;input.epoch=9;input.life=1;input.sequence=10;input.debugPhysics=true;input.suspended=true;check(std::get<wire::Input>(wire::decode(wire::encode(input)))==input,"Debug request valid with suspended gameplay");auto newer=input;newer.sequence=11;newer.debugPhysics=false;check(!wire::coalesce_input(input,newer).debugPhysics,"Latest OFF wins input coalescing");
 Snapshot snapshot;snapshot.epoch=9;snapshot.revision=1;Player player;player.identity={0,1,100};player.life=1;player.alive=true;snapshot.players[0]=player;wire::Offer offer{9,player.identity};DebugFlightReceiver receiver;check(!receiver.receive(message,offer,snapshot,500),"Off by default");receiver.request(true,10,1);check(receiver.receive(message,offer,snapshot,500)&&receiver.state(),"Admitted recipient and exact owner life");check(!receiver.receive(message,offer,snapshot,501),"Repeated diagnostic sequence rejected");bad=message;bad.sequence=2;bad.scene=2;check(!receiver.receive(bad,offer,snapshot,510),"Old scene rejected");bad=message;bad.sequence=2;bad.recipient.character=101;check(!receiver.receive(bad,offer,snapshot,510),"Recipient mismatch rejected");bad=message;bad.sequence=2;bad.flights[0].owner.life=2;check(!receiver.receive(bad,offer,snapshot,510),"Owner life mismatch rejected");receiver.poll(snapshot,wire::Status::active,1001);check(!receiver.state(),"Stale diagnostics expire after 500 ms");receiver.request(false,11,1);check(!receiver.receive(message,offer,snapshot,1010),"OFF ignores queued diagnostic");receiver.request(true,12,1);message.sequence=3;message.at=130;check(!receiver.receive(message,offer,snapshot,1100),"Older activation input cannot reappear after re-enable");message.inputSequence=12;check(receiver.receive(message,offer,snapshot,1100),"New activation accepted");snapshot.players[0]->life=2;receiver.poll(snapshot,wire::Status::active,1110);check(!receiver.state(),"Respawn clears old-life diagnostics");
 pool.reset({9,4});check(pool.debug_flights().empty(),"Scene replacement clears actual flight pool");std::cout<<"Actual HOST point sweeps, GWCB22 1092-byte budget, request/OFF/scope/replay/stale validation PASS\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
