#include "combat_service.h"
#include "combat_initial_profile.h"
#include <iostream>
using namespace mgo2mt;using namespace combat;
namespace {void check(bool b,const char*m){if(!b)throw std::runtime_error(m);}std::vector<wire::DebugFlights> debug(std::vector<Delivery> ds,Identity expected){std::vector<wire::DebugFlights>out;for(const auto&d:ds){auto record=wire::decode(d.payload);if(auto f=std::get_if<wire::DebugFlights>(&record)){check(d.recipient==expected&&f->recipient==expected&&d.payload.size()<=1152,"Only requesting admitted peer gets bounded diagnostics");out.push_back(*f);}}return out;}}
int main(){try{
 auto world=std::make_shared<const stage::Collision>(stage::Collision::make({{-200000,0,-200000},{200000,0,-200000},{200000,0,200000},{-200000,0,200000}},{{{0,1,2}},{{0,2,3}}}));Service service(9);auto profiles=initial_profiles(20,1,0);service.configure(world,profiles);Identity self{0,1,100},other{1,2,101};Pose pose;pose.feet={0,2,0};auto remote=pose;remote.feet[0]=10000;
 for(auto id:{self,other})check(service.admit(id)&&service.receive(id,wire::encode(wire::Accept{9}),0),"Admit both peers");auto&authority=service.authority();check(authority.join(self,1,pose,1000,1000,std::array<uint16_t,1>{52},0)&&authority.join(other,2,remote,1000,1000,std::array<uint16_t,1>{52},0),"Host grants");authority.active(true);service.deliveries();check(bool(authority.fire(self,{9,1,52,{0,0,1}},0)),"Actual grenade launched");service.poll(10);check(debug(service.deliveries(),self).empty(),"Default mode sends no diagnostics");
 wire::Input request;request.epoch=9;request.sequence=1;request.pose=pose;request.weapon=52;request.life=1;request.suspended=true;request.debugPhysics=true;check(!service.receive({0,99,100},wire::encode(request),10),"Forged admission rejected");check(service.receive(self,wire::encode(request),10),"F12 while gameplay suspended accepted");service.poll(20);auto first=debug(service.deliveries(),self);check(first.size()==1&&first[0].flights.size()==1&&first[0].flights[0].simulatedAt==20,"Read-only debug retains actual HOST flight under suspended UI");const auto position=first[0].flights[0].position;
 service.poll(50);check(debug(service.deliveries(),self).empty(),"Ten Hz diagnostics rate bound");request.sequence=2;request.debugPhysics=false;check(service.receive(self,wire::encode(request),50),"OFF accepted");service.poll(50);auto off=debug(service.deliveries(),self);check(off.size()==1&&off[0].flights.empty(),"OFF sends one clearing record");check(authority.debug_flights().size()==1&&authority.debug_flights()[0].position!=position,"Turning diagnostics off never stops simulation");service.poll(100);check(debug(service.deliveries(),self).empty(),"No subsequent OFF traffic");
 request.sequence=3;request.debugPhysics=true;check(service.receive(self,wire::encode(request),100),"Re-enable accepted");service.poll(110);auto again=debug(service.deliveries(),self);check(again.size()==1&&again[0].sequence>off[0].sequence&&again[0].inputSequence==3,"New request serial and sequence propagated");service.poll(700);auto expired=debug(service.deliveries(),self);check(expired.size()==1&&expired[0].flights.empty(),"Stale peer request stops diagnostics");service.remove(self);service.poll(710);check(debug(service.deliveries(),self).empty(),"Removed peer never receives diagnostics");
 std::cout<<"HOST debug admission, suspended request, exact live flight, rate/OFF/stale/removal delivery PASS\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
