#include "body_hit_presentation.h"
#include "blast_pose.h"
#include "combat_death.h"
#include "combat_initial_profile.h"
#include "combat_particle_renderer.h"
#include <fstream>
#include <iostream>
using namespace mgo2mt;
using namespace mgo2mt::combat;
using Microsoft::WRL::ComPtr;
namespace {
unsigned checks=0;
void check(bool value,const char* why){++checks;if(!value)throw std::runtime_error(why);}
void ok(HRESULT h){check(SUCCEEDED(h),"D3D11 WARP operation");}
std::vector<char> read(const std::filesystem::path& p){std::ifstream f(p,std::ios::binary);check(bool(f),"original asset missing");return {std::istreambuf_iterator<char>(f),{}};}
const Identity shooter{0,1,100},target{1,1,101};
auto floor(){return std::make_shared<const stage::Collision>(stage::Collision::make({{-50000,0,-50000},{50000,0,-50000},{50000,0,50000},{-50000,0,50000}},{{{0,1,2}},{{0,2,3}}}));}
std::unique_ptr<Authority> host(bool gekko=false){auto h=std::make_unique<Authority>();auto profiles=initial_profiles(20,1,0);for(auto&w:profiles)w.nativeAkAccuracy=false;h->begin(7,floor(),profiles);check(h->join(shooter,1,{{0,2,-3000}},1000,1000,std::array<uint16_t,1>{25},0),"shooter admitted");check(h->join(target,2,{{0,2,0}},1000,1000,std::array<uint16_t,1>{25},0),"target admitted");if(gekko)check(h->assign_special(target,special_pc::Kind::gekko,true,0)==Reject::none,"original Gekko form");h->active(true);return h;}
CharacterModel panel(){CharacterModel m;m.bounds={-20000,0,-20000,20000,10000,20000};
 for(auto p:std::array<Vec3,8>{{{-20000,0,-20000},{20000,0,-20000},{20000,0,20000},{-20000,0,20000},{-20000,0,10000},{20000,0,10000},{20000,10000,10000},{-20000,10000,10000}}}){ModelVertex v{};v.x=p[0];v.y=p[1];v.z=p[2];v.ny=1;v.lr=.36f;v.lg=.4f;v.lb=.44f;v.lit=1;m.vertices.push_back(v);}m.indices={0,2,1,0,3,2,4,5,6,4,6,7};m.parts.push_back({0,12,0,0});m.textures.push_back({4,4,9,{255,255,255,255,0,0,0,0}});return m;}
void geometry(){
 CharacterModel m;for(auto p:std::array<Vec3,3>{{{-100,-100,0},{100,-100,0},{0,100,0}}}){ModelVertex v{};v.x=p[0];v.y=p[1];v.z=p[2];m.vertices.push_back(v);}m.indices={0,1,2};
 Event e;e.kind=EventKind::damage;e.hpDamage=100;e.position={0,0,-25};e.normal={0,0,-1};auto point=body_hit::surface(e,m,{},0,100);check(point&&std::hypot((*point)[0],(*point)[1],(*point)[2])<.01f,"proxy hit projects onto visible triangle");
 e.position={0,150,-20};point=body_hit::surface(e,m,{},0,100);check(point&&std::abs((*point)[1]-100)<.01f,"off-ray proxy uses nearest body surface");
 e.position={975,200,3000};e.normal={-1,0,0};point=body_hit::surface(e,m,{1000,200,3000},1.57079632679f,100);check(point&&std::hypot((*point)[0]-1000,(*point)[1]-200,(*point)[2]-3000)<.01f,"skin-space yaw and world origin match renderer");
 e.normal={};check(!body_hit::surface(e,m,{},0,100),"fall and burn events do not create body surface hits");e.normal={0,0,-1};e.position={0,0,-1000};check(!body_hit::surface(e,m,{},0,100),"late remote pose cannot move an effect across the scene");
 e.position={};e.hpDamage=0;check(!body_hit::surface(e,m,{},0,100),"stamina-only event has no blood");
 mounted::FlightPresentation clock;Player p;p.identity=target;p.life=1;p.alive=true;p.flightId=1;p.blastFlight=true;p.stunned=true;
 auto f=clock.update(7,&p,10);check(f&&f->blast&&!f->landing,"stunned blast still has airborne presentation");p.stunned=false;p.flightId=0;p.blastFlight=false;f=clock.update(7,&p,20);check(f&&f->blast&&f->landing,"landing retains blast kind after HOST flight ends");p.life=2;check(!clock.update(7,&p,30),"respawn clears old blast transition");
 mounted::FlightPosition position;p.flightId=5;p.pose.feet={100,200,300};position.update(7,p,10);p.pose.feet={200,400,600};position.update(7,p,20);p.blastFlight=true;check(position.update(7,p,25)==p.pose.feet,"same serial different flight kind resets interpolation");
 for(bool gekko:{false,true}){auto h=host(gekko);auto result=h->fire(shooter,{7,1,25,{0,0,1}},0);check(bool(result),"actual HOST accepted shot");auto hit=std::find_if(result.events.begin(),result.events.end(),[](const Event&e){return e.kind==EventKind::damage;});check(hit!=result.events.end()&&hit->hpDamage&&hit->target==target&&hit->targetLife==1,"human and Gekko damage carries exact target incarnation");check(hit->position[1]>1000&&hit->position[2]<1000&&hit->normal==Vec3{0,0,-1},"HOST body damage retains shot intersection and direction");}
}
struct Image {unsigned width=0,height=0;std::vector<uint8_t> rgba;};
Image capture(ID3D11Device*d,ID3D11DeviceContext*c,const CharacterRenderer&r){ComPtr<ID3D11Resource> resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D> texture;ok(resource.As(&texture));D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> copy;ok(d->CreateTexture2D(&desc,nullptr,&copy));c->CopyResource(copy.Get(),texture.Get());D3D11_MAPPED_SUBRESOURCE map{};ok(c->Map(copy.Get(),0,D3D11_MAP_READ,0,&map));Image result{desc.Width,desc.Height,std::vector<uint8_t>(size_t(desc.Width)*desc.Height*4)};for(unsigned y=0;y<desc.Height;++y)std::copy_n(static_cast<uint8_t*>(map.pData)+y*map.RowPitch,desc.Width*4,result.rgba.data()+size_t(y)*desc.Width*4);c->Unmap(copy.Get(),0);return result;}
void save(const std::filesystem::path&p,Image image){for(size_t i=0;i<image.rgba.size();i+=4)std::swap(image.rgba[i],image.rgba[i+2]);BITMAPFILEHEADER b{};BITMAPINFOHEADER h{};h.biSize=sizeof(h);h.biWidth=LONG(image.width);h.biHeight=-LONG(image.height);h.biPlanes=1;h.biBitCount=32;h.biSizeImage=DWORD(image.rgba.size());b.bfType=0x4d42;b.bfOffBits=sizeof(b)+sizeof(h);b.bfSize=b.bfOffBits+h.biSizeImage;std::ofstream file(p,std::ios::binary);file.write(reinterpret_cast<char*>(&b),sizeof(b));file.write(reinterpret_cast<char*>(&h),sizeof(h));file.write(reinterpret_cast<char*>(image.rgba.data()),image.rgba.size());check(bool(file),"capture saved");}
void original_capture(const std::filesystem::path&data,const std::filesystem::path&bundle,const std::filesystem::path&out){
 std::filesystem::create_directories(out);CharacterCatalog human(read(data/"character/appearance.gwc")),gekko(read(data/"special/gekko.gwc"));PlayerMotionBank motion(read(data/"character/player.gwmot"));
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;ok(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));CharacterRenderer stage(d.Get(),panel());stage.resize_target(d.Get(),1280,720);particles::Renderer renderer(d.Get(),data/"fx/original.gwfx");renderer.add_bundle(bundle);
 std::array<uint8_t,28> appearance{};appearance[2]=11;appearance[3]=22;appearance[15]=46;appearance[17]=57;
 std::ofstream report(out/"validation.json");report<<"{\"offline_render\":true,\"scene\":\"synthetic studio\",\"device\":\"WARP\",\"blood\":[";
 for(bool large:{false,true}){
  auto h=host(large);auto result=h->fire(shooter,{7,1,25,{0,0,1}},0);auto s=h->snapshot();auto&catalog=large?gekko:human;auto body=catalog.assemble(large?std::array<uint8_t,28>{}:appearance);check(body.ready(),"original body assembled");auto pose=large?catalog.sample_pose(0,0):*motion.sample(PlayerMotion::Idle,0);catalog.pose(body,pose);Vec3 origin=s.players[1]->pose.feet;if(large)origin[1]+=special_pc::native_gekko.modelFeetOffset;
  auto hit=std::find_if(result.events.begin(),result.events.end(),[](const Event&e){return e.kind==EventKind::damage;});check(hit!=result.events.end(),"HOST body impact for render");auto point=body_hit::surface(*hit,body.model,origin,0,large?2000.f:650.f);check(bool(point),"actual original skin surface located");hit->position=*point;
  particles::Pool pool;pool.synchronize(7,1,0,0);pool.dispatch({&*hit,1},s,0);auto sprites=pool.sprites(s,90);check(!sprites.empty(),"original blood emitted from HOST hit");CharacterRenderer actor(d.Get(),body.model);WorldView view;view.eye=large?Vec3{-4100,2600,-6000}:Vec3{-1700,1600,-2800};view.direction=body_hit::detail::sub(large?Vec3{0,2000,0}:Vec3{0,1050,0},view.eye);
  stage.render(c.Get(),0,false,&view);actor.render(c.Get(),0,false,&view,&stage,&origin);auto before=capture(d.Get(),c.Get(),stage);check(renderer.render(c.Get(),stage,view,sprites),"blood rendered using original BC images");auto after=capture(d.Get(),c.Get(),stage);size_t changed=0;for(size_t i=0;i<after.rgba.size();i+=4)if(!std::equal(after.rgba.begin()+i,after.rgba.begin()+i+3,before.rgba.begin()+i))++changed;check(changed>20,"blood visible outside opaque skin");save(out/(large?"02-gekko-blood.bmp":"01-human-blood.bmp"),after);if(large)report<<',';report<<"{\"gekko\":"<<(large?"true":"false")<<",\"changed_pixels\":"<<changed<<",\"emitter\":["<<(*point)[0]<<','<<(*point)[1]<<','<<(*point)[2]<<"]}";
 }
 // Use the actual thrown/fused grenade path, with the owner caught in its blast.
 Authority h;auto profiles=initial_profiles(20,1,0);h.begin(8,floor(),profiles);Pose spawn;spawn.feet={0,2,0};spawn.pitch=-1.3f;check(h.join(shooter,1,spawn,10000,1000,std::array<uint16_t,1>{52},0),"grenade owner admitted");h.active(true);check(bool(h.fire(shooter,{8,1,52,{0,std::sin(spawn.pitch),std::cos(spawn.pitch)}},0)),"self grenade thrown");Decision burst;for(uint64_t now=20;now<=2020;now+=20){h.advance(now);auto step=h.advance_projectiles(now);burst.events.insert(burst.events.end(),step.events.begin(),step.events.end());}auto s=h.snapshot();check(s.players[0]->alive&&s.players[0]->blastFlight&&s.players[0]->hp<10000,"own grenade starts living HOST blast flight");auto kick=std::find_if(burst.events.begin(),burst.events.end(),[](const Event&e){return e.kind==EventKind::knockback;});check(kick!=burst.events.end()&&kick->source==shooter&&kick->target==shooter,"self knockback event");float start=s.players[0]->pose.feet[1];for(uint64_t now=2040;now<=2300;now+=20)h.advance(now);s=h.snapshot();check(s.players[0]->pose.feet[1]>start+50,"owner is actually lifted by HOST physics");
 auto body=human.assemble(appearance);mounted::FlightFrame f{s.players[0]->flightId,.3,false,true};auto pose=presentation::blast_pose(motion,f);check(bool(pose),"original down motion present");human.pose(body,*pose);CharacterRenderer actor(d.Get(),body.model);Vec3 origin=s.players[0]->pose.feet;WorldView view;view.eye={-2800,1500,-3600};view.direction=body_hit::detail::sub(Vec3{0,800,0},view.eye);stage.render(c.Get(),0,false,&view);actor.render(c.Get(),0,false,&view,&stage,&origin);particles::Pool pool;pool.synchronize(8,1,0,0);pool.dispatch(burst.events,s,2020);auto sprites=pool.sprites(s,2300);renderer.render(c.Get(),stage,view,sprites);save(out/"03-self-grenade.bmp",capture(d.Get(),c.Get(),stage));report<<"],\"self_grenade\":{\"hp\":"<<s.players[0]->hp<<",\"feet\":["<<origin[0]<<','<<origin[1]<<','<<origin[2]<<"],\"blastFlight\":true}}\n";
 // A fatal blast starts all articulated bodies with the same admitted velocity.
 for(unsigned gender=0;gender<2;++gender){player::Ragdoll rag;presentation::Death death;Player p;p.identity=shooter;p.life=1;Snapshot dead;dead.epoch=8;dead.eventWatermark=kick->id;death.scope(rag,8,1,shooter,1);auto live=*motion.sample(PlayerMotion::Idle,0);check(death.update(rag,human,gender,live,{0,500,0},0,p,dead,{&*kick,1},2020),"fatal blast starts corpse");for(const auto&b:rag.bodies())check(b.velocity==kick->normal,"HOST velocity distributed to every body");rag.step(*floor(),.01f);auto before=rag.bodies()[0].velocity;check(!death.update(rag,human,gender,live,{},0,p,dead,{&*kick,1},2030)&&rag.bodies()[0].velocity==before,"duplicate event never relaunches corpse");p.life=2;death.scope(rag,8,1,shooter,2);check(death.update(rag,human,gender,live,{0,500,0},0,p,dead,{&*kick,1},2040)&&rag.bodies()[0].velocity!=kick->normal,"old life impulse cannot affect next corpse");}
}
}
int main(int argc,char**argv){try{geometry();if(argc==4)original_capture(argv[1],argv[2],argv[3]);else check(argc==1,"usage: damage_presentation_test [data damage.gwfx output]");std::cout<<"PASS "<<checks<<" body surface, HOST damage, blast/death presentation checks\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
