#include "character_renderer.h"
#include "stage_lighting.h"
#include "stage_navigation.h"
#include "stage_normals.h"
#include "stage_floor_blend.h"
#include "source_coordinates.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <algorithm>
#include <cmath>
using namespace mgo2mt;using Microsoft::WRL::ComPtr;using V=std::array<float,3>;
V sub(V a,V b){for(int i=0;i<3;++i)a[i]-=b[i];return a;}V cross(V a,V b){return {a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]};}float dot(V a,V b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}V unit(V a){float l=std::sqrt(dot(a,a));for(auto&v:a)v/=l;return a;}V pos(const ModelVertex&v){return {v.x,v.y,v.z};}
void save(ID3D11Device*d,ID3D11DeviceContext*c,CharacterRenderer&r,const std::filesystem::path&p){ComPtr<ID3D11Resource>resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D>image;resource.As(&image);D3D11_TEXTURE2D_DESC desc{};image->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>copy;if(FAILED(d->CreateTexture2D(&desc,nullptr,&copy)))throw std::runtime_error("capture");c->CopyResource(copy.Get(),image.Get());D3D11_MAPPED_SUBRESOURCE map{};if(FAILED(c->Map(copy.Get(),0,D3D11_MAP_READ,0,&map)))throw std::runtime_error("capture map");std::vector<uint8_t> pixels(size_t(desc.Width)*desc.Height*4);for(unsigned y=0;y<desc.Height;++y)std::copy_n(static_cast<uint8_t*>(map.pData)+y*map.RowPitch,desc.Width*4,pixels.data()+size_t(y)*desc.Width*4);c->Unmap(copy.Get(),0);for(size_t i=0;i<pixels.size();i+=4)std::swap(pixels[i],pixels[i+2]);BITMAPFILEHEADER file{};BITMAPINFOHEADER info{};info.biSize=40;info.biWidth=desc.Width;info.biHeight=-LONG(desc.Height);info.biPlanes=1;info.biBitCount=32;info.biSizeImage=DWORD(pixels.size());file.bfType=0x4d42;file.bfOffBits=sizeof(file)+sizeof(info);file.bfSize=file.bfOffBits+info.biSizeImage;std::ofstream out(p,std::ios::binary);out.write(reinterpret_cast<char*>(&file),sizeof(file));out.write(reinterpret_cast<char*>(&info),sizeof(info));out.write(reinterpret_cast<char*>(pixels.data()),pixels.size());}
int main(int argc,char**argv){try{if(argc!=4&&argc!=5)return 2;std::filesystem::path data=argv[1],out=argv[2];std::filesystem::create_directories(out);std::ifstream in(data/"stage/n022a.gwm",std::ios::binary),lf(data/"stage/n022a.lighting.cfg"),cf(data/"stage/n022a.collision.cfg");std::vector<char>bytes{std::istreambuf_iterator<char>(in),{}};CharacterModel model(bytes);auto light=stage::Lighting::read(lf);auto world=stage::Collision::read(cf);stage::Navigation nav;if(!nav.place(world,{-42878.8359f,3000,29781.7969f}))return 3;auto feet=nav.feet();float angle=2.2f+1.57079632679f;WorldView camera;camera.eye={feet[0]-std::sin(angle)*3700,feet[1]+1900,feet[2]-std::cos(angle)*3700};camera.direction={feet[0]-camera.eye[0],feet[1]+750-camera.eye[1],feet[2]-camera.eye[2]};camera.aspect=16.f/9;
 std::ofstream report(out/"floor.txt");auto forward=unit(camera.direction),right=unit(cross({0,1,0},forward)),up=cross(forward,right);std::vector<unsigned> images;
 for(auto xy:std::array<std::array<float,2>,5>{{{1000,600},{400,600},{640,540},{640,625},{220,270}}}){auto ray=forward;for(unsigned j=0;j<3;++j)ray[j]+=source_screen_x*right[j]*((xy[0]/1280*2-1)*std::tan(.5f)*camera.aspect)+up[j]*((1-xy[1]/720*2)*std::tan(.5f));ray=unit(ray);float best=1e9;unsigned pi=0,vi=0;float bu=0,bv=0;
  for(unsigned k=0;k<model.parts.size();++k){const auto&p=model.parts[k];for(unsigned i=p.first;i<p.first+p.count;i+=3){auto a=pos(model.vertices[model.indices[i]]),e1=sub(pos(model.vertices[model.indices[i+1]]),a),e2=sub(pos(model.vertices[model.indices[i+2]]),a),h=cross(ray,e2);float det=dot(e1,h);if(std::abs(det)<1e-6)continue;auto s=sub(camera.eye,a);float u=dot(s,h)/det;if(u<0||u>1)continue;auto q=cross(s,e1);float v=dot(ray,q)/det;if(v<0||u+v>1)continue;float t=dot(e2,q)/det;if(t>0&&t<best){best=t;pi=k;vi=i;bu=u;bv=v;}}}
  const auto&p=model.parts[pi];report<<"pixel "<<xy[0]<<','<<xy[1]<<" hit="<<best<<" part="<<pi<<" shader="<<std::hex<<p.materialShader<<std::dec<<" texture="<<p.texture<<" mdn="<<p.original.mdnPath<<" sourceIndex="<<p.original.sourceIndex<<" bary="<<bu<<','<<bv<<'\n';images.push_back(p.texture);for(unsigned i=vi;i<vi+3;++i){const auto&v=model.vertices[model.indices[i]];auto sample=light.sample(pos(v),{v.nx,v.ny,v.nz});report<<" pos "<<v.x<<','<<v.y<<','<<v.z<<" normal "<<v.nx<<','<<v.ny<<','<<v.nz<<" uv "<<v.u<<','<<v.v<<" COLOR "<<v.ar<<','<<v.ag<<','<<v.ab<<','<<v.aa<<" light "<<sample.color[0]<<','<<sample.color[1]<<','<<sample.color[2]<<'\n';}
 }
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;if(FAILED(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c)))return 4;
 stage::load_original_normals(model,bytes,argv[3]);if(argc==5)stage::load_floor_blend(model,bytes,argv[4]);for(auto&v:model.vertices){auto l=light.sample({v.x,v.y,v.z},{v.nx,v.ny,v.nz});v.lr=l.color[0];v.lg=l.color[1];v.lb=l.color[2];v.lit=1;}CharacterRenderer corrected(d.Get(),model);corrected.resize_target(d.Get(),1280,720);corrected.render(c.Get(),0,false,&camera);save(d.Get(),c.Get(),corrected,out/"corrected-lighting.bmp");
 for(auto&v:model.vertices){v.lr=v.lg=v.lb=v.lit=1;v.ar=v.ag=v.ab=0;}for(auto&p:model.parts)p.original.requestedRules=0;CharacterRenderer flat(d.Get(),model);flat.resize_target(d.Get(),1280,720);flat.render(c.Get(),0,false,&camera);save(d.Get(),c.Get(),flat,out/"diffuse-only.bmp");
 for(auto index:images){CharacterModel quad;quad.bounds={-1,-1,2,1,1,2};for(auto xy:std::array<std::array<float,2>,4>{{{-1,-1},{1,-1},{1,1},{-1,1}}}){ModelVertex v{};v.x=xy[0];v.y=xy[1];v.z=2;v.nz=-1;v.u=(v.x+1)*.5f;v.v=(1-v.y)*.5f;v.lr=v.lg=v.lb=v.lit=1;quad.vertices.push_back(v);}quad.indices={0,1,2,0,2,3};quad.parts.push_back({0,6,0,0});quad.textures.push_back(model.textures[index]);CharacterRenderer r(d.Get(),quad);r.resize_target(d.Get(),512,512);WorldView view{{0,0,-10},{0,0,1},1};for(auto&v:quad.vertices){v.x*=6.55f;v.y*=6.55f;}r.update_vertices(c.Get(),quad.vertices);r.render(c.Get(),0,false,&view);save(d.Get(),c.Get(),r,out/("texture-"+std::to_string(index)+".bmp"));}
 report.close();std::cout<<"Floor diagnostic saved\n";return 0;}catch(const std::exception&e){std::cerr<<e.what();return 1;}}
