#include "gekko_test_profiles.h"
#include "gekko_jump.h"
#include "combat_service.h"
#include "stage_water.h"
#include <iostream>
#include <fstream>
#include <stdexcept>
#include <limits>
using namespace mgo2mt;using namespace mgo2mt::special_pc;
namespace {
void check(bool b,const char*s){if(!b)throw std::runtime_error(s);}
std::shared_ptr<stage::Collision> scene(bool wall=false,bool ceiling=false,float end=30000){std::vector<stage::Vec3>v{{-30000,0,-30000},{-30000,0,end},{30000,0,end},{30000,0,-30000}};std::vector<stage::CollisionTriangle>t{{{0,1,2},stage::attribute::native_solid},{{0,2,3},stage::attribute::native_solid}};if(wall){v.insert(v.end(),{{-10000,0,2500},{10000,0,2500},{10000,22000,2500},{-10000,22000,2500}});t.push_back({{4,5,6},stage::attribute::native_solid});t.push_back({{4,6,7},stage::attribute::native_solid});}if(ceiling){auto n=unsigned(v.size());v.insert(v.end(),{{-10000,4500,-10000},{10000,4500,-10000},{10000,4500,10000},{-10000,4500,10000}});t.push_back({{n,n+1,n+2},stage::attribute::native_solid});t.push_back({{n,n+2,n+3},stage::attribute::native_solid});}return std::make_shared<stage::Collision>(stage::Collision::make(v,t));}
void helper(){auto ground=scene();check(!begin_jump({0,2,0},{0,1,0})&&!begin_jump({0,2,0},{0,0,4225})&&!begin_jump({0,2,0},{0,0,std::numeric_limits<float>::infinity()}),"invalid trajectory rejected");
 for(float speed:{0.f,native_gekko.walkSpeed,native_gekko.runSpeed}){auto jump=begin_jump({0,2,0},{0,0,speed}).value();check(advance_jump(jump,600,*ground)&&jump.feet[2]==0,"windup does not slide");check(advance_jump(jump,native_gekko.jumpMs,*ground),"finish jump");const float distance=speed*2.858f;check(std::abs(jump.feet[2]-distance)<.3f&&jump.feet[1]>=1.9f&&jump.feet[1]<3,"bounded authored-airphase travel and grounded finish");auto delayed=begin_jump({0,2,0},{0,0,speed}).value();check(advance_jump(delayed,native_gekko.jumpMs,*ground)&&std::abs(jump.feet[2]-delayed.feet[2])<.3f,"one delayed poll still sweeps entire path");auto before=delayed;check(!advance_jump(delayed,1,*ground)&&delayed.feet==before.feet&&delayed.elapsedMs==before.elapsedMs,"backward clock leaves state intact");}
 auto obstacle=scene(true);auto stopped=begin_jump({0,2,0},{0,0,native_gekko.runSpeed}).value();advance_jump(stopped,native_gekko.jumpMs,*obstacle);check(stopped.horizontalStopped&&stopped.feet[2]<1702&&stopped.feet[2]>1600&&stopped.feet[1]<3,"continuous sweep stops at thin wall then lands");
 auto roof=scene(false,true);auto under=begin_jump({0,2,0},{0,0,1000}).value();advance_jump(under,800,*roof);check(under.feet[1]<302,"ceiling clips jump height");advance_jump(under,native_gekko.jumpMs,*roof);check(under.feet[1]<3,"ceiling cannot leave floating end pose");
 std::array bodies{JumpBody{{0,2,2500},{800,20000,2}}};auto other=begin_jump({0,2,0},{0,0,native_gekko.runSpeed}).value();advance_jump(other,native_gekko.jumpMs,*ground,bodies);check(other.feet[2]<2000&&other.horizontalStopped,"continuous peer capsule prevents air tunnelling");
 std::array prone{JumpBody{{0,2,2500},{260,560,2}}};auto over=begin_jump({0,2,0},{0,0,native_gekko.runSpeed}).value();advance_jump(over,native_gekko.jumpMs,*ground,prone);check(over.feet[2]>4000&&over.feet[1]<3,"clear low participant can be jumped over");
 auto cancelled=begin_jump({0,2,0},{0,0,native_gekko.walkSpeed}).value();advance_jump(cancelled,1000,*ground);auto xz=cancelled.feet;check(cancelled.feet[2]>700&&cancelled.feet[1]>1000,"moving airborne cancel fixture");cancel_jump(cancelled,*ground);check(cancelled.horizontalStopped&&cancelled.feet[0]==xz[0]&&cancelled.feet[2]==xz[2]&&cancelled.feet[1]==xz[1],"cancel preserves current airborne position for ordinary falling");
 auto ledge=scene(false,false,2000);auto edge=begin_jump({0,2,0},{0,0,native_gekko.runSpeed}).value();advance_jump(edge,native_gekko.jumpMs,*ledge);check(edge.feet[2]>9000&&edge.feet[1]<3,"unsupported destination remains airborne for ordinary gravity after jump");
 std::array badPeer{JumpBody{{0,0,0},{-1,1700,2}}};auto unchanged=cancelled;check(!advance_jump(cancelled,native_gekko.jumpMs,*ground,badPeer)&&cancelled.feet==unchanged.feet,"invalid peer does not partially update");
}
combat::Weapon weapon(){combat::Weapon w;w.id=23;w.damage=100;w.intervalMs=100;w.reloadMs=500;w.magazine=30;w.reserve=60;w.range=20000;return w;}
struct Match {combat::Service service{8};combat::Identity id{0,1,100};uint32_t seq=0;Match(){service.configure(scene(),gekko_test_profiles(weapon()));check(service.authority().join(id,1,{{0,2,0}},1000,1000,std::array<uint16_t,1>{23},0),"grant");service.authority().active(true);check(service.authority().assign_special(id,Kind::gekko,true,0)==combat::Reject::none&&service.admit(id)&&service.receive(id,combat::wire::encode(combat::wire::Accept{8}),0),"form and acceptance");service.deliveries();}
 void input(uint64_t now,float z,bool jump=false){auto p=service.authority().snapshot().players[0]->pose;p.feet[2]=z;combat::wire::Input in{8,++seq,p,128};if(jump)in.specialPc={Action::jump,1};check(service.receive(id,combat::wire::encode(in),now),"received input");service.poll(now);service.deliveries();}
};
void authority(){
 Match moving;moving.input(100,200);moving.input(150,200,true);check(moving.service.authority().snapshot().players[0]->specialPc.action==Action::jump,"halting request pose starts jump");moving.service.poll(1150);auto body=*moving.service.authority().snapshot().players[0];check(std::abs(body.pose.feet[2]-1000)<.4f,"request pose retains preceding approved 2000 velocity");auto malicious=body.pose;malicious.feet[0]+=9000;check(moving.service.authority().pose(moving.id,8,99,malicious,1200)==combat::Reject::unavailable,"client air teleport rejected");moving.input(1250,29000);check(moving.service.authority().snapshot().players[0]->pose.feet[2]<2000,"received air packet cannot change trajectory");moving.service.poll(150+native_gekko.jumpMs);check(std::abs(moving.service.authority().snapshot().players[0]->pose.feet[2]-5916)<.4f,"no-packet HOST action completes at frozen velocity");
 Match stopped;stopped.input(100,200);stopped.input(150,200);stopped.input(200,200,true);stopped.service.poll(200+native_gekko.jumpMs);check(stopped.service.authority().snapshot().players[0]->pose.feet[2]==200,"ordinary stop packet clears velocity before later jump");
 Match old;old.input(100,200);old.input(400,200,true);old.service.poll(400+native_gekko.jumpMs);check(old.service.authority().snapshot().players[0]->pose.feet[2]==200,"stale movement is not recycled after delay");
 Match delayed;delayed.input(500,500);delayed.input(550,500,true);delayed.service.poll(550+native_gekko.jumpMs);check(std::abs(delayed.service.authority().snapshot().players[0]->pose.feet[2]-3358)<.4f,"velocity uses actual received 500ms interval rather than 250ms admission clamp");
 Match failed;failed.input(100,200);failed.input(150,10000);failed.input(200,200,true);failed.service.poll(200+native_gekko.jumpMs);check(failed.service.authority().snapshot().players[0]->pose.feet[2]<6000,"rejected teleport never becomes jump speed");
 Match reset;reset.input(100,200);check(reset.service.authority().assign_special(reset.id,Kind::human,true,110)==combat::Reject::none&&reset.service.authority().assign_special(reset.id,Kind::gekko,true,120)==combat::Reject::none,"form reset");reset.input(150,200,true);reset.service.poll(150+native_gekko.jumpMs);check(reset.service.authority().snapshot().players[0]->pose.feet[2]==200,"kind reset clears locomotion evidence");
 Match suspended;suspended.input(100,200);auto p=suspended.service.authority().snapshot().players[0]->pose;combat::wire::Input pause{8,++suspended.seq,p,23};pause.suspended=true;check(suspended.service.receive(suspended.id,combat::wire::encode(pause),120),"suspend input");suspended.service.poll(120);suspended.service.deliveries();suspended.input(150,200,true);suspended.service.poll(150+native_gekko.jumpMs);check(suspended.service.authority().snapshot().players[0]->pose.feet[2]==200,"menu/focus suspension clears movement evidence");
}
void original_scene(const char* path){std::ifstream in(path,std::ios::binary);check(bool(in),"original collision opens");auto raw=std::make_shared<stage::Collision>(stage::Collision::read(in));auto world=stage::movement_collision(raw);unsigned accepted=0;for(const auto& t:world->triangles){const auto&a=world->vertices[t.vertices[0]],&b=world->vertices[t.vertices[1]],&c=world->vertices[t.vertices[2]];stage::Vec3 origin{(a[0]+b[0]+c[0])/3,(a[1]+b[1]+c[1])/3+50,(a[2]+b[2]+c[2])/3};auto hit=world->ray(origin,{0,-1,0},100);if(!hit||std::abs(hit->normal[1])<.8f)continue;auto feet=hit->position;feet[1]+=2;if(!world->clear(feet,native_gekko.capsule))continue;auto jump=begin_jump(feet,{0,0,native_gekko.walkSpeed}).value();for(uint32_t now=0;now<=native_gekko.jumpMs;now+=50){check(advance_jump(jump,now,*world)&&world->clear(jump.feet,native_gekko.capsule),"original-stage every jump step remains clear");check(std::hypot(jump.feet[0]-feet[0],jump.feet[2]-feet[2])<=native_gekko.walkSpeed*2.858f+.5f,"original-stage horizontal speed bound");}if(++accepted>=4)break;}check(accepted==4,"four real capsule-clear starting locations");std::cout<<"original collision "<<path<<" starts="<<accepted<<" PASS\n";}
}
int main(int argc,char**argv){try{helper();if(argc>1&&std::string(argv[1])=="--helper-only"){std::cout<<"Gekko jump helper PASS\n";return 0;}authority();for(int i=1;i<argc;++i)original_scene(argv[i]);std::cout<<"Gekko moving jump: ground/airphase/fixed velocity/continuous GEOM+peer/cancel/latency/teleport PASS\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
