#include "graphics_settings.h"
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace mgo2mt;
void require(bool b){if(!b)throw std::runtime_error("Graphics settings contract failed");}
void capture_graphics(const std::filesystem::path& output){
 std::filesystem::create_directories(output);HDC dc=CreateCompatibleDC(nullptr);require(dc!=nullptr);
 BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=1280;info.bmiHeader.biHeight=-720;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biSizeImage=1280*720*4;
 void* pixels=nullptr;auto bitmap=CreateDIBSection(dc,&info,DIB_RGB_COLORS,&pixels,nullptr,0);require(bitmap!=nullptr);auto previous=SelectObject(dc,bitmap);
 std::vector<HFONT> fonts;for(int size:{30,24,20,17}){fonts.push_back(CreateFontW(-size,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,ANTIALIASED_QUALITY,DEFAULT_PITCH,L"Yu Gothic UI"));require(fonts.back()!=nullptr);}
 for(unsigned variant=0;variant<5;++variant){GraphicsSettings screen(output/L"never-saved.cfg");screen.draft.footIk=variant!=1;if(variant==2){screen.message(nullptr,WM_KEYDOWN,VK_NEXT,0);screen.draft.shadowEnabled=1;}if(variant>=3){screen.message(nullptr,WM_KEYDOWN,VK_PRIOR,0);if(variant==3){screen.draft.hdr=screen.draft.aa=screen.draft.ao=screen.draft.bloom=screen.draft.reflections=screen.draft.lod=screen.draft.softParticles=1;screen.draft.exposureMilli=1750;}}
  RECT rect{0,0,1280,720};auto brush=CreateSolidBrush(RGB(25,33,29));FillRect(dc,&rect,brush);DeleteObject(brush);screen.draw(dc,fonts);GdiFlush();
  BITMAPFILEHEADER header{};header.bfType=0x4d42;header.bfOffBits=sizeof(header)+sizeof(BITMAPINFOHEADER);header.bfSize=header.bfOffBits+info.bmiHeader.biSizeImage;
  const char* names[]={"graphics-ik-on.bmp","graphics-ik-off.bmp","graphics-shadow-on.bmp","graphics-effects-on.bmp","graphics-effects-off.bmp"};std::ofstream f(output/names[variant],std::ios::binary);f.write(reinterpret_cast<const char*>(&header),sizeof(header));f.write(reinterpret_cast<const char*>(&info.bmiHeader),sizeof(BITMAPINFOHEADER));f.write(static_cast<const char*>(pixels),info.bmiHeader.biSizeImage);require(bool(f));
 }
 SelectObject(dc,GetStockObject(SYSTEM_FONT));for(auto font:fonts)DeleteObject(font);SelectObject(dc,previous);DeleteObject(bitmap);DeleteDC(dc);
}
int main(int argc,char**argv){auto dir=std::filesystem::current_path()/(L"graphics-test-"+std::to_wstring(GetCurrentProcessId()));require(std::filesystem::create_directory(dir));auto path=dir/L"graphics.cfg";
 try{
  GraphicsConfig cfg;require(valid_graphics(cfg));cfg={1,1920,1080,60000,1001,4096,0};save_graphics(path,cfg);GraphicsConfig loaded;require(load_graphics(path,loaded)&&loaded==cfg);
  for(unsigned shadow:{512u,1024u,2048u,4096u,8192u}){loaded.shadow=shadow;require(valid_graphics(loaded));}loaded.refresh_den=0;require(!valid_graphics(loaded));loaded=cfg;loaded.shadow=3000;require(!valid_graphics(loaded));
  {std::ofstream f(path);f<<"MGO2MT.GRAPHICS 1 1 1920 1080 60000 0 4096 1";}bool bad=false;try{load_graphics(path,loaded);}catch(...){bad=true;}require(bad);std::filesystem::remove(path);
  {std::ofstream f(path);f<<"MGO2MT.GRAPHICS 1 0 3840 2160 0 1 2048 1";}require(load_graphics(path,loaded)&&loaded.renderScale==100&&!loaded.anisotropy&&!loaded.mipmaps&&!loaded.linearColor);
  loaded.renderScale=150;loaded.anisotropy=16;loaded.mipmaps=loaded.linearColor=1;save_graphics(path,loaded);GraphicsConfig enhanced;require(load_graphics(path,enhanced)&&loaded==enhanced);enhanced.anisotropy=3;require(!valid_graphics(enhanced));enhanced=loaded;enhanced.renderScale=201;require(!valid_graphics(enhanced));std::filesystem::remove(path);
  GraphicsSettings s(path);unsigned calls=0;GraphicsConfig applied;bool reject=false;s.apply=[&](const GraphicsConfig& c){++calls;if(reject&&c.width==1600)return false;applied=c;return true;};
  s.draft.width=1600;s.draft.height=900;s.request();s.tick(100,true);require(s.pending()&&applied.width==1600&&!std::filesystem::exists(path));s.tick(15099,true);require(s.pending());s.tick(15100,true);require(!s.pending()&&applied.width==1280&&!std::filesystem::exists(path));
  s.draft.width=1600;s.request();s.tick(20000,true);s.tick(20001,false);require(!s.pending()&&applied.width==1280);
  s.draft.width=1600;s.request();s.tick(21000,true);s.cancel();s.tick(21001,true);require(!s.pending()&&applied.width==1280);
  reject=true;s.draft.width=1600;s.request();s.tick(22000,true);require(!s.pending()&&applied.width==1280);reject=false;
  s.draft.width=1920;s.draft.height=1080;s.draft.shadow=8192;s.request();s.tick(23000,true);require(s.confirm()&&load_graphics(path,loaded)&&loaded.width==1920&&loaded.shadow==8192);require(!s.pending());
  GraphicsSettings navigation(dir/L"not-saved.cfg");for(unsigned i=0;i<5;++i)navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(navigation.draft.anisotropy==2);navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(navigation.draft.mipmaps==1);navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(navigation.draft.linearColor==1);navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(!navigation.draft.footIk);navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.apply=[](const auto&){return true;};navigation.message(nullptr,WM_KEYDOWN,VK_RETURN,0);navigation.tick(24000,true);require(navigation.pending()&&!navigation.active.footIk);navigation.cancel();navigation.tick(24001,true);require(!navigation.pending()&&!navigation.active.linearColor&&navigation.active.footIk);
  navigation.message(nullptr,WM_KEYDOWN,VK_NEXT,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(navigation.draft.shadowEnabled==1);navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(navigation.draft.shadow==4096);navigation.message(nullptr,WM_KEYDOWN,VK_DOWN,0);navigation.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(navigation.draft.shadowCascades==5);
  loaded=navigation.draft;loaded.shadowPcf=2;loaded.shadowBias=100;loaded.shadowNormal=80;loaded.shadowSlope=5;loaded.shadowDebug=1;save_graphics(dir/L"shadow.cfg",loaded);require(load_graphics(dir/L"shadow.cfg",enhanced)&&loaded==enhanced);require(enhanced.shadows().enabled&&enhanced.shadows().cascades==5);std::filesystem::remove(dir/L"shadow.cfg");enhanced.shadowCascades=7;require(!valid_graphics(enhanced));enhanced=loaded;enhanced.shadowBias=1001;require(!valid_graphics(enhanced));
  {std::ofstream f(dir/L"old.cfg");f<<"MGO2MT.GRAPHICS 2 0 1280 720 0 1 2048 1 100 0 0 0";}require(load_graphics(dir/L"old.cfg",enhanced)&&!enhanced.shadowEnabled&&enhanced.shadowCascades==4);std::filesystem::remove(dir/L"old.cfg");
  loaded.footIk=0;save_graphics(dir/L"ik.cfg",loaded);require(load_graphics(dir/L"ik.cfg",enhanced)&&!enhanced.footIk);enhanced.footIk=2;require(!valid_graphics(enhanced));std::filesystem::remove(dir/L"ik.cfg");
  {std::ofstream f(dir/L"old4.cfg");f<<"MGO2MT.GRAPHICS 4 0 1280 720 0 1 2048 1 100 0 0 0 0 4 1 30 20 2 0 1";}require(load_graphics(dir/L"old4.cfg",enhanced)&&!enhanced.hdr&&!enhanced.aa&&!enhanced.ao&&!enhanced.bloom&&!enhanced.reflections&&!enhanced.lod&&!enhanced.softParticles&&enhanced.gpuTiming==1&&enhanced.exposureMilli==1000);std::filesystem::remove(dir/L"old4.cfg");
  GraphicsSettings effects(dir/L"effects.cfg");effects.message(nullptr,WM_KEYDOWN,VK_PRIOR,0);for(unsigned i=0;i<8;++i)effects.message(nullptr,WM_KEYDOWN,VK_DOWN,0);effects.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(effects.draft.hdr&&effects.draft.aa&&effects.draft.ao&&effects.draft.bloom&&effects.draft.reflections&&effects.draft.lod&&effects.draft.softParticles&&effects.draft.footIk&&effects.draft.gpuTiming);effects.message(nullptr,WM_KEYDOWN,VK_UP,0);effects.message(nullptr,WM_KEYDOWN,VK_RIGHT,0);require(effects.draft.exposureMilli==1250);
  effects.apply=[](const auto&){return true;};effects.request();effects.tick(50000,true);require(effects.pending()&&effects.active.ao);effects.tick(65000,true);require(!effects.pending()&&!effects.active.ao&&effects.active.exposureMilli==1000);
  effects.draft.hdr=effects.draft.aa=effects.draft.ao=effects.draft.bloom=effects.draft.reflections=effects.draft.lod=effects.draft.softParticles=1;effects.draft.exposureMilli=3750;effects.draft.gpuTiming=0;effects.request();effects.tick(70000,true);require(effects.confirm()&&load_graphics(dir/L"effects.cfg",enhanced)&&enhanced==effects.active);std::filesystem::remove(dir/L"effects.cfg");
  for(auto field:{&GraphicsConfig::hdr,&GraphicsConfig::aa,&GraphicsConfig::ao,&GraphicsConfig::bloom,&GraphicsConfig::reflections,&GraphicsConfig::lod,&GraphicsConfig::softParticles,&GraphicsConfig::gpuTiming}){auto invalid=enhanced;invalid.*field=2;require(!valid_graphics(invalid));}for(unsigned value:{0u,249u,4001u}){auto invalid=enhanced;invalid.exposureMilli=value;require(!valid_graphics(invalid));}
  {std::ofstream f(dir/L"broken5.cfg");f<<"MGO2MT.GRAPHICS 5 0 1280 720 0 1 2048 1 100 0 0 0 0 4 1 30 20 2 0 1 1";}auto unchanged=enhanced;bool failed=false;try{load_graphics(dir/L"broken5.cfg",enhanced);}catch(...){failed=true;}require(failed&&enhanced==unchanged);std::filesystem::remove(dir/L"broken5.cfg");
  GraphicsSettings restored(path);require(restored.draft==s.active);require(calls>=9);std::filesystem::remove(path);std::filesystem::remove(dir);
 }catch(...){std::error_code ec;std::filesystem::remove(path,ec);std::filesystem::remove(dir,ec);throw;}
 if(argc==2)capture_graphics(argv[1]);
 std::cout<<"Graphics rational refresh persistence, bounds, 15-second timeout, focus-loss/Esc rollback, apply-failure recovery and confirmed-only saving passed.\n";
}
