#include "player_menu.h"
#include "menu_audio.h"
#include "hold_inventory_bridge.h"
#include "hold_selection_layout.h"
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace mgo2mt;
namespace {
void check(bool value,const char* reason){if(!value)throw std::runtime_error(reason);}
void bitmap(const void* pixels,const std::filesystem::path& path){BITMAPFILEHEADER h{};BITMAPINFOHEADER i{};h.bfType=0x4d42;h.bfOffBits=sizeof(h)+sizeof(i);h.bfSize=h.bfOffBits+1280*720*4;i.biSize=sizeof(i);i.biWidth=1280;i.biHeight=-720;i.biPlanes=1;i.biBitCount=32;std::ofstream f(path,std::ios::binary);f.write(reinterpret_cast<char*>(&h),sizeof(h));f.write(reinterpret_cast<char*>(&i),sizeof(i));f.write(static_cast<const char*>(pixels),1280*720*4);check(bool(f),"capture");}
hold_selection::Snapshot fixture(){hold_selection::Snapshot s;s.scope={9,7,2,1,33,101,4};s.eligible=true;s.weapons={{0,25,7,1,24,120,0,true},{1,3,4,1,7,21,0,true},{2,52,1,3,0,0,3,false}};s.selectedWeapon=uint8_t(0);return s;}
}
int main(int argc,char**argv){try{
 const auto temp=std::filesystem::temp_directory_path()/("MGO2MT-hold-menu-test-"+std::to_string(GetCurrentProcessId())+"-"+std::to_string(GetTickCount64()));check(std::filesystem::create_directory(temp),"isolated temp");
 auto input=std::make_shared<ControllerInput>(temp/"input.cfg");input->config.device=1;auto graphics=std::make_shared<GraphicsSettings>(temp/"graphics.cfg");PlayerMenu menu(temp/"input.cfg",input,graphics);if(argc>1)menu.hold_assets(argv[1]);
 auto capture=[&](const char* name){Sleep(165);const auto* pixels=menu.draw();check(pixels,"hold render");size_t lit=0;for(size_t n=0;n<1280*720;++n)lit+=(static_cast<const uint32_t*>(pixels)[n]&0xffffff)!=0;check(lit>10000,"visible GDI panel");if(menu.hold_visible()){const auto* p=static_cast<const uint32_t*>(pixels);check((p[100*1280+20]>>24)==112,"hold selection dims the scene beyond the old central panel");const bool weapon=menu.hold_selection_state().kind()==hold_selection::Kind::weapons;check((p[630*1280+(weapon?1240:30)]&0xffffff)==0xffbb53,"outer yellow strip is on the selected inventory side");check((p[630*1280+(weapon?30:1240)]&0xffffff)==0,"opposite inventory side stays unobscured");}if(argc>2){std::filesystem::create_directories(argv[2]);bitmap(pixels,std::filesystem::path(argv[2])/name);}};
 for(bool weapon:{false,true})for(size_t selected=0;selected<4;++selected){const auto at=hold_selection::card_position(weapon,4,selected,selected);check(at.x==(weapon?1000:70)&&at.y==598,"selected held item keeps the video lower corner across selection changes");bool above=false,inward=false;for(size_t i=0;i<4;++i){const auto p=hold_selection::card_position(weapon,4,selected,i);check(p.x>=0&&p.x+210<=1280&&p.y>=0&&p.y+78<=720,"all authoritative held slots remain within the UI canvas");above|=p.x==at.x&&p.y<at.y;inward|=p.y==at.y&&(weapon?p.x<at.x:p.x>at.x);}check(above&&inward,"four held choices occupy both L arms");}
 const auto s=fixture();hold_selection::Input rt;rt.weapons=true;hold_selection::Input lt;lt.equipment=true;
 auto open=[&]{menu.hold_selection_step(s,{});check(!menu.hold_selection_step(s,rt)&&menu.hold_visible()&&menu.visible()&&menu.hold_blocks_gameplay(),"RT opens independent hold panel");};
 open();check(menu.cues().empty(),"open has no false confirm sound");check(menu.hold_consumes_action(5)&&!menu.hold_consumes_action(4)&&!menu.hold_consumes_action(12),"A bypasses cancel mapping while other menu actions remain routed");capture("hold_weapon_ak.bmp");
 rt.right=true;check(!menu.hold_selection_step(s,rt)&&menu.hold_selection_state().choice()->item==3,"preview selects owned Operator");check(menu.cues()==std::vector<unsigned>{menu_audio::Cursor},"one cursor sound");capture("hold_weapon_operator.bmp");menu.hold_selection_step(s,rt);check(menu.cues().empty(),"held direction has no sound repeat");
 check(menu.message(nullptr,WM_KEYDOWN,VK_RETURN,0)&&menu.message(nullptr,WM_KEYDOWN,VK_RETURN,1LL<<30),"Enter consumed without commit");check(menu.hold_visible()&&menu.cues().empty(),"Enter cannot prematurely confirm");
 auto request=menu.hold_selection_step(s,{});check(request&&request->scope==s.scope&&request->item==s.weapons[1]&&!menu.visible()&&menu.hold_blocks_gameplay(),"release returns request without HOST mutation");check(menu.cues().empty(),"release waits for HOST acceptance before success sound");check(!menu.hold_selection_step(s,{})&&menu.cues().empty()&&!menu.hold_blocks_gameplay(),"release drains once");check(s==fixture(),"supplied canonical holdings unchanged");
 rt.right=false;open();rt.left=true;menu.hold_selection_step(s,rt);capture("hold_weapon_grenade.bmp");check(menu.hold_selection_state().choice()->item==52,"left wrap selects owned grenade");menu.cues();
 check(menu.message(nullptr,WM_KEYDOWN,VK_ESCAPE,0)&&!menu.hold_visible(),"Escape cancels");check(menu.cues()==std::vector<unsigned>{menu_audio::Cancel},"cancel sound");check(!menu.hold_selection_step(s,{}),"cancel release cannot submit");
 menu.hold_selection_step(s,lt);check(menu.hold_visible()&&menu.hold_selection_state().choices().empty(),"empty equipment shown");capture("hold_equipment_empty.bmp");check(!menu.hold_selection_step(s,{})&&!menu.hold_visible(),"empty release cannot submit");check(menu.cues()==std::vector<unsigned>{menu_audio::Cancel},"empty release has no confirm");
 rt.left=false;open();menu.cues();menu.message(nullptr,WM_KILLFOCUS,0,0);check(!menu.hold_visible()&&!menu.hold_selection_step(s,{}),"focus loss cancels release");
 open();auto dead=s;dead.eligible=false;check(!menu.hold_selection_step(dead,{})&&!menu.hold_visible(),"death cancels");menu.cues();
 open();auto respawn=s;++respawn.scope[6];check(!menu.hold_selection_step(respawn,{})&&!menu.hold_visible(),"life change cancels");menu.cues();
 menu.hold_selection_step(s,{});open();auto changed=s;++changed.weapons[0].revision;check(!menu.hold_selection_step(changed,{})&&!menu.hold_visible(),"HOST revision change cancels");menu.cues();
 menu.hold_selection_step(s,{});open();menu.open(player::Menu::equipment);check(menu.inventory_menu()&&!menu.hold_visible(),"existing placement equipment menu retained");check(!menu.hold_selection_step(s,rt)&&!menu.hold_visible(),"other menu blocks trigger panel");capture("hold_existing_placement.bmp");menu.close();check(!menu.hold_selection_step(s,{}),"menu switch cannot release-equip");
 auto equipped=s;equipped.equipment={{3,22,1,1,0,0,70,false}};equipped.selectedEquipment=uint8_t(3);menu.hold_selection_step(equipped,{});menu.hold_selection_step(equipped,lt);capture("hold_equipment_owned_fixture.bmp");request=menu.hold_selection_step(equipped,{});check(request&&request->kind==hold_selection::Kind::equipment&&request->item.item==22,"separate equipment namespace");
 menu.hold_selection_step(s,{});input->config.device=0;rt.left=rt.right=false;menu.hold_selection_step(s,rt);capture("hold_weapon_keyboard.bmp");menu.cancel_hold_selection();menu.hold_selection_step(s,{});input->config.device=1;assign_input(input->config,14,12);menu.hold_selection_step(s,rt);capture("hold_weapon_custom_ls.bmp");menu.cancel_hold_selection();
 menu.hold_selection_step(s,{});rt.left=rt.right=false;menu.hold_selection_step(s,rt);capture("hold_drop_hint.bmp");menu.cues();rt.drop=true;request=menu.hold_selection_step(s,rt);check(request&&request->action==hold_selection::Action::drop&&!menu.hold_visible()&&menu.hold_blocks_gameplay(),"mapped A returns drop");check(menu.cues().empty(),"drop request has no premature success sound");menu.hold_selection_step(s,rt);check(menu.cues().empty(),"held A is silent");rt.weapons=false;check(!menu.hold_selection_step(s,rt)&&menu.hold_blocks_gameplay(),"A does not leak into roll");menu.hold_selection_step(s,{});
 // Accepted/rejected results are the sole source of operation feedback.
 for(auto outcome:{items::ResultCode::ok,items::ResultCode::policy}){
  auto session=std::make_shared<items::ClientSession>();items::ClientContext context{{7,2},{1,33,101,4},{0,2,0,0},true};items::wire::Header h{context.scope,991,context.actor,0};session->pump(context,0,991,true,{});items::wire::Held owned;owned.header=h;owned.selectedSlot=0;owned.slots[0].contents={25,1,24,120,0,items::Resource::ammunition,items::Domain::weapon};owned.slots[0].revision=7;
  std::vector<std::vector<uint8_t>> incoming{*items::wire::encode(items::wire::Offer{h,63,{64,64}}),*items::wire::encode(owned)};session->pump(context,1,0,true,incoming);menu.inventory_session(session);menu.cues();
  auto snapshot=hold_selection::inventory_snapshot(session->state(),true);hold_selection::Input input;menu.hold_selection_step(snapshot,input);input.weapons=true;menu.hold_selection_step(snapshot,input);input.drop=true;auto action=menu.hold_selection_step(snapshot,input);check(action&&action->action==hold_selection::Action::drop,"A chooses scoped drop");auto stale=*action;++stale.item.revision;check(!hold_selection::submit_inventory_selection(*session,stale),"drop revision checked atomically");stale=*action;++stale.scope[6];check(!hold_selection::submit_inventory_selection(*session,stale),"drop life checked atomically");check(hold_selection::submit_inventory_selection(*session,*action),"drop request queues");check(menu.cues().empty(),"enqueue is silent");auto outgoing=session->pump(context,2,0,true,{});check(outgoing.size()==1,"one pending drop");auto command=std::get<items::wire::Command>(*items::wire::decode(outgoing[0]));check(command.action==items::wire::Action::drop&&command.heldRevision==7,"exact drop request wire");menu.inventory_session(session);check(menu.cues().empty(),"pending is silent");
  items::wire::Reply reply;reply.header=command.header;reply.action=command.action;reply.heldSlot=command.heldSlot;reply.result=outcome;reply.worldRevision=1;incoming={*items::wire::encode(reply)};session->pump(context,3,0,true,incoming);menu.inventory_session(session);check(menu.cues()==std::vector<unsigned>{outcome==items::ResultCode::ok?menu_audio::Confirm:menu_audio::Cancel},"HOST outcome has exactly one appropriate cue");menu.inventory_session(session);check(menu.cues().empty(),"same ACK state cannot replay cue");session->pump(context,4,0,true,incoming);menu.inventory_session(session);check(menu.cues().empty(),"duplicate ACK cannot replay cue");menu.hold_selection_step(snapshot,{});
 }
 menu.close();std::filesystem::remove_all(temp);std::cout<<"hold_selection_menu_test PASS: independent hold UI, release/cursor/cancel sounds, frozen holdings, namespace, focus/life and old placement menu; offline GDI\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
