#include "hold_selection.h"
#include <iostream>
#include <stdexcept>
using namespace mgo2win::hold_selection;
namespace {
void check(bool v,const char* why){if(!v)throw std::runtime_error(why);}
Snapshot fixture(){Snapshot s;s.scope={9,7,2,1,33,101,4};s.eligible=true;s.weapons={{0,25,7,1,24,120,0,true},{1,3,4,1,7,21,0,true},{2,52,1,3,0,0,3,false}};s.selectedWeapon=uint8_t(0);return s;}
Input held(bool left=false,bool right=false){Input i;i.weapons=true;i.left=left;i.right=right;return i;}
void open(State& state,const Snapshot& s){state.step(s,{});check(state.step(s,held()).opened&&state.visible(),"open after neutral");}
}
int main(){try{
 const auto s=fixture();check(State::valid(s),"valid current HOST holdings");State a;check(!a.blocks_gameplay(),"neutral unavailable cannot freeze gameplay");check(!a.step(s,held()).opened&&!a.visible()&&a.blocks_gameplay(),"initial held requires neutral");a.step(s,{});check(!a.blocks_gameplay(),"neutral unblocks initial held");check(a.step(s,held()).opened&&a.choice()->item==25,"opens current selected slot");
 check(a.step(s,held(false,true)).cursor&&a.choice()->item==3,"right edge selects");check(!a.step(s,held(false,true)).cursor&&a.choice()->item==3,"held right does not repeat");a.step(s,held());check(a.step(s,held(true)).cursor&&a.choice()->item==25,"left edge selects");a.step(s,held());check(a.step(s,held(true)).cursor&&a.choice()->item==52,"left wraps");
 auto e=a.step(s,{});check(e.confirm&&e.confirm->scope==s.scope&&e.confirm->kind==Kind::weapons&&e.confirm->item==s.weapons[2]&&!a.visible()&&a.blocks_gameplay(),"release returns exact frozen row once and consumes frame");check(!a.step(s,{}).confirm&&!a.blocks_gameplay(),"next neutral releases gameplay block");check(s==fixture(),"preview never mutates HOST holdings");
 State empty;empty.step(s,{});Input lt;lt.equipment=true;check(empty.step(s,lt).opened&&empty.visible()&&empty.choices().empty(),"empty equipment visible without fabricated ownership");e=empty.step(s,{});check(!e.confirm&&e.cancelled&&!empty.visible(),"empty release never equips");
 State both;open(both,s);auto bothInput=held();bothInput.equipment=true;e=both.step(s,bothInput);check(e.cancelled&&!e.confirm&&!both.visible(),"both triggers cancel");check(!both.step(s,lt).opened&&!both.step(s,{}).confirm,"cross switch/release does not confirm");check(both.step(s,lt).opened,"neutral allows new LT");
 State cross;open(cross,s);check(cross.step(s,lt).cancelled&&!cross.visible(),"direct opposite trigger cancels rather than commit");
 for(size_t k=0;k<s.scope.size();++k){State x;open(x,s);auto changed=s;++changed.scope[k];e=x.step(changed,{});check(e.cancelled&&!e.confirm&&!x.visible(),"every identity/scope field invalidates release");}
 for(int change=0;change<6;++change){State x;open(x,s);auto changed=s;if(change==0)++changed.weapons[0].revision;if(change==1)--changed.weapons[0].magazine;if(change==2)changed.weapons.erase(changed.weapons.begin()+1);if(change==3)changed.selectedWeapon=uint8_t(1);if(change==4)changed.eligible=false;if(change==5)changed.weapons[0].item=3;e=x.step(changed,{});check(e.cancelled&&!e.confirm&&!x.visible(),"holdings change cancels stale release");}
 for(int reason=0;reason<3;++reason){State x;open(x,s);Input i;if(reason==0)i.active=false;if(reason==1)i.otherMenu=true;if(reason==2)x.cancel();e=x.step(s,i);check(!e.confirm&&!x.visible(),"focus/death/menu/manual cancel never commits");}
 {State x;open(x,s);x.cancel();check(!x.step(s,held()).opened,"held trigger cannot reopen after cancel");x.step(s,{});check(x.step(s,held()).opened,"release rearms after cancel");}
 {State x;open(x,s);Input released;released.right=true;check(x.step(s,released).confirm.has_value()&&x.blocks_gameplay(),"release with direction still commits once");check(!x.step(s,released).confirm&&x.blocks_gameplay(),"lingering direction cannot leak after release");x.step(s,{});check(!x.blocks_gameplay(),"complete neutral clears post-release block");}
 {State x;open(x,s);auto opposite=held(true,true);check(!x.step(s,opposite).cursor&&x.selected()==0,"opposite horizontal input does not move");check(!x.step(s,held(true)).cursor,"releasing one simultaneous direction is not a fresh press");}
 {auto one=s;one.weapons.resize(1);State x;open(x,one);check(!x.step(one,held(false,true)).cursor&&x.selected()==0,"single row has no cursor event");}
 {auto equipment=s;equipment.equipment.push_back({3,22,1,1,0,0,70,false});equipment.selectedEquipment=uint8_t(3);State x;x.step(equipment,{});check(x.step(equipment,lt).opened&&x.choice()->item==22,"equipment has its own namespace");e=x.step(equipment,{});check(e.confirm&&e.confirm->kind==Kind::equipment&&e.confirm->item.slot==3,"equipment request retains domain and slot");}
 for(int reason=0;reason<12;++reason){auto bad=s;switch(reason){case 0:bad.scope[0]=0;break;case 1:bad.scope[1]=0;break;case 2:bad.scope[2]=0;break;case 3:bad.scope[3]=24;break;case 4:bad.scope[4]=65536;break;case 5:bad.scope[5]=0;break;case 6:bad.scope[6]=0;break;case 7:bad.weapons[0].quantity=0;break;case 8:bad.weapons[0].revision=0;break;case 9:bad.weapons[0].item=0;break;case 10:bad.weapons[1].slot=0;break;case 11:bad.selectedEquipment=uint8_t(2);break;}check(!State::valid(bad),"invalid authoritative snapshot rejected");State x;open(x,s);e=x.step(bad,{});check(!e.confirm&&e.cancelled,"invalid state blocks release");}
 {auto duplicate=s;duplicate.equipment.push_back(s.weapons[0]);check(!State::valid(duplicate),"slot cannot appear in both namespaces");}
 {State x;open(x,s);auto dropInput=held();dropInput.drop=true;auto dropped=x.step(s,dropInput);check(dropped.confirm&&dropped.confirm->action==Action::drop&&dropped.confirm->item==s.weapons[0]&&!x.visible()&&x.blocks_gameplay(),"A requests exact highlighted drop once");check(!x.step(s,dropInput).confirm,"A hold never repeats");dropInput.weapons=false;check(!x.step(s,dropInput).confirm&&x.blocks_gameplay(),"A still held blocks roll after trigger release");dropInput.drop=false;check(!x.step(s,dropInput).confirm&&!x.blocks_gameplay(),"full neutral ends drop guard without equip");}
 {State x;x.step(s,{});auto dropInput=held();dropInput.drop=true;check(x.step(s,dropInput).opened&&!x.step(s,dropInput).confirm,"A already held while opening is not dropInput drop edge");dropInput.drop=false;x.step(s,dropInput);dropInput.drop=true;check(x.step(s,dropInput).confirm->action==Action::drop,"fresh A after release permits drop");}
 {State x;open(x,s);Input simultaneousRelease;simultaneousRelease.drop=true;auto releaseEvent=x.step(s,simultaneousRelease);check(releaseEvent.cancelled&&!releaseEvent.confirm,"A with trigger release cannot accidentally equip");}
 for(size_t n=0;n<s.scope.size();++n){State x;open(x,s);auto changed=s;++changed.scope[n];auto dropInput=held();dropInput.drop=true;check(!x.step(changed,dropInput).confirm,"drop preserves complete frozen scope");}
 {State x;open(x,s);auto changed=s;++changed.weapons[0].revision;auto dropInput=held();dropInput.drop=true;check(!x.step(changed,dropInput).confirm,"drop refuses replacement held revision");}
 std::cout<<"hold_selection_test PASS: release-equip/A-drop, scope/holdings freeze, trigger conflicts, focus/menu cancellation, empty ownership and neutral gating\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
