#include "combat_service.h"
#include "host_session.h"
#include "dedicated_peer.h"
#include <chrono>
#include <fstream>
#include <iostream>
#include <sstream>
using namespace mgo2mt;
namespace {
void check(bool b,const char*s){if(!b)throw std::runtime_error(s);}
template<class F>bool rejects(F f){try{f();return false;}catch(const std::exception&){return true;}}
environment::Config manual(){environment::Config c;c.weatherOverride=c.fog=c.rain=c.snow=c.sandstorm=c.manualHemisphere=true;c.time=environment::Time::night;c.sound=environment::Sound::sandstorm;c.upper={0,128,255};c.lower={255,1,0};c.gainMilli=1750;return c;}
std::vector<combat::wire::Environment> settings(combat::Service&s){std::vector<combat::wire::Environment> out;for(auto&d:s.deliveries()){auto r=combat::wire::decode(d.payload);if(auto e=std::get_if<combat::wire::Environment>(&r))out.push_back(*e);}return out;}
std::vector<uint8_t>profile(){std::vector<uint8_t>b(45);b[0]=2;b.insert(b.end(),{'P','l','a','y','e','r',0});return b;}
}
int main(){try{
 const auto c=manual();combat::wire::Environment e{71,3,c};auto bytes=combat::wire::encode(e);check(bytes.size()==34,"small separate environment record");
 for(unsigned t=0;t<6;++t)for(unsigned s=0;s<6;++s){auto v=e;v.config.time=environment::Time(t);v.config.sound=environment::Sound(s);v.config.gainMilli=t%2?0:4000;check(std::get<combat::wire::Environment>(combat::wire::decode(combat::wire::encode(v)))==v,"all enum and gain endpoints roundtrip");}
 for(size_t n=0;n<bytes.size();++n)check(rejects([&]{combat::wire::decode(std::span(bytes).first(n));}),"all truncations rejected");
 for(auto [offset,value]:std::array<std::pair<unsigned,unsigned>,4>{{{23,64},{24,6},{25,6},{33,255}}}){auto bad=bytes;bad[offset]=uint8_t(value);check(rejects([&]{combat::wire::decode(bad);}),"invalid reserved flags enum or gain rejected");}
 auto tail=bytes;tail.push_back(0);check(rejects([&]{combat::wire::decode(tail);}),"trailing bytes rejected");auto zero=e;zero.revision=0;check(rejects([&]{combat::wire::encode(zero);}),"zero revision rejected");zero=e;zero.epoch=0;check(rejects([&]{combat::wire::encode(zero);}),"zero epoch rejected");
 combat::EnvironmentReceiver receiver;combat::wire::Offer offer{71,{1,2,3}};check(receiver.receive(e,offer),"first setting");auto stale=e;stale.revision=2;check(!receiver.receive(stale,offer),"old revision rejected");stale=e;stale.config={};check(!receiver.receive(stale,offer),"conflicting same revision rejected");stale.revision=4;check(receiver.receive(stale,offer)&&receiver.state()->config==environment::Config{},"new all-OFF clears prior weather and hemisphere");stale.epoch=72;check(!receiver.receive(stale,offer),"wrong epoch rejected");receiver.clear();check(!receiver.state(),"disconnect clear");
 const auto dir=std::filesystem::temp_directory_path()/("mgo2mt-environment-test-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));const auto file=dir/"environment.cfg";
 check(environment::load(file)==environment::Config{},"missing persisted config preserves original");environment::save(file,c);check(environment::load(file)==c,"persist all manual selections");auto invalid=c;invalid.gainMilli=4001;check(rejects([&]{environment::save(file,invalid);})&&environment::load(file)==c,"invalid save cannot replace prior settings");
 for(auto str:{"MGO2MT_ENVIRONMENT 1 64 0 0 1 2 3 4 5 6 1000","MGO2MT_ENVIRONMENT 1 0 6 0 1 2 3 4 5 6 1000","MGO2MT_ENVIRONMENT 1 0 0 0 256 2 3 4 5 6 1000","MGO2MT_ENVIRONMENT 1 0 0 0 1 2 3 4 5 6 nan","MGO2MT_ENVIRONMENT 1 0 0 0 1 2 3 4 5 6 1000 extra"})check(rejects([&]{std::istringstream in(str);environment::read(in);}),"malformed persisted setting rejected");std::filesystem::remove_all(dir);
 auto control=std::make_shared<environment::Control>();check(control->configure(c)&&control->state().revision==2,"first change increments revision");check(control->configure(c)&&control->state().revision==2&&!control->configure(invalid),"same value and rejected value retain revision");
 combat::Identity id{1,1,200},late{2,2,300};combat::Service service(71);service.configure_environment(control);check(service.admit(id)&&service.admit(late),"admit waiting world");service.deliveries();service.poll(0);check(settings(service).empty(),"unaccepted peers get no settings");check(service.receive(id,combat::wire::encode(combat::wire::Accept{71}),1),"accept capability");auto initial=settings(service);check(initial.size()==1&&initial[0].config==c,"initial accept gets latest immediately");
 for(unsigned n=0;n<3;++n){auto next=c;next.gainMilli=uint16_t(2000+n);control->configure(next);service.poll(10+n);}auto latest=settings(service);check(latest.size()==1&&latest[0].config.gainMilli==2002,"only newest queued environment survives");service.poll(20);check(settings(service).empty(),"no redundant sub-second publication");service.poll(1012);check(settings(service).size()==1,"unchanged current settings refresh within one second");check(!service.receive(id,combat::wire::encode(e),1100),"client cannot set host environment");control->configure({});service.poll(1101);check(settings(service)[0].config==environment::Config{},"OFF broadcast clears settings");check(service.receive(late,combat::wire::encode(combat::wire::Accept{71}),1200),"late accept");check(settings(service)[0].config==environment::Config{},"late join receives current OFF state");
 // Real encrypted sessions: retry, reordered batches, duplicate packets and late join.
 combat::Service encrypted(1);auto shared=std::make_shared<environment::Control>();shared->configure(c);encrypted.configure_environment(shared);
 host::Hello owner{100,0x12345678,2,1,{{{192,0,2,1},5732}}};std::array<host::Hello,2>hello{{{200,0xabcdef01,2,2,{{{192,0,2,2},5730}}},{300,0x11223344,2,2,{{{192,0,2,3},5730}}}}};
 std::array<host::Machine,2>clients{{{hello[0],100,profile(),0},{hello[1],100,profile(),1200}}};std::array<host::DedicatedPeer,2>servers{{{owner,hello[0],0},{owner,hello[1],1200}}};std::array<host::Player,2>roster{{{1,0x101,200,"Player",{}},{2,0x102,300,"Player",{}}}};std::array<combat::Identity,2>ids{{{1,0x101,200},{2,0x102,300}}};std::array<bool,2>admitted{},synced{};unsigned rx=0,tx=0;bool observedInitial=false;
 for(uint64_t now=0;now<4000;now+=10){if(now==800)shared->configure({});for(unsigned i=0;i<2;++i){if(i==1&&now<1200)continue;for(auto&p:clients[i].poll(now))if(++tx%17)servers[i].receive(p,now);for(auto&ev:servers[i].events()){
  if(ev[0]==2&&!admitted[i]){admitted[i]=true;servers[i].queue(host::roster_record({0,0x100,100,"Host",{}},owner),now);for(unsigned j=0;j<2;++j)if(admitted[j])servers[i].queue(host::roster_record(roster[j],hello[j]),now);servers[i].queue({7,0,0,0,0,0,3},now);for(unsigned j=0;j<2;++j)if(i!=j&&admitted[j])servers[j].queue(host::roster_record(roster[i],hello[i]),now);}
  else if(ev[0]==10&&!synced[i]){synced[i]=true;servers[i].queue(host::room_snapshot(std::array<host::Rotation,1>{{{20,1,0}}},1),now);check(encrypted.admit(ids[i]),"encrypted admitted");}else if(combat::wire::recognized(ev))encrypted.receive(ids[i],ev,now);
 }}encrypted.poll(now);for(auto&d:encrypted.deliveries())servers[d.recipient.character==200?0:1].queue(std::move(d.payload),now);for(unsigned i=0;i<2;++i){if(i==1&&now<1200)continue;auto out=servers[i].poll(now);for(auto it=out.rbegin();it!=out.rend();++it)if(++rx%19){clients[i].receive(*it,now);clients[i].receive(*it,now);}if(now<800&&clients[i].result().environment&&clients[i].result().environment->config==c)observedInitial=true;}}
 check(observedInitial,"encrypted first client observed initial manual settings");for(auto&client:clients){const auto r=client.result();check(r.stage==host::Stage::joined&&r.environment&&r.environment->config==environment::Config{}&&r.environment->revision==3,"existing and late clients converge to OFF under loss/reordering");client.cancel();check(!client.result().environment,"disconnect clears exposed setting");}
 std::cout<<"HOST environment: strict config/wire, current-only publication, independent OFF, encrypted loss/reorder/late join and disconnect PASS\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
