#include "weapon_fixture.h"
#include "character_screen.h"
#include <fstream>
#include <iostream>
using namespace mgo2win;
void check(bool v,const char*s){if(!v)throw std::runtime_error(s);}
int main(int argc,char**argv){try{
 std::atomic_uint advance=0,joins=0;std::atomic_bool cancellation=false;
 CharacterScreen ui([](const std::atomic_bool&){CharacterReply r;r.status=CharacterStatus::success;r.list.slots=4;r.list.entries.push_back({123,L"テストPC"});return r;});
 test::WeaponFixture fixture;auto catalogPath=std::filesystem::path(__FILE__).parent_path().parent_path()/"assets/weapon_catalog.tsv";
 ui.weapon_catalog(std::filesystem::exists(catalogPath)?catalogPath:fixture.path);
 if(argc>2)ui.weapon_icons(argv[2]);
 ui.selection([](uint32_t,const std::atomic_bool&){CharacterSelectionReply r;r.status=CharacterSelectionStatus::success;r.request_may_have_been_sent=true;r.character.id=123;r.lobbies.push_back({5,5735,1,L"Test Lobby",0,2});return r;},std::make_shared<CharacterSelectionState>());
 ui.rooms([&](uint32_t,const GameLobbyEntry&,const std::atomic_bool&stop,std::atomic_bool&,const RoomPublish&publish,RoomRequests&requests){RoomReply list;list.status=RoomStatus::ready;list.rooms.push_back({77,L"テストルーム",1,16});publish(list);while(!stop){if(auto action=requests.take()){RoomReply r;r.event=action->event;r.requested_room=77;r.status=RoomStatus::ready;RoomDetail d;d.id=77;d.name=L"テストルーム";d.comment=L"ホスト接続とエラー処理のオフライン試験";d.capacity=16;d.players=1;d.subtype=1;d.environment_known=true;d.briefing_minutes=2;d.roster={{456,L"テストホスト"}};r.detail=d;if(action->event==RoomEvent::detail){publish(r);continue;}++joins;for(auto stage:{RoomJoinStatus::host_connecting,RoomJoinStatus::host_profile,RoomJoinStatus::host_sync,RoomJoinStatus::joined}){unsigned expected=unsigned(stage)-unsigned(RoomJoinStatus::host_connecting)+1;r.join_status=stage;r.status=stage==RoomJoinStatus::joined?RoomStatus::ready:RoomStatus::connecting;if(stage==RoomJoinStatus::joined){r.host_roster=host::Roster{};r.host_match=host::MatchState{};r.host_match->revision=1;r.host_match->request=host::LoadRequest{1,3,0,0,{15,1,2},host::MatchTransition::initial};r.host_roster->complete=true;r.host_roster->revision=1;for(unsigned i=0;i<24;++i)r.host_roster->slots[i]=host::Player{uint8_t(i),uint16_t(i),i==0?456u:i==1?123u:1000+i,i==0?"Host":"Player-"+std::to_string(i+1),""};}publish(r);while(!stop&&!requests.cancel_join&&advance<expected)Sleep(1);if(stop||requests.cancel_join)break;}if(!stop&&!requests.cancel_join&&r.host_roster){r.host_roster->slots[23].reset();r.host_roster->revision=2;publish(r);while(!stop&&!requests.cancel_join&&advance<5)Sleep(1);if(!stop&&!requests.cancel_join){r.host_match->revision=2;r.host_match->request=host::LoadRequest{2,4,1,0,{20,1,0},host::MatchTransition::map_change};publish(r);}while(!stop&&!requests.cancel_join)Sleep(1);}cancellation=requests.cancel_join.load();r.host_roster.reset();r.host_match.reset();r.status=RoomStatus::ready;r.join_status=RoomJoinStatus::host_cancelled;publish(r);}Sleep(1);}});
 auto key=[&](WPARAM k){ui.message(nullptr,WM_KEYDOWN,k,0);};auto wait=[&](auto condition){auto until=GetTickCount64()+2500;while(!condition()&&GetTickCount64()<until){ui.draw();Sleep(1);}check(condition(),"host UI deadline");};
 auto capture=[&](const char*name){if(argc<2)return;std::filesystem::path dir=argv[1];std::filesystem::create_directories(dir);BITMAPFILEHEADER f{};BITMAPINFOHEADER h{};h.biSize=sizeof(h);h.biWidth=1280;h.biHeight=-720;h.biPlanes=1;h.biBitCount=32;h.biSizeImage=1280*720*4;f.bfType=0x4d42;f.bfOffBits=sizeof(f)+sizeof(h);f.bfSize=f.bfOffBits+h.biSizeImage;auto pixels=ui.draw();std::ofstream out(dir/name,std::ios::binary);out.write(reinterpret_cast<const char*>(&f),sizeof(f));out.write(reinterpret_cast<const char*>(&h),sizeof(h));out.write(static_cast<const char*>(pixels),h.biSizeImage);check(bool(out),"host UI capture");};
 ui.draw();wait([&]{return !ui.busy();});key(VK_RETURN);wait([&]{return ui.lobby_visible();});key(VK_RETURN);wait([&]{return ui.room_count()==1;});key(VK_RETURN);wait([&]{return ui.room_detail_visible()&&!ui.room_detail_busy();});key(VK_RETURN);
 wait([&]{return ui.room_join_status()==RoomJoinStatus::host_connecting;});capture("connecting.bmp");key(VK_RETURN);check(joins==1&&ui.room_detail_busy(),"pending duplicate prevented");advance=1;wait([&]{return ui.room_join_status()==RoomJoinStatus::host_profile;});capture("profile.bmp");advance=2;wait([&]{return ui.room_join_status()==RoomJoinStatus::host_sync;});capture("sync.bmp");advance=3;wait([&]{return ui.room_join_status()==RoomJoinStatus::joined;});check(!ui.room_detail_busy(),"joined completes the admission transaction");check(ui.room_loading(),"joined fixture waits for explicit stage feedback");key(VK_F10);key(VK_ESCAPE);check(!ui.room_match_visible()&&!cancellation&&joins==1,"loading blocks preview and cannot leave an admitted room");capture("joined_loading.bmp");ui.stage_feedback(stage::Status::preview_ready);check(!ui.room_loading(),"explicit local preview feedback completes loading");check(ui.stage_load_request()&&ui.stage_load_request()->rotation.map==15&&!ui.stage_request(),"room admission preloads stage while roster stays visible");check(ui.room_host_roster()&&ui.room_host_roster()->count()==24,"all live slots reach UI");capture("joined.bmp");advance=4;wait([&]{return ui.room_host_roster()&&ui.room_host_roster()->revision==2;});check(ui.room_host_roster()->count()==23,"same-stage participant update reaches UI");capture("participant_left.bmp");key(VK_F10);check(joins==1&&ui.room_match_visible(),"joined opens stage info without duplicate join");check(ui.room_host_match()&&ui.room_host_match()->request->rotation.map==15,"initial match metadata reaches UI");capture("stage_initial.bmp");advance=5;wait([&]{return ui.room_host_match()&&ui.room_host_match()->revision==2;});check(ui.room_host_match()->request->rotation.map==20&&ui.room_host_roster()->revision==2,"same-stage match-only update reaches UI");check(ui.stage_request()&&ui.stage_request()->rotation.map==20,"visible stage selects exact host map");ui.stage_feedback(stage::Status::preview_ready);capture("stage_changed.bmp");
 const std::wstring debugMetrics=L"FPS：60.0（描画）\n本人座標（足元・ワールド座標）\nX 1250.00   Y -250.50   Z 3200.00\nF4：モーションブレンド 500%/秒（約0.200秒）\n現在の合成率：自己 50%\n";
 const auto debugNotice=debugMetrics+L"F5：ローカル再初期化   F10：歩行確認／全景\nF7 / F8：曲選択   F9：再生／停止\nF11：倒れる／操作へ戻る　Shift+F11：物体落下\n物理姿勢：13剛体・12関節（ローカル確認）\n匍匐 / 三人称\nAUTO AIM OFF\nローカル操作確認（戦闘・移動送信は準備中）\n物体状態 32件受信済み / 世代 3\n受信配置 12件 / モデル未対応 0件\n原曲 32 / 88\nbgm_mgo_action01_layer1\n再生中\n\n診断：ステージと物体の読み込みを確認しています。長い説明もパネル内で折り返します。";
 auto checkDebugBounds=[&](int right){auto pixels=static_cast<const uint32_t*>(ui.draw());check((pixels[110*1280+120]>>24)!=0,"debug panel has a visible outer border");for(int y=0;y<720;++y)for(int x=0;x<1280;++x)if(x<120||x>=right||y<110||y>=700)check(!(pixels[y*1280+x]>>24),"debug text and panel stay within the canvas and reserved bounds");};
 ui.stage_navigation_feedback(true);ui.stage_debug_feedback(debugNotice);capture("stage_walk_ui.bmp");checkDebugBounds(610);
 {auto pixels=static_cast<const uint32_t*>(ui.draw());size_t covered=0;for(int y=120;y<512;++y)for(int x=620;x<1236;++x)if(pixels[y*1280+x]>>24)++covered;check(covered<616u*392u/100,"walking viewport remains clear of room labels and bands");}
 std::wstring longDebug=debugNotice+L"\n"+std::wstring(300,L'W');for(unsigned i=0;i<48;++i)longDebug+=L"\n追加診断：長い音源名と受信した物体の状態を確認しています。";
 ui.stage_debug_feedback(longDebug);capture("stage_walk_ui_long.bmp");checkDebugBounds(610);
 ui.stage_navigation_feedback(false);ui.stage_debug_feedback(L"");
 key(VK_F4);check(!ui.weapon_visible(),"hidden weapon shortcut cannot activate in stage view");key(VK_ESCAPE);check(!ui.room_match_visible()&&ui.room_join_status()==RoomJoinStatus::joined&&!cancellation,"stage Esc returns to briefing without leaving");key(VK_F4);check(ui.weapon_visible()&&ui.weapon_draft()&&!ui.room_match_visible()&&ui.stage_load_request(),"weapon panel keeps admitted room and preloaded stage");capture("weapons_initial.bmp");
 check(ui.weapon_draft()->selected(weapons::Category::primary)&&ui.weapon_draft()->selected(weapons::Category::primary)->id==25,"native default AK102 is selected before edits");key(VK_RETURN);check(ui.weapon_draft()->selected(weapons::Category::primary)&&ui.weapon_draft()->selected(weapons::Category::primary)->id==25,"unavailable NONE preserves the default in ordinary DP-off profile");
 key(VK_RIGHT);key(VK_RETURN);check(ui.weapon_draft()->selected(weapons::Category::primary)&&ui.weapon_draft()->selected(weapons::Category::primary)->id==23,"main weapon selected through keyboard");
 if(ui.weapon_draft()->choices(weapons::Category::primary).size()>6){key(VK_DOWN);key(VK_RETURN);check(ui.weapon_draft()->selected(weapons::Category::primary)->id==23,"DP-only grid row cannot replace allowed choice");key(VK_UP);key(VK_RETURN);}
 key(VK_F2);key(VK_RIGHT);key(VK_RETURN);check(ui.weapon_draft()->selected(weapons::Category::secondary)&&ui.weapon_draft()->selected(weapons::Category::secondary)->id==7,"secondary weapon selected through shoulder tab navigation");
 key(VK_TAB);key(VK_RIGHT);key(VK_RETURN);key(VK_F10);check(ui.weapon_draft()->complete()&&ui.weapon_draft()->quote().cost==0&&joins==1,"full basic loadout stored without DP charge or another room join");capture("weapons_selected.bmp");
 key(VK_ESCAPE);check(!ui.weapon_visible()&&ui.room_join_status()==RoomJoinStatus::joined&&ui.weapon_draft()->complete(),"back preserves draft without leaving room");key(VK_F10);
ui.stage_debug_feedback(debugMetrics+L"F5：ローカル再初期化  #2  参考配置18件\nF7 / F8：曲選択   F9：再生／停止\n原曲 32 / 88\nbgm_mgo_action01_layer1\n再生中\n指定BGMがありません。ローカル曲へ復帰。");capture("stage_debug.bmp");checkDebugBounds(800);ui.stage_reset_feedback(true,false);capture("stage_reset_no.bmp");ui.stage_reset_feedback(true,true);capture("stage_reset_yes.bmp");ui.stage_reset_feedback(false,false);ui.stage_debug_feedback(L"");ui.stage_feedback(stage::Status::invalid);capture("stage_invalid.bmp");ui.stage_feedback(stage::Status::unavailable);capture("stage_unavailable.bmp");key(VK_RETURN);check(ui.room_match_visible(),"hidden stage Enter cannot activate room buttons");key(VK_ESCAPE);check(!ui.room_match_visible()&&!ui.stage_request()&&ui.stage_load_request()&&ui.stage_load_request()->rotation.map==20,"Esc hides preview without discarding round preparation");key(VK_ESCAPE);check(!cancellation&&ui.room_join_status()==RoomJoinStatus::joined&&ui.briefing_panel()==briefing::Panel::none,"briefing Esc never requests leave");for(unsigned i=0;i<7&&ui.briefing_focus()!=6;++i)key(VK_RIGHT);key(VK_RETURN);check(ui.briefing_panel()==briefing::Panel::quit&&!ui.briefing_confirm_yes(),"QUIT defaults to NO");key(VK_RETURN);check(!cancellation&&ui.room_join_status()==RoomJoinStatus::joined,"QUIT NO retains room");key(VK_RETURN);key(VK_LEFT);key(VK_RETURN);wait([&]{return ui.room_join_status()==RoomJoinStatus::host_cancelled;});check(cancellation&&!ui.room_detail_busy()&&ui.room_detail_visible(),"only QUIT YES requests leave and waits for cleanup result");check(!ui.room_host_roster()&&!ui.room_host_match()&&!ui.room_match_visible()&&!ui.stage_load_request(),"terminal reply clears roster, stage preparation and match panel");capture("left.bmp");key(VK_ESCAPE);check(!ui.room_detail_visible(),"return after cleanup");
 advance=0;cancellation=false;key(VK_RETURN);wait([&]{return ui.room_detail_visible()&&!ui.room_detail_busy();});key(VK_RETURN);wait([&]{return ui.room_join_status()==RoomJoinStatus::host_connecting;});key(VK_ESCAPE);wait([&]{return ui.room_join_status()==RoomJoinStatus::host_cancelled;});check(cancellation&&joins==2,"Esc during connection cancels worker");
 std::cout<<"host UI progress, duplicate prevention, in-progress cancel and leave passed\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
