#include "character_screen.h"
#include <fstream>
#include <iostream>
using namespace mgo2win;
void check(bool v,const char*s){if(!v)throw std::runtime_error(s);}
int main(int argc,char**argv){try{
 std::atomic_uint advance=0,joins=0;std::atomic_bool cancellation=false;
 CharacterScreen ui([](const std::atomic_bool&){CharacterReply r;r.status=CharacterStatus::success;r.list.slots=4;r.list.entries.push_back({123,L"テストPC"});return r;});
 ui.selection([](uint32_t,const std::atomic_bool&){CharacterSelectionReply r;r.status=CharacterSelectionStatus::success;r.request_may_have_been_sent=true;r.character.id=123;r.lobbies.push_back({5,5735,1,L"Test Lobby",0,2});return r;},std::make_shared<CharacterSelectionState>());
 ui.rooms([&](uint32_t,const GameLobbyEntry&,const std::atomic_bool&stop,std::atomic_bool&,const RoomPublish&publish,RoomRequests&requests){RoomReply list;list.status=RoomStatus::ready;list.rooms.push_back({77,L"テストルーム",1,16});publish(list);while(!stop){if(auto action=requests.take()){RoomReply r;r.event=action->event;r.requested_room=77;r.status=RoomStatus::ready;RoomDetail d;d.id=77;d.name=L"テストルーム";d.comment=L"ホスト接続とエラー処理のオフライン試験";d.capacity=16;d.players=1;d.subtype=1;d.roster={{456,L"テストホスト"}};r.detail=d;if(action->event==RoomEvent::detail){publish(r);continue;}++joins;for(auto stage:{RoomJoinStatus::host_connecting,RoomJoinStatus::host_profile,RoomJoinStatus::host_sync,RoomJoinStatus::joined}){unsigned expected=unsigned(stage)-unsigned(RoomJoinStatus::host_connecting)+1;r.join_status=stage;r.status=stage==RoomJoinStatus::joined?RoomStatus::ready:RoomStatus::connecting;if(stage==RoomJoinStatus::joined){r.host_roster=host::Roster{};r.host_match=host::MatchState{};r.host_match->revision=1;r.host_match->request=host::LoadRequest{1,3,0,0,{15,1,2},host::MatchTransition::initial};r.host_roster->complete=true;r.host_roster->revision=1;for(unsigned i=0;i<24;++i)r.host_roster->slots[i]=host::Player{uint8_t(i),uint16_t(i),i==0?456u:i==1?123u:1000+i,i==0?"Host":"Player-"+std::to_string(i+1),""};}publish(r);while(!stop&&!requests.cancel_join&&advance<expected)Sleep(1);if(stop||requests.cancel_join)break;}if(!stop&&!requests.cancel_join&&r.host_roster){r.host_roster->slots[23].reset();r.host_roster->revision=2;publish(r);while(!stop&&!requests.cancel_join&&advance<5)Sleep(1);if(!stop&&!requests.cancel_join){r.host_match->revision=2;r.host_match->request=host::LoadRequest{2,4,1,0,{20,3,2},host::MatchTransition::map_change};publish(r);}while(!stop&&!requests.cancel_join)Sleep(1);}cancellation=requests.cancel_join.load();r.host_roster.reset();r.host_match.reset();r.status=RoomStatus::ready;r.join_status=RoomJoinStatus::host_cancelled;publish(r);}Sleep(1);}});
 auto key=[&](WPARAM k){ui.message(nullptr,WM_KEYDOWN,k,0);};auto wait=[&](auto condition){auto until=GetTickCount64()+2500;while(!condition()&&GetTickCount64()<until){ui.draw();Sleep(1);}check(condition(),"host UI deadline");};
 auto capture=[&](const char*name){if(argc<2)return;std::filesystem::path dir=argv[1];std::filesystem::create_directories(dir);BITMAPFILEHEADER f{};BITMAPINFOHEADER h{};h.biSize=sizeof(h);h.biWidth=1280;h.biHeight=-720;h.biPlanes=1;h.biBitCount=32;h.biSizeImage=1280*720*4;f.bfType=0x4d42;f.bfOffBits=sizeof(f)+sizeof(h);f.bfSize=f.bfOffBits+h.biSizeImage;auto pixels=ui.draw();std::ofstream out(dir/name,std::ios::binary);out.write(reinterpret_cast<const char*>(&f),sizeof(f));out.write(reinterpret_cast<const char*>(&h),sizeof(h));out.write(static_cast<const char*>(pixels),h.biSizeImage);check(bool(out),"host UI capture");};
 ui.draw();wait([&]{return !ui.busy();});key(VK_RETURN);wait([&]{return ui.lobby_visible();});key(VK_RETURN);wait([&]{return ui.room_count()==1;});key(VK_RETURN);wait([&]{return ui.room_detail_visible()&&!ui.room_detail_busy();});key(VK_RETURN);
 wait([&]{return ui.room_join_status()==RoomJoinStatus::host_connecting;});capture("connecting.bmp");key(VK_RETURN);check(joins==1&&ui.room_detail_busy(),"pending duplicate prevented");advance=1;wait([&]{return ui.room_join_status()==RoomJoinStatus::host_profile;});capture("profile.bmp");advance=2;wait([&]{return ui.room_join_status()==RoomJoinStatus::host_sync;});capture("sync.bmp");advance=3;wait([&]{return ui.room_join_status()==RoomJoinStatus::joined;});check(!ui.room_detail_busy(),"joined offers leave");check(ui.room_host_roster()&&ui.room_host_roster()->count()==24,"all live slots reach UI");capture("joined.bmp");advance=4;wait([&]{return ui.room_host_roster()&&ui.room_host_roster()->revision==2;});check(ui.room_host_roster()->count()==23,"same-stage participant update reaches UI");capture("participant_left.bmp");key(VK_RETURN);check(joins==1&&ui.room_match_visible(),"joined opens stage info without duplicate join");check(ui.room_host_match()&&ui.room_host_match()->request->rotation.map==15,"initial match metadata reaches UI");capture("stage_initial.bmp");advance=5;wait([&]{return ui.room_host_match()&&ui.room_host_match()->revision==2;});check(ui.room_host_match()->request->rotation.map==20&&ui.room_host_roster()->revision==2,"same-stage match-only update reaches UI");capture("stage_changed.bmp");key(VK_RETURN);check(!ui.room_match_visible(),"stage info returns to roster");key(VK_RETURN);key(VK_ESCAPE);wait([&]{return ui.room_join_status()==RoomJoinStatus::host_cancelled;});check(cancellation&&!ui.room_detail_busy()&&ui.room_detail_visible(),"Esc requests leave and waits for cleanup result");check(!ui.room_host_roster()&&!ui.room_host_match()&&!ui.room_match_visible(),"terminal reply clears roster and match panel");capture("left.bmp");key(VK_ESCAPE);check(!ui.room_detail_visible(),"return after cleanup");
 advance=0;cancellation=false;key(VK_RETURN);wait([&]{return ui.room_detail_visible()&&!ui.room_detail_busy();});key(VK_RETURN);wait([&]{return ui.room_join_status()==RoomJoinStatus::host_connecting;});key(VK_ESCAPE);wait([&]{return ui.room_join_status()==RoomJoinStatus::host_cancelled;});check(cancellation&&joins==2,"Esc during connection cancels worker");
 std::cout<<"host UI progress, duplicate prevention, in-progress cancel and leave passed\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
