#include "combat_service.h"
#include <cmath>
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace mgo2mt;using namespace mgo2mt::combat;
namespace {
void check(bool b,const char*why){if(!b)throw std::runtime_error(why);}
constexpr Identity a{0,1,100},b{1,2,200},c{2,3,300};
Pose pose(float z,float x=0){Pose p;p.feet={x,2,z};return p;}
std::shared_ptr<const stage::Collision> world(){return std::make_shared<const stage::Collision>(stage::Collision::make({{-100000,0,-100000},{100000,0,-100000},{100000,0,100000},{-100000,0,100000}},{{{0,1,2},stage::attribute::native_solid},{{0,2,3},stage::attribute::native_solid}}));}
std::vector<Weapon> weapons(){Weapon carried;carried.id=25;carried.damage=100;carried.intervalMs=100;carried.reloadMs=1000;carried.magazine=10;carried.reserve=20;carried.range=20000;Weapon mount=carried;mount.id=500;mount.damage=120;mount.automatic=true;mount.magazine=5;mount.reserve=0;mount.mountedOnly=true;return {carried,mount};}
mounted::Registry registry(bool infinite=true){mounted::Registry r;mounted::Type t;t.id="m2";t.name="M2";t.model="data/m2.gwm";t.weapon=500;t.pivot={0,1000,0};t.muzzle={0,1200,1000};t.operatorOffset={0,0,-600};t.yawMin=-.5f;t.yawMax=.5f;t.pitchMin=-.2f;t.pitchMax=.3f;t.infiniteAmmo=infinite;r.types.push_back(t);r.placements.push_back({20,1,"m2",{0,2,0},0});return r;}
void start(Authority&h,bool infinite=true){auto ws=weapons();h.begin(1,world(),ws);check(h.configure_mounted(registry(infinite),20),"configure mounted");const uint16_t gear[]{25};check(h.join(a,1,pose(-600),1000,1000,gear,0)&&h.join(b,2,pose(5000),1000,1000,gear,0)&&h.join(c,1,pose(-1600),1000,1000,gear,0),"join");h.active(true);}
void enter(Authority&h,uint64_t now=0,uint32_t sequence=1,uint32_t request=1){check(h.pose(a,1,sequence,pose(-600),now)==Reject::none,"fresh mount pose");check(h.mount(a,1,sequence,{mounted::Action::mount,1,request},now)==Reject::none,"mount admitted");}
void lifecycle(){Authority h;start(h);const auto inventory=*h.item_held(a,1);enter(h);auto p=*h.snapshot().players[a.slot];check(p.mountedId==1&&p.weapon==500&&p.ammo==5,"mount state");check(h.mount(a,1,1,{mounted::Action::mount,1,1},0)==Reject::sequence,"edge replay");check(h.mount(a,2,1,{mounted::Action::dismount,0,2},0)==Reject::generation,"wrong epoch");check(h.mount(a,1,1,{mounted::Action::dismount,0,2},0,2)==Reject::generation,"wrong life");check(h.pose(c,1,1,pose(-1600),0)==Reject::none,"second operator pose");check(h.mount(c,1,1,{mounted::Action::mount,1,1},0)==Reject::unavailable,"exclusive seat");
 auto moved=pose(50000);moved.yaw=2;moved.pitch=1;check(h.pose(a,1,2,moved,100)==Reject::none,"mounted movement pinned");p=*h.snapshot().players[a.slot];check(p.pose.feet==Vec3{0,2,-600}&&std::abs(p.pose.yaw-.5f)<.0001f&&std::abs(p.pose.pitch-.3f)<.0001f,"yaw pitch clamped");check(h.equip(a,1,25,100)==Reject::unavailable,"equip blocked");check(h.reload(a,1,100).reject==Reject::unavailable,"reload blocked");check(h.melee(a,{1,1,500,{0,0,1}},100).reject==Reject::unavailable,"punch blocked");
 check(h.pose(a,1,3,pose(-600),200)==Reject::none,"aim forward");auto shot=h.fire(a,{1,2,500,{0,0,1}},200);check(bool(shot)&&shot.events.size()==3,"mounted shot impact damage");check(shot.events[0].position==Vec3{0,1202,1000},"exact host muzzle");check(h.snapshot().players[b.slot]->hp==880&&h.snapshot().players[a.slot]->ammo==5,"mounted damage infiniteammo");check(h.fire(a,{1,3,500,{0,0,1}},201).reject==Reject::interval,"fire cadence");
 check(h.release_mounted(a),"release");p=*h.snapshot().players[a.slot];check(!p.mountedId&&p.weapon==25&&p.ammo==10&&p.reserve==20,"restore carried selected weapon");check(h.item_held(a,1)->slots==inventory.slots,"inventory exact preservation");enter(h,300,4,2);h.advance(800);check(!h.snapshot().players[a.slot]->mountedId,"no-input timeout release");enter(h,900,5,3);h.active(false);check(!h.snapshot().players[a.slot]->mountedId,"roundstop release");
 Authority finite;start(finite,false);enter(finite);for(unsigned i=0;i<5;++i){check(finite.pose(a,1,i+2,pose(-600),i*100)==Reject::none,"finite aim");check(bool(finite.fire(a,{1,i+1,500,{0,0,1}},i*100)),"finite shot");}check(!finite.snapshot().players[a.slot]->ammo,"finite magazine consumed");finite.release_mounted(a);enter(finite,500,7,2);check(finite.fire(a,{1,6,500,{0,0,1}},500).reject==Reject::no_ammo,"remount never replenishes");
 Authority death;start(death);enter(death);burning::Blast blast{{{1,b.slot,b.instance,b.character,1},52,0,2},1,{0,1000,-600},5000,10000,false};death.explode(blast,0);check(!death.snapshot().players[a.slot]->alive&&!death.snapshot().players[a.slot]->mountedId,"death releases");Authority stun;start(stun);enter(stun);blast.damage=0;blast.staminaDamage=10000;stun.explode(blast,0);check(stun.snapshot().players[a.slot]->stunned&&!stun.snapshot().players[a.slot]->mountedId,"stun releases");
 Authority denied;start(denied);check(denied.pose(b,1,1,pose(5000),0)==Reject::none,"distant pose");check(denied.mount(b,1,1,{mounted::Action::mount,1,1},0)==Reject::invalid_pose,"range rejected");const uint16_t mountGear[]{500};check(!denied.join({3,4,400},1,pose(10000),1000,1000,mountGear,0),"mounted cannot inventorygrant");
}
void occlusion(){auto geometry=stage::Collision::make({{-100000,0,-100000},{100000,0,-100000},{100000,0,100000},{-100000,0,100000},{-2000,0,500},{2000,0,500},{2000,3000,500},{-2000,3000,500}},{{{0,1,2},stage::attribute::native_solid},{{0,2,3},stage::attribute::native_solid},{{4,5,6},stage::attribute::native_solid},{{4,6,7},stage::attribute::native_solid}});Authority h;auto ws=weapons();h.begin(1,std::make_shared<const stage::Collision>(geometry),ws);check(h.configure_mounted(registry(),20),"wall scene");const uint16_t gear[]{25};check(h.join(a,1,pose(-600),1000,1000,gear,0)&&h.join(b,2,pose(5000),1000,1000,gear,0),"wall bodies");h.active(true);enter(h);check(h.fire(a,{1,1,500,{0,0,1}},0).reject==Reject::obstructed,"barrel beyond wall never shoots through");check(h.snapshot().players[b.slot]->hp==1000&&h.snapshot().players[a.slot]->ammo==5,"blocked muzzle no ammo/damage");h.world(world());check(!h.snapshot().players[a.slot]->mountedId,"world reset releases old seat");}
void collider(){auto r=registry();r.types[0].collisionCenter={0,600,0};r.types[0].collisionHalfExtents={300,600,300};auto geometry=mounted::with_collision(*world(),r,20);auto again=mounted::with_collision(geometry,r,20);check(geometry.vertices.size()==again.vertices.size()&&geometry.triangles.size()==again.triangles.size(),"mounted collider idempotent");auto hit=geometry.ray({0,602,-2000},{0,0,1},5000);check(hit&&std::abs(hit->distance-1700)<.1f&&geometry.triangles[hit->triangle].object==0xf0320001u,"mounted base raycollision");check(geometry.clear({0,2,-600},{260,1700,2})&&!geometry.clear({0,2,0},{260,1700,2}),"operatorclear baseblocks capsule");projectile::Pool pool;pool.reset({1,1});check(pool.spawn({{1,1},{0,1,100,1},1,52,{0,602,-1000},{0,0,1}},projectile::native_throw(52),0)==projectile::Submit::accepted,"grenade spawn");pool.advance(100,[&](Vec3 a,Vec3 d,float maximum,projectile::Owner)->std::optional<projectile::Contact>{auto h=geometry.ray(a,d,maximum);if(!h)return {};return projectile::Contact{h->distance,h->normal,{},geometry.triangles[h->triangle].object};});const auto debug=pool.debug_flights();check(debug.size()==1&&debug[0].position[2]<-300,"grenade reflects frommountedbase");Authority h;auto ws=weapons();h.begin(1,world(),ws);check(h.configure_mounted(r,20),"authoritycollider");const uint16_t gear[]{25};check(h.join(a,1,pose(-600),1000,1000,gear,0),"collider operatorjoin");h.active(true);enter(h);check(h.object_world(world()),"objectscene replacement");check(h.release_mounted(a),"collider release");check(h.pose(a,1,2,pose(0),100)==Reject::obstructed,"replacement preservesmountedbase");}
void configured_ak(){auto fire=[&](uint32_t damage,float range){Authority h;auto ws=weapons();ws[0].nativeAkPenetration=true;ws[0].damage=damage;ws[0].range=range;ws[0].ballistics=original_weapon::Ballistic{range,473750,0,range,1000,250};h.begin(1,world(),ws);const uint16_t gear[]{25};check(h.join(a,1,pose(-600),1000,1000,gear,0)&&h.join(b,2,pose(5000),1000,1000,gear,0),"configured AK bodies");h.active(true);check(bool(h.fire(a,{1,1,25,{0,0,1}},0)),"configured AK shot");return 1000-h.snapshot().players[b.slot]->hp;};check(fire(110,8000)==110,"configured AK damage110 applied");check(fire(330,8000)==330,"configured AK damage330 applied");check(fire(330,4000)==0,"configured AK range applied");}
void orbit(){
 auto r=registry();auto& t=r.types[0];t.operatorOrbit=true;t.operatorOffset={0,0,-1200};t.yawMin=-1.8f;t.yawMax=1.8f;t.collisionCenter={0,600,0};t.collisionHalfExtents={300,600,300};
 auto begin=[&](Authority& h,std::shared_ptr<const stage::Collision> geometry,bool peer){auto ws=weapons();h.begin(1,std::move(geometry),ws);check(h.configure_mounted(r,20),"orbit registry");const uint16_t gear[]{25};auto initial=pose(-1200);initial.yaw=.8f;check(h.join(a,1,initial,1000,1000,gear,0),"orbit operator");if(peer)check(h.join(b,2,pose(-848.528f,-848.528f),1000,1000,gear,0),"orbit peer obstacle");h.active(true);check(h.pose(a,1,1,initial,0)==Reject::none&&h.mount(a,1,1,{mounted::Action::mount,1,1},0)==Reject::none,"orbit mount");check(h.snapshot().players[a.slot]->pose.yaw==0,"mount aligns initial yaw");};
 Pose requested=pose(99999);requested.yaw=1.57079632679f;requested.pitch=.2f;
 Authority free;begin(free,world(),false);check(free.pose(a,1,2,requested,0)==Reject::none,"orbit independent of walking speed");auto p=free.snapshot().players[a.slot]->pose;auto expected=mounted::operator_position(r.placements[0],t,requested.yaw);check(std::hypot(p.feet[0]-expected[0],p.feet[2]-expected[2])<.01f&&std::abs(p.yaw-requested.yaw)<.0001f,"operator orbits turret pivot");check(p.feet[1]==2,"orbit keeps original ground elevation");
 auto path=mounted::operator_path(r.placements[0],t,0,requested.yaw);check(path.size()>20&&path.back()==expected,"arc samples include destination");
 Authority peer;begin(peer,world(),true);check(peer.pose(a,1,2,requested,0)==Reject::none,"peer blocked orbit accepted with correction");p=peer.snapshot().players[a.slot]->pose;check(p.yaw==0&&p.feet==Vec3{0,2,-1200}&&p.pitch==.2f,"arc cannot pass through another player");
 auto vertices=world()->vertices;auto triangles=world()->triangles;vertices.insert(vertices.end(),{{-700,0,-1600},{-700,3000,-1600},{-700,3000,200},{-700,0,200}});triangles.push_back({{4,5,6},stage::attribute::native_solid});triangles.push_back({{4,6,7},stage::attribute::native_solid});Authority wall;begin(wall,std::make_shared<const stage::Collision>(stage::Collision::make(std::move(vertices),std::move(triangles))),false);check(wall.pose(a,1,2,requested,0)==Reject::none,"wall blocked orbit accepted with correction");p=wall.snapshot().players[a.slot]->pose;check(p.yaw==0&&p.feet==Vec3{0,2,-1200},"operator cannot orbit through wall");
}
void packets(){Authority h;start(h);enter(h);auto s=h.snapshot();for(unsigned i=0;i<24;++i){auto p=*s.players[0];p.identity={uint8_t(i),uint16_t(i+1),i+1};p.mountedId=uint16_t(i+1);s.players[i]=p;}Event e;e.epoch=1;e.id=1;e.source=s.players[0]->identity;e.weapon=500;e.sourceLife=1;e.kind=EventKind::shot;s.eventWatermark=1;wire::Frame frame{s,wire::Status::active,{e},h.sop_view(a).value()};frame.sop.recipient=s.players[0]->identity;auto encoded=wire::encode(frame);std::cout<<"24 mounted + shot + SOP bytes="<<encoded.size()<<char(10);check(encoded.size()<=2000,"24 mounted plus event fits");check(std::get<wire::Frame>(wire::decode(encoded))==frame,"mounted snapshot wire roundtrip");Replica replica;check(replica.snapshot(s),"mounted replica valid");s.players[0]->mountedId=40000;check(!replica.snapshot(s),"invalid mount rejected");
 wire::Input input;input.epoch=1;input.sequence=1;input.pose=pose(-600);input.weapon=25;input.mounted={mounted::Action::mount,1,1};encoded=wire::encode(input);check(std::get<wire::Input>(wire::decode(encoded))==input,"intent roundtrip");encoded[encoded.size()-7]=3;bool bad=false;try{wire::decode(encoded);}catch(const wire::Invalid&){bad=true;}check(bad,"invalid mount opcode");auto newer=input;newer.sequence=2;newer.mounted={};newer.fire=true;auto merged=wire::coalesce_input(input,newer);check(merged.mounted==input.mounted&&!merged.fire&&!merged.aiming,"coalesce preserves single action overfire");wire::encode(merged);
}
void service(){Service s(1);s.configuration(123);auto ws=weapons();s.configure(world(),ws);check(s.authority().configure_mounted(registry(),20),"service mount scene");const uint16_t gear[]{25};check(s.authority().join(a,1,pose(-600),1000,1000,gear,0),"service body");s.authority().active(true);s.admit(a);check(!s.receive(a,wire::encode(wire::Accept{1,122}),0),"mismatched config rejected");check(s.receive(a,wire::encode(wire::Accept{1,123}),0),"matching config accepted");wire::Input in;in.epoch=1;in.sequence=1;in.pose=pose(-600);in.weapon=25;in.mounted={mounted::Action::mount,1,1};check(s.receive(a,wire::encode(in),0),"service input");s.poll(0);check(s.authority().snapshot().players[a.slot]->mountedId==1,"service mount");in.sequence=2;in.mounted={};in.weapon=500;in.suspended=true;check(s.receive(a,wire::encode(in),100),"suspend input");s.poll(100);check(!s.authority().snapshot().players[a.slot]->mountedId,"menu release");}
void json(){auto path=std::filesystem::temp_directory_path()/"mgo2mt-mounted-fixture.json";const std::string value=R"({"version":1,"types":[{"id":"m2","name":"M2","weapon":500,"model":"data/m2.gwm","pivot":[0,1000,0],"muzzle":[0,1200,1000],"operatorOffset":[0,0,-600],"yawMin":-0.5,"yawMax":0.5,"pitchMin":-0.2,"pitchMax":0.3,"useRadius":1500,"infiniteAmmo":true}],"placements":[{"map":20,"id":1,"type":"m2","origin":[0,2,0],"yaw":0}]})";auto write=[&](std::string v){std::ofstream out(path);out<<v;};mounted::Registry r;std::string error;write(value);check(r.load(path,error)&&r.find(20,1)&&r.find("m2"),"strict JSON load");auto extras=value;extras.replace(extras.find("\"infiniteAmmo\":true"),19,"\"infiniteAmmo\":true,\"operatorOrbit\":true,\"ejection\":[0,100,200],\"ejectionDirection\":[1,0,0]");write(extras);check(r.load(path,error)&&r.types[0].operatorOrbit&&r.types[0].ejectionDirection==Vec3{1,0,0},"orbit and ejection JSON");auto badDirection=extras;badDirection.replace(badDirection.find("\"ejectionDirection\":[1,0,0]"),27,"\"ejectionDirection\":[2,0,0]");write(badDirection);check(!r.load(path,error),"nonunit ejection rejected");auto invalid=value;invalid.replace(invalid.find("data/m2.gwm"),11,"../evil.gwm");write(invalid);check(!r.load(path,error)&&r.find(20,1),"path escape rejected preservesold");write(value.substr(0,value.size()-1)+",\"oops\":0}");check(!r.load(path,error),"unknown field rejected");std::filesystem::remove(path);}
}
int main(){try{lifecycle();occlusion();collider();configured_ak();orbit();packets();service();json();std::cout<<"PASS mounted HOST authority, exact muzzle, cadence, inventory, lifecycle, collision-checked operator orbit, wire24 and JSON\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
