#include "render_lod.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <set>
#include <stdexcept>
#include <chrono>
using namespace mgo2mt;
namespace {
int checks=0;void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
CharacterModel grid(unsigned size=32){CharacterModel m;for(unsigned z=0;z<size;++z)for(unsigned x=0;x<size;++x)m.vertices.push_back({float(x)*10,0,float(z)*10,0,1,0,x*.002f,z*.002f});for(unsigned z=0;z+1<size;++z)for(unsigned x=0;x+1<size;++x){uint32_t a=z*size+x,b=a+size;m.indices.insert(m.indices.end(),{a,b,a+1,a+1,b,b+1});}m.parts.push_back({0,uint32_t(m.indices.size()),0,0});return m;}
struct V {double x,y,z;};V vec(const ModelVertex&v){return {v.x,v.y,v.z};}V sub(V a,V b){return {a.x-b.x,a.y-b.y,a.z-b.z};}V add(V a,V b){return {a.x+b.x,a.y+b.y,a.z+b.z};}V mul(V a,double b){return {a.x*b,a.y*b,a.z*b};}double dot(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}V cross(V a,V b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
double segmentDistance(V p,V a,V b){auto d=sub(b,a);double length=dot(d,d);auto v=sub(p,add(a,mul(d,length?std::clamp(dot(sub(p,a),d)/length,0.,1.):0.)));return dot(v,v);}
double triangleDistance(V p,V a,V b,V c){auto n=cross(sub(b,a),sub(c,a));double n2=dot(n,n);if(n2>1e-16){auto q=sub(p,mul(n,dot(sub(p,a),n)/n2));if(dot(cross(sub(b,a),sub(q,a)),n)>=-1e-10&&dot(cross(sub(c,b),sub(q,b)),n)>=-1e-10&&dot(cross(sub(a,c),sub(q,c)),n)>=-1e-10){auto d=sub(p,q);return dot(d,d);}}return std::min({segmentDistance(p,a,b),segmentDistance(p,b,c),segmentDistance(p,c,a)});}
double shapeAudit(const CharacterModel&m,const render_lod::Mesh&lod){double maximum=0;for(size_t part=0;part<lod.parts.size();++part)for(const auto*v:{&lod.parts[part].mid,&lod.parts[part].coarse}){if(v->indices.empty())continue;const auto&p=m.parts[part];const size_t samples=std::max(size_t(8),std::min(size_t(256),size_t(16000000)/v->indices.size()));auto measure=[&](V q){double best=std::numeric_limits<double>::infinity();for(size_t i=0;i<v->indices.size();i+=3)best=std::min(best,triangleDistance(q,vec(m.vertices[v->indices[i]]),vec(m.vertices[v->indices[i+1]]),vec(m.vertices[v->indices[i+2]])));if(std::sqrt(best)>v->maxError+.005)std::cerr<<"part="<<part<<" source="<<p.count/3<<" output="<<v->indices.size()/3<<" bound="<<v->maxError<<" measured="<<std::sqrt(best)<<" point="<<q.x<<","<<q.y<<","<<q.z<<"\n";check(std::sqrt(best)<=v->maxError+.005,"sampled original surface stays within measured displacement bound");maximum=std::max(maximum,std::sqrt(best));};for(size_t i=0;i<p.count;i+=std::max(size_t(3),(size_t(p.count)/(samples*3))*3)){auto a=vec(m.vertices[m.indices[p.first+i]]),b=vec(m.vertices[m.indices[p.first+i+1]]),c=vec(m.vertices[m.indices[p.first+i+2]]),n=cross(sub(b,a),sub(c,a));if(dot(n,n)<=1e-8)continue;measure(a);measure(b);measure(c);measure(mul(add(add(a,b),c),1./3));}}return maximum;}
void validate(const CharacterModel&m,const render_lod::Mesh&lod){for(size_t n=0;n<lod.parts.size();++n){const auto&p=m.parts[n];std::set<uint32_t>source(m.indices.begin()+p.first,m.indices.begin()+p.first+p.count);for(const auto*v:{&lod.parts[n].mid,&lod.parts[n].coarse}){check(v->indices.size()%3==0,"triangles");check(v->indices.size()<p.count||v->indices.empty(),"real triangle reduction");check(std::isfinite(v->maxError)&&v->maxError>=0,"finite measured error");for(auto id:v->indices)check(source.contains(id),"material boundary/source index retained");}}}
}
int main(int argc,char**argv){try{
 if(argc==2){std::ifstream f(argv[1],std::ios::binary|std::ios::ate);check(bool(f),"stage file");auto size=f.tellg();check(size>0&&size<=64*1024*1024,"stage bytes");std::vector<char>bytes(static_cast<size_t>(size));f.seekg(0);f.read(bytes.data(),size);CharacterModel m(bytes);auto begin=std::chrono::steady_clock::now();auto lod=render_lod::build(m);auto buildMs=std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-begin).count();validate(m,lod);auto sampledError=shapeAudit(m,lod);float error=0;size_t reduced=0;for(const auto&p:lod.parts){error=std::max({error,p.mid.maxError,p.coarse.maxError});reduced+=!p.mid.indices.empty()||!p.coarse.indices.empty();}std::cout<<"{\"vertices\":"<<m.vertices.size()<<",\"parts\":"<<m.parts.size()<<",\"sourceTriangles\":"<<lod.originalTriangles<<",\"midTriangles\":"<<lod.midTriangles<<",\"farTriangles\":"<<lod.farTriangles<<",\"reducedParts\":"<<reduced<<",\"maxError\":"<<error<<",\"sampledSurfaceError\":"<<sampledError<<",\"budgetExceeded\":"<<lod.budgetExceeded<<",\"buildMs\":"<<buildMs<<"}\n";return 0;}
 auto m=grid();auto originalVertices=m.vertices;auto originalIndices=m.indices;auto lod=render_lod::build(m);validate(m,lod);check(!lod.budgetExceeded&&lod.midTriangles<lod.originalTriangles/2&&lod.farTriangles<=lod.midTriangles,"grid actual triangle reduction");check(m.indices==originalIndices&&std::memcmp(m.vertices.data(),originalVertices.data(),m.vertices.size()*sizeof(ModelVertex))==0,"source vertices/indices immutable");
 check(shapeAudit(m,lod)<.0001,"planar grid surface retained exactly"); auto repeat=render_lod::build(m);check(repeat.parts[0].mid.indices==lod.parts[0].mid.indices&&repeat.parts[0].coarse.indices==lod.parts[0].coarse.indices,"deterministic generation");
 auto soup=m;soup.vertices.clear();soup.indices.clear();for(auto id:m.indices){soup.indices.push_back(uint32_t(soup.vertices.size()));soup.vertices.push_back(m.vertices[id]);}auto soupLod=render_lod::build(soup);validate(soup,soupLod);check(soupLod.midTriangles==lod.midTriangles&&soupLod.farTriangles==lod.farTriangles,"exact duplicate strip vertices reconstruct connectivity");
 auto seams=soup;for(size_t i=0;i<seams.vertices.size();++i)seams.vertices[i].u1+=float(i/3)*.0001f;auto seamLod=render_lod::build(seams);check(seamLod.midTriangles==seamLod.originalTriangles&&seamLod.farTriangles==seamLod.originalTriangles,"UV seams never welded");
 for(const auto*v:{&lod.parts[0].mid,&lod.parts[0].coarse}){std::set<uint32_t>used(v->indices.begin(),v->indices.end());for(unsigned z=0;z<32;++z)for(unsigned x=0;x<32;++x)if(x==0||z==0||x==31||z==31)check(used.contains(z*32+x),"boundary vertex preserved");for(size_t t=0;t<v->indices.size();t+=3){const auto&a=m.vertices[v->indices[t]],&b=m.vertices[v->indices[t+1]],&c=m.vertices[v->indices[t+2]];check((b.z-a.z)*(c.x-a.x)-(b.x-a.x)*(c.z-a.z)>0,"winding and nondegenerate triangles");}}
 auto alpha=m;alpha.parts[0].surfaceAlpha=1;auto protectedLod=render_lod::build(alpha);check(protectedLod.parts[0].protectedPart&&protectedLod.parts[0].mid.indices.empty()&&protectedLod.parts[0].coarse.indices.empty(),"transparent part protection");alpha=m;alpha.vertices[42].aa=.5f;check(render_lod::build(alpha).parts[0].protectedPart,"vertex alpha protection");
 auto split=m;uint32_t half=uint32_t(split.indices.size()/6)*3;split.parts={{0,half,0,0},{half,uint32_t(split.indices.size())-half,1,0}};auto splitLod=render_lod::build(split);validate(split,splitLod);check(splitLod.parts.size()==2,"separate material parts");
 auto component=m;uint32_t start=uint32_t(component.vertices.size());component.vertices.insert(component.vertices.end(),{{1000,0,0,0,1,0,0,0},{1001,0,0,0,1,0,0,0},{1000,1,0,0,1,0,0,0},{1000,0,1,0,1,0,0,0}});std::vector<uint32_t>tetra{start,start+2,start+1,start,start+1,start+3,start,start+3,start+2,start+1,start+2,start+3};component.indices.insert(component.indices.end(),tetra.begin(),tetra.end());component.parts[0].count=uint32_t(component.indices.size());auto componentLod=render_lod::build(component);for(const auto*v:{&componentLod.parts[0].mid,&componentLod.parts[0].coarse})check(std::search(v->indices.begin(),v->indices.end(),tetra.begin(),tetra.end())!=v->indices.end(),"small closed component not deleted");
 auto limited=render_lod::BuildOptions{};limited.maxVertices=10;check(render_lod::build(m,limited).budgetExceeded,"bounded mesh work");auto invalid=m;invalid.indices[0]=uint32_t(m.vertices.size());bool rejected=false;try{render_lod::build(invalid);}catch(...){rejected=true;}check(rejected,"invalid index rejection");invalid=m;invalid.vertices[0].x=std::numeric_limits<float>::quiet_NaN();rejected=false;try{render_lod::build(invalid);}catch(...){rejected=true;}check(rejected,"nonfinite source rejection");
 render_lod::Part p;p.radius=100;p.mid.indices={0,1,2};p.mid.maxError=10;float lo=110.1f,hi=1e7f;for(unsigned i=0;i<60;++i){float mid=(lo+hi)/2;if(render_lod::projected_error(p,p.mid,mid,1,720)>1.35f)lo=mid;else hi=mid;}check(render_lod::select(p,hi,1,720,0)==0&&render_lod::select(p,hi,1,720,1)==1,"hysteresis prevents threshold flicker");check(render_lod::select(p,101,1,720,1)==0,"near bounding sphere uses original");check(render_lod::select(p,-1,1,720)==0&&render_lod::select(p,hi,0,720)==0,"invalid projection original fallback");p.coarse.indices={0,1,2};p.coarse.maxError=30;check(render_lod::select(p,1e7f,1,720)==2,"coarse variant selection");check(render_lod::projected_error(p,p.coarse,1e7f,1,720)<=1.5f,"selected variant respects pixel bound");
 std::cout<<"PASS "<<checks<<" LOD boundary/material/alpha/component/source/error/hysteresis/budget checks; grid "<<lod.originalTriangles<<" -> "<<lod.midTriangles<<" -> "<<lod.farTriangles<<" triangles\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
