#include "character_screen.h"
#include <algorithm>
#include <iostream>
#include <fstream>
#include <stdexcept>
using namespace mgo2win;
void check(bool v,const char*s){if(!v)throw std::runtime_error(s);}
void put(std::vector<uint8_t>&b,size_t at,uint32_t v){for(unsigned i=0;i<4;++i)b[at+3-i]=uint8_t(v>>(8*i));}
LobbyPacket detail(){LobbyPacket p{0x4313,0,std::vector<uint8_t>(877)};put(p.payload,4,77);p.payload[8]='R';p.payload[24]='C';p.payload[154]=1;p.payload[234]=16;p.payload[235]=2;put(p.payload,372,123);p.payload[376]='H';put(p.payload,400,124);p.payload[404]='P';return p;}
LobbyPacket permission(){LobbyPacket p{0x4321,0,std::vector<uint8_t>(43)};const char*ip="192.0.2.1";std::copy_n(ip,strlen(ip),p.payload.begin()+4);std::copy_n(ip,strlen(ip),p.payload.begin()+22);p.payload[20]=0x16;p.payload[21]=0x67;p.payload[38]=0x16;p.payload[39]=0x67;return p;}
int main(int argc,char**argv){try{
 auto d=parse_room_detail(detail().payload,77);check(d.name==L"R"&&d.comment==L"C"&&d.capacity==16&&d.players==2&&d.roster.size()==2&&d.roster[0].id==123,"detail offsets and host slot");
 for(unsigned mode=0;mode<7;++mode){auto b=detail().payload;if(mode==0)b.pop_back();if(mode==1)put(b,4,78);if(mode==2)put(b,372,0);if(mode==3)put(b,400,123);if(mode==4)b[234]=19;if(mode==5)b[8]=255;if(mode==6)b[152]=2;bool bad=false;try{parse_room_detail(b,77);}catch(...){bad=true;}check(bad,"malformed detail rejected");}
 auto logical=room_join_payload(77,1,L"abc");check(logical.size()==21&&logical[3]==77&&logical[4]=='a'&&logical[7]==0&&logical[20]==1,"logical join layout");
 NetworkKeys keys;auto encrypted=room_action_wire_payload(keys,0x4320,logical);check(encrypted.size()==24,"encrypted join block extent");network_block(encrypted,keys.packet,false);check(std::equal(logical.begin(),logical.end(),encrypted.begin())&&encrypted[21]==0&&encrypted[22]==0&&encrypted[23]==0,"encrypted wire decrypts to padded original contract");
 for(auto password:{L"a",L"ab",L"abcdefghijklmnopq",L"abc\n",L"日本語日本語"}){bool bad=false;try{room_join_payload(77,1,password);}catch(...){bad=true;}check(bad,"password wire bounds");}check(room_join_payload(77,1,L"日本語").size()==21,"UTF8 password supported within byte limit");
 RoomAction a;a.event=RoomEvent::join;a.id=77;a.subtype=1;std::copy_n(L"abc",3,a.password.begin());std::atomic_bool guard=false,cancel=false;
 for(unsigned mode=0;mode<9;++mode){guard=false;unsigned calls=0;std::vector<uint16_t>commands;
  auto out=exchange_room_action(a,[&](uint16_t cmd,std::span<const uint8_t>b)->LobbyPacket{++calls;commands.push_back(cmd);if(cmd==0x4312){check(b.size()==4&&b[3]==77,"fresh detail ID");auto p=detail();if(mode==1)p.payload[235]=16;if(mode==2)p.payload[154]=2;if(mode==8)cancel=true;return p;}if(cmd==0x4320){check(guard&&b.size()==21&&b[20]==1,"guard before logical join");if(mode==3)return {0x4321,0,{0xc0,0xff,0xee,3}};if(mode==4)throw std::runtime_error("connection lost after send");auto p=permission();if(mode==5)p.payload.pop_back();if(mode==6)p.payload[4]='x';return p;}check(cmd==0x4322&&b.empty(),"provisional join explicitly released");if(mode==7)throw std::runtime_error("cleanup lost");return {0x4323,0,{0,0,0,0}};},guard,cancel);
  if(mode==0)check(out.join_status==RoomJoinStatus::permission_checked&&!guard&&commands==std::vector<uint16_t>({0x4312,0x4320,0x4322}),"permission is not game entry; reservation released");
  if(mode==1)check(calls==1&&out.error==0xc0ffee10&&!guard,"full room no join send");if(mode==2)check(calls==1&&!guard,"subtype drift no join send");if(mode==3)check(calls==2&&out.join_status==RoomJoinStatus::rejected&&!guard,"exact server rejection permits correction");
  if(mode>=4&&mode<=7&&mode!=6){check(guard&&out.join_status==RoomJoinStatus::outcome_unknown,"ambiguous state retained");auto retry=exchange_room_action(a,[&](uint16_t,std::span<const uint8_t>)->LobbyPacket{throw std::runtime_error("must not send");},guard,cancel);check(retry.join_status==RoomJoinStatus::outcome_unknown,"uncertain retry blocked");}
  if(mode==6)check(!guard&&out.join_status==RoomJoinStatus::host_protocol_error&&commands.back()==0x4322,"malformed endpoint never dialed; reservation released");
  if(mode==8)check(calls==1&&out.status==RoomStatus::cancelled&&!guard,"cancel after detail before join");cancel=false;
 }
 for(unsigned mode=0;mode<5;++mode){guard=false;cancel=false;std::vector<uint16_t>commands;
  auto out=exchange_room_action(a,[&](uint16_t cmd,std::span<const uint8_t>)->LobbyPacket{commands.push_back(cmd);if(cmd==0x4312)return detail();if(cmd==0x4320)return permission();if(cmd==0x4380){if(mode==4)throw std::runtime_error("leave acknowledgement lost");return {0x4381,0,{0,0,0,0}};}check(cmd==0x4322,"cleanup command");return {0x4323,0,{0,0,0,0}};},guard,cancel,[&](const host::Admission&admission){check(guard&&admission.character==123&&admission.endpoints[0].port==5735,"authenticated host endpoint handed to UDP adapter");host::Result r;r.stage=mode==0?host::Stage::timeout:mode==1?host::Stage::rejected:host::Stage::cancelled;r.profile_sent=mode>=2;r.was_joined=mode==3;return r;});
  check(commands.size()==(mode>=2?4:3),"profile send determines active-player cleanup");if(mode==4)check(guard&&out.join_status==RoomJoinStatus::outcome_unknown,"failed cleanup latches uncertain state");else check(!guard&&out.join_status==(mode==0?RoomJoinStatus::host_timeout:mode==1?RoomJoinStatus::host_rejected:RoomJoinStatus::host_cancelled),"host terminal error is preserved after cleanup");
 }
 // UI: first Enter opens details, a separate confirmation sends only once;
 // even repeated non-repeat events and Back cannot abandon an active send.
 CharacterScreen ui([](const std::atomic_bool&){CharacterReply r;r.status=CharacterStatus::success;r.list.slots=4;CharacterEntry e;e.id=123;e.name=L"PC";r.list.entries.push_back(e);return r;});
 ui.selection([](uint32_t,const std::atomic_bool&){CharacterSelectionReply r;r.status=CharacterSelectionStatus::success;r.request_may_have_been_sent=true;r.character.id=123;r.lobbies.push_back({7,5737,1,L"Lobby",0,2});return r;},std::make_shared<CharacterSelectionState>());
 std::atomic_bool release=false;std::atomic_uint joins=0;
 ui.rooms([&](uint32_t,const GameLobbyEntry&,const std::atomic_bool&stop,std::atomic_bool&,const RoomPublish&publish,RoomRequests&requests){RoomReply r;r.status=RoomStatus::ready;r.rooms.push_back({77,L"Room",2,16});publish(r);while(!stop){if(auto action=requests.take()){RoomReply out;out.event=action->event;out.requested_room=77;out.status=RoomStatus::ready;out.detail=d;if(action->event==RoomEvent::join){++joins;while(!release&&!stop)Sleep(1);out.join_status=RoomJoinStatus::permission_checked;}if(!stop)publish(out);}Sleep(1);}});
 auto spin=[&](auto predicate){auto end=GetTickCount64()+2000;while(!predicate()&&GetTickCount64()<end){ui.draw();Sleep(1);}check(predicate(),"UI deadline");};auto key=[&](WPARAM k){ui.message(nullptr,WM_KEYDOWN,k,0);};
 auto capture=[&](const char*name){if(argc<2)return;std::filesystem::path dir=argv[1];std::filesystem::create_directories(dir);BITMAPFILEHEADER file{};BITMAPINFOHEADER info{};info.biSize=sizeof(info);info.biWidth=1280;info.biHeight=-720;info.biPlanes=1;info.biBitCount=32;info.biSizeImage=1280*720*4;file.bfType=0x4d42;file.bfOffBits=sizeof(file)+sizeof(info);file.bfSize=file.bfOffBits+info.biSizeImage;auto pixels=ui.draw();std::ofstream out(dir/name,std::ios::binary);out.write(reinterpret_cast<const char*>(&file),sizeof(file));out.write(reinterpret_cast<const char*>(&info),sizeof(info));out.write(static_cast<const char*>(pixels),info.biSizeImage);check(bool(out),"capture write");};
 ui.draw();spin([&]{return !ui.busy();});key(VK_RETURN);spin([&]{return ui.lobby_visible();});key(VK_RETURN);spin([&]{return ui.room_count()==1;});key(VK_RETURN);spin([&]{return ui.room_detail_visible()&&!ui.room_detail_busy();});check(!joins,"opening detail does not join");capture("detail.bmp");key(VK_RETURN);key(VK_RETURN);key(VK_ESCAPE);spin([&]{return joins==1;});check(ui.room_detail_visible()&&ui.room_detail_busy(),"pending join prevents duplicate and back");release=true;spin([&]{return !ui.room_detail_busy();});check(ui.room_join_status()==RoomJoinStatus::permission_checked,"UI labels server permission only");capture("permission.bmp");key(VK_RETURN);check(joins==1,"no repeat after completed permission check");key(VK_ESCAPE);check(!ui.room_detail_visible()&&ui.room_visible(),"detail back preserves lobby session");
 d.password=true;key(VK_RETURN);spin([&]{return ui.room_detail_visible()&&!ui.room_detail_busy();});for(auto c:L"abc")if(c)ui.message(nullptr,WM_CHAR,c,0);capture("password.bmp");key(VK_ESCAPE);
 std::cout<<"room detail/join protocol and UI passed\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
