#include "round_items.h"
#include "combat_initial_profile.h"
#include "hold_inventory_bridge.h"
#include "combat_spawn_profile.h"
#include "stage_water.h"
#include "stage_profiles.h"
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <limits>
using namespace mgo2mt;
namespace {void check(bool v,const char*m){if(!v)throw std::runtime_error(m);}std::shared_ptr<const stage::Collision> floor(){return std::make_shared<const stage::Collision>(stage::Collision::make({{-20000,0,-20000},{20000,0,-20000},{20000,0,20000},{-20000,0,20000}},{{{0,1,2}},{{0,2,3}}}));}}
int main(int argc,char**argv){try{check(argc==3||argc==4,"catalog, output, optional real stage root arguments");items::DropPolicies catalog;std::string error;check(catalog.load(argv[1],error),"real catalog");items::RoundItems config;config.enabled=true;config.rules={{20,items::Domain::weapon,1,1,{}},{20,items::Domain::weapon,22,1,{}},{20,items::Domain::equipment,16,1,{}}};check(config.valid(),"required nondrop settings valid");items::RoundItems decoded;check(decoded.parse(config.serialize(),error)&&decoded.serialize()==config.serialize(),"config roundtrip");auto previous=decoded.serialize();for(auto bad:{"MGO2MT_ROUND_ITEMS 2\nenabled 1\n","MGO2MT_ROUND_ITEMS 1\nenabled 1\nitem 20 weapon 25 4097 spawn\n","MGO2MT_ROUND_ITEMS 1\nenabled 1\nitem 20 equipment 16 1 at nan 0 0 0\n","MGO2MT_ROUND_ITEMS 1\nenabled 1\nitem 20 weapon -1 1 spawn\n"})check(!decoded.parse(bad,error)&&decoded.serialize()==previous,"bad config atomic");
 std::filesystem::create_directories(argv[2]);auto path=std::filesystem::path(argv[2])/"round_items.cfg";check(config.save(path,error)&&decoded.load(path,error)&&decoded.serialize()==previous,"atomic disk roundtrip");auto invalid=config;invalid.rules[0].count=4097;check(!invalid.save(path,error)&&decoded.load(path,error)&&decoded.serialize()==previous,"invalid save keeps existing");
 combat::Authority a;auto profiles=combat::initial_profiles(20,1,0);auto collision=floor();a.begin(10,collision,profiles);a.item_policies(catalog);auto lookup=[&](auto d,auto id){return a.item_template(d,id);};std::array<stage::Vec3,3> anchors{{{0,2,650},{700,2,650},{-700,2,650}}};auto seeds=items::resolve_round_items(config,20,*collision,anchors,lookup);check(seeds.size()==3,"all requested nondrop items resolved");check(a.seed_items(seeds),"HOST seeds without drop authorization");auto before=a.item_state();check(before.entities.size()==3&&!a.seed_items(seeds)&&a.item_state().revision==before.revision,"one initial atomic batch");for(const auto&e:before.entities)check(e.kind==items::PlacementKind::round&&e.owner==items::Actor{},"neutral HOST owner");
 items::wire::Header header{{10,1},777,{1,100,1000,1},0};auto pages=items::wire::pages(before,header);check(pages&&pages->size()==1,"round items encode as rows");items::wire::Receiver receiver;receiver.bind(header,{64,64});check(receiver.receive(*items::wire::encode(pages->front()))&&receiver.state()->entities==before.entities,"neutral round ownership roundtrip");auto badPage=pages->front();badPage.entities[0].owner=header.actor;check(!items::wire::encode(badPage),"round cannot forge player owner");badPage=pages->front();badPage.entities[0].kind=items::PlacementKind::dropped;check(!items::wire::encode(badPage),"player drop cannot forge neutral owner");
 combat::Identity id{1,100,1000};combat::Pose p;p.feet={0,2,0};check(a.join(id,1,p,1000,1000,std::array<uint16_t,1>{25},0),"join after seeding");a.active(true);uint64_t sequence=0;
 auto request=[&](items::wire::Action action,uint8_t slot,uint64_t entity){auto held=*a.item_held(id,777);items::wire::Command c;c.header=held.header;c.header.sequence=++sequence;c.action=action;c.heldSlot=slot;c.heldRevision=held.slots[slot].revision;c.entity=entity;if(entity){auto state=a.item_state();auto it=std::find_if(state.entities.begin(),state.entities.end(),[&](auto&e){return e.key.id==entity;});check(it!=state.entities.end(),"requested existing entity");c.entityRevision=it->revision;}return a.item_action(id,c,1);};
 check(!bool(request(items::wire::Action::pickup,1,before.entities[0].key.id)),"initial knife prevents duplicate pickup");check(bool(request(items::wire::Action::pickup,2,before.entities[1].key.id)),"patriot picked into weapon slot");check(bool(request(items::wire::Action::pickup,3,before.entities[2].key.id)),"stealth picked into equipment slot");auto held=*a.item_held(id,777);check(held.slots[4].contents.item==1&&held.slots[2].contents.item==22&&held.slots[3].contents.domain==items::Domain::equipment&&held.selectedEquipment==3,"full slots correctly typed");check(a.item_state().entities.size()==1,"pickups remove placements once");
 items::DropPolicy denied;denied.drop=items::DropOverride::deny;check(a.item_policy(1,denied)&&a.item_policy(22,denied)&&a.item_policy(16,denied,items::Domain::equipment),"explicit nondrop policy");for(uint8_t slot:{4,2,3})check(request(items::wire::Action::drop,slot,0).code==items::ResultCode::policy,"HOST placement does not grant drop");check(bool(request(items::wire::Action::equip,4,0))&&a.snapshot().players[1]->weapon==1,"knife selection");auto knife=a.fire(id,{10,1,1,{0,0,1},1},2);check(bool(knife)&&a.snapshot().players[1]->ammo==0&&std::count_if(knife.events.begin(),knife.events.end(),[](const auto&e){return e.kind==combat::EventKind::shot&&e.weapon==1;})==1,"equipped knife has dedicated durable attack");check(bool(request(items::wire::Action::equip,2,0)),"unknown attack identity can be held");check(a.fire(id,{10,2,22,{0,0,1},1},2).reject==combat::Reject::weapon,"unknown attacks never rifle fallback");check(bool(request(items::wire::Action::equip,4,0)),"return to knife");check(bool(request(items::wire::Action::equip,3,0))&&a.snapshot().players[1]->weapon==1,"equipment selection preserves weapon");
 items::ClientState cs;cs.connection=1;cs.context={header.scope,header.actor,{},true};cs.status=items::ClientStatus::ready;cs.capabilities=items::wire::all_capabilities;cs.held=*a.item_held(id,777);auto view=hold_selection::inventory_snapshot(cs,true);check(view.eligible&&view.weapons.size()==3&&view.equipment.size()==1&&view.selectedEquipment==3,"LT and RT menus receive all holdings");auto bytes=items::wire::encode(*cs.held);check(bytes&&bytes->size()==220&&items::wire::decode(*bytes),"4 slot GWIV2");auto legacy=*bytes;legacy[5]=1;check(!items::wire::decode(legacy),"mixed GWIV1 rejected");
 items::WorldInventory atomic({3,0});check(atomic.reset({1,1}),"atomic fixture");auto broken=seeds;broken.back().position.x=std::numeric_limits<float>::infinity();check(!atomic.seed({1,1},broken)&&atomic.snapshot().empty()&&atomic.seed({1,1},seeds),"bad final seed rolls back whole batch");check(!atomic.seed({1,1},{}),"no second seed");check(atomic.reset({2,1})&&atomic.seed({2,1},seeds),"new round restores placements");
 auto emptyWorld=stage::Collision::make({},{});bool noFloor=false;try{items::resolve_round_items(config,20,emptyWorld,anchors,lookup);}catch(...){noFloor=true;}check(noFloor,"missing support rejects entire resolver");auto unknown=config;unknown.rules.push_back({20,items::Domain::weapon,65535,1,{}});bool unknownRejected=false;try{items::resolve_round_items(unknown,20,*collision,anchors,lookup);}catch(...){unknownRejected=true;}check(unknownRejected,"unregistered metadata rejected");
 // Equal numeric identifiers from different namespaces must never be substituted.
 bool mismatched=false;try{items::resolve_round_items(config,20,*collision,anchors,[&](auto d,auto id){auto value=lookup(d,id);if(value)value->domain=items::Domain::world_item;return value;});}catch(...){mismatched=true;}check(mismatched,"resolver rejects namespace substitution");
 auto wrongHeld=*cs.held;wrongHeld.slots[3].contents.domain=items::Domain::weapon;check(!items::wire::encode(wrongHeld),"gear slot rejects weapon namespace");wrongHeld=*cs.held;wrongHeld.slots[4].contents.domain=items::Domain::equipment;check(!items::wire::encode(wrongHeld),"weapon slot rejects equipment namespace");
 auto truncated=*bytes;truncated.resize(156);check(!items::wire::decode(truncated),"old three-slot extent with current version rejected");
 items::WorldInventory constrained({2,0});check(constrained.reset({1,1})&&!constrained.seed({1,1},seeds)&&constrained.snapshot().empty(),"capacity failure transfers nothing");check(constrained.configure({3,0})&&constrained.seed({1,1},seeds),"failed seed does not consume once-only generation");
 // Actual packaged GEOM and GCX spawn arrays, for all four maps and both rules.
 if(argc==4)for(const auto& profile:stage::runtime_profiles)for(uint8_t rule:{0,1}){
  const auto root=std::filesystem::path(argv[3]);std::ifstream geom(root/(std::string(profile.stage)+".collision.cfg"));check(bool(geom),"real stage collision available");auto real=std::make_shared<const stage::Collision>(stage::Collision::read(geom));auto movement=stage::movement_collision(real);
  std::ifstream spawnFile(root/(std::string(profile.stage)+(rule?".tdm-spawns-v2.cfg":".dm-spawns.cfg")));check(bool(spawnFile),"real stage spawns available");auto spawn=combat::spawn::StageProfile::read(spawnFile);check(spawn.stage()==profile.stage&&spawn.map()==profile.map&&spawn.rule()==rule,"real stage identity matches route");std::vector<stage::Vec3> originalAnchors;for(uint8_t team:{0,1,2})for(const auto& e:spawn.group(combat::spawn::Variant::normal,combat::spawn::Kind::initial,team))originalAnchors.push_back(e.position);
  auto perMap=config;for(auto& r:perMap.rules)r.map=profile.map;auto actual=items::resolve_round_items(perMap,profile.map,*movement,originalAnchors,lookup);check(actual.size()==3,"real stage resolves all nondrop placements");for(const auto& seed:actual){stage::Vec3 feet{seed.position.x,seed.position.y,seed.position.z};check(movement->clear(feet,{25,60,2}),"real placement capsule clear");auto origin=feet;origin[1]+=1;auto support=movement->ray(origin,{0,-1,0},20);check(support&&support->normal[1]>=.707f,"real placement supported by local floor");}
  std::cout<<profile.stage<<" rule "<<unsigned(rule)<<" original floor/spawn placements PASS\n";
 }
 std::cout<<"HOST round placement / nondrop isolation / neutral-owner wire / typed four holdings / safe-floor all-or-none / reset / atomic save PASS\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
