#include "shadow_renderer.h"
#include "character_renderer.h"
#include <DirectXMath.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <iostream>
#include <limits>
#include <set>
using namespace mgo2mt;using Microsoft::WRL::ComPtr;
namespace {
void check(bool v,const char* text){if(!v)throw std::runtime_error(text);}
void ok(HRESULT h){check(SUCCEEDED(h),"Shadow test GPU");}
std::vector<uint8_t> pixels(ID3D11Device*d,ID3D11DeviceContext*c,CharacterRenderer&r){ComPtr<ID3D11Resource> resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D> texture;ok(resource.As(&texture));D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> copy;ok(d->CreateTexture2D(&desc,nullptr,&copy));c->CopyResource(copy.Get(),texture.Get());D3D11_MAPPED_SUBRESOURCE map{};ok(c->Map(copy.Get(),0,D3D11_MAP_READ,0,&map));std::vector<uint8_t> p(size_t(desc.Width)*desc.Height*4);for(unsigned y=0;y<desc.Height;++y)std::copy_n(static_cast<uint8_t*>(map.pData)+y*map.RowPitch,desc.Width*4,p.data()+size_t(y)*desc.Width*4);c->Unmap(copy.Get(),0);return p;}
CharacterModel plane(float height,float radius,bool transparent=false){CharacterModel m;m.bounds={-radius,height,-radius,radius,height,radius};for(auto p:std::array<std::array<float,2>,4>{{{-radius,-radius},{radius,-radius},{radius,radius},{-radius,radius}}}){ModelVertex v{};v.x=p[0];v.y=height;v.z=p[1];v.ny=1;v.lr=v.lg=v.lb=.9f;v.lit=transparent?0.f:1.f;m.vertices.push_back(v);}m.indices={0,2,1,0,3,2};m.parts.push_back({0,6,0,0});m.textures.push_back(transparent?ModelTexture{4,4,11,{0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0}}:ModelTexture{4,4,9,{255,255,255,255,0,0,0,0}});return m;}
void planning(){
 shadows::Settings settings;settings.enabled=true;auto a=shadows::allocation(settings,64ull<<20);check(a.cascades==4&&a.resolution==2048&&a.bytes==(64ull<<20),"exact shadow allocation bytes");settings.resolution=8192;settings.cascades=6;a=shadows::allocation(settings,64ull<<20);check(a.reduced&&a.resolution==1024&&a.cascades==6,"extreme settings reduce resolution preserve cascade count");check(!shadows::allocation(settings,1).cascades,"unavailable minimum closed");settings.enabled=false;check(!shadows::allocation(settings,64ull<<20).bytes,"OFF no memory");settings.enabled=true;
 WorldView camera{{123,2345,-4567},{.1f,-.2f,1},16.f/9};const std::array<float,6> bounds{-20000,-1000,-20000,20000,20000,30000};
 for(float fov:{.15f,.4f,1.f,1.5f})for(unsigned count=2;count<=6;++count){camera.verticalFov=fov;settings.cascades=count;settings.resolution=2048;a=shadows::allocation(settings,256ull<<20);auto p=shadows::plan(camera,{.3f,-1,.2f},{.7f,.7f,.7f},bounds,settings,a);check(p.count==count&&p.splits[count-1]==60000,"requested cascade count and distance");for(unsigned i=1;i<count;++i)check(p.splits[i]>p.splits[i-1],"strict ordered splits");auto tiny=camera;tiny.eye[0]+=.0001f;check(shadows::plan(tiny,{.3f,-1,.2f},{.7f,.7f,.7f},bounds,settings,a).matrices==p.matrices,"subtexel camera movement stable matrices");
  using namespace DirectX;auto eye=XMVectorSet(camera.eye[0],camera.eye[1],camera.eye[2],1),forward=XMVector3Normalize(XMVectorSet(camera.direction[0],camera.direction[1],camera.direction[2],0)),right=XMVector3Normalize(XMVector3Cross(XMVectorSet(0,1,0,0),forward)),up=XMVector3Cross(forward,right);float begin=10;
  for(unsigned i=0;i<count;++i){XMFLOAT4X4 matrix;std::memcpy(&matrix,p.matrices[i].data(),64);for(float z:{begin,p.splits[i]})for(float x:{-1.f,1.f})for(float y:{-1.f,1.f}){auto point=eye+forward*z+right*(x*z*std::tan(camera.verticalFov*.5f)*camera.aspect)+up*(y*z*std::tan(camera.verticalFov*.5f));XMFLOAT3 q;XMStoreFloat3(&q,XMVector3TransformCoord(point,XMLoadFloat4x4(&matrix)));check(std::abs(q.x)<1&&std::abs(q.y)<1,"frustum corner including PCF padding");}begin=p.splits[i];}
 }
 settings.depthBias=std::numeric_limits<float>::quiet_NaN();check(!shadows::valid(settings),"nonfinite shadow settings rejected");
}
}
int main(){try{
 planning();ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;ok(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));auto floor=plane(0,12000),block=plane(1800,1000),alpha=plane(1800,1000,true);floor.parts={{0,3,0,0},{3,3,0,0}};CharacterRenderer ground(d.Get(),floor),occluder(d.Get(),block),transparent(d.Get(),alpha);ground.resize_target(d.Get(),640,360);
 WorldView camera{{-4000,4500,-7000},{.4f,-.45f,1},16.f/9};const std::array<float,3> direction{.7f,-1,.2f},sun{.7f,.7f,.7f};const std::array<float,6> bounds{-15000,-1000,-15000,15000,15000,15000};
 auto draw=[&](const shadows::Renderer* shadow,const EnvironmentLight* environment=nullptr){ground.render(c.Get(),0,false,&camera,nullptr,nullptr,{},nullptr,shadow,environment);return pixels(d.Get(),c.Get(),ground);};auto baseline=draw(nullptr);
 shadows::Renderer shadows;shadows::Settings settings;settings.enabled=true;settings.resolution=1024;settings.cascades=3;check(shadows.configure(d.Get(),settings),"allocate CSM");std::array<shadows::Caster,2> casters{{{&ground},{&occluder}}};check(shadows.render(c.Get(),camera,direction,sun,bounds,casters),"shadow pass");auto lit=draw(&shadows);size_t changed=0;for(size_t i=0;i<lit.size();i+=4){if(lit[i]!=baseline[i]){++changed;check(lit[i]<baseline[i]&&lit[i]>=80,"only directional component removed; ambient remains");}}check(changed>100,"caster actually shadows receiver");auto stats=shadows.statistics();check(stats.active&&stats.cascades==3&&stats.drawCalls==6&&stats.triangles==12,"real submitted draw and triangle counters");
 EnvironmentLight environment;environment.front=environment.back={.3f,.3f,.3f};environment.direct=sun;environment.direction=shadows.current_plan().direction;const auto actorLit=draw(nullptr,&environment),actorShadow=draw(&shadows,&environment);size_t actorChanged=0;for(size_t i=0;i<actorLit.size();i+=4)if(actorLit[i]!=actorShadow[i]){++actorChanged;check(actorShadow[i]>=76&&actorShadow[i]<actorLit[i],"CSM preserves actor hemisphere ambient");}check(actorChanged>100,"CSM connected with actor hemisphere");
 std::set<std::vector<uint8_t>> filtered;for(unsigned radius=0;radius<=2;++radius){settings.pcfRadius=radius;check(shadows.configure(d.Get(),settings)&&shadows.render(c.Get(),camera,direction,sun,bounds,casters),"PCF setting renders");filtered.insert(draw(&shadows));}check(filtered.size()==3,"each PCF kernel changes edge pixels");settings.pcfRadius=1;check(shadows.configure(d.Get(),settings),"restore PCF");
 check(shadows.render(c.Get(),camera,direction,{0,0,0},bounds,casters)&&draw(&shadows)==baseline,"no directional light never darkens ambient");
 casters[1].renderer=&transparent;check(shadows.render(c.Get(),camera,direction,sun,bounds,casters)&&draw(&shadows)==baseline,"fully transparent original BC3 cannot cast opaque shadow");
 casters[1].renderer=&occluder;for(auto&v:block.vertices)v.x+=3500;occluder.update_vertices(c.Get(),block.vertices);check(shadows.render(c.Get(),camera,direction,sun,bounds,casters)&&draw(&shadows)!=lit,"current posed vertex buffer changes shadow");
 check(shadows.render(c.Get(),camera,direction,sun,bounds,{})&&draw(&shadows)==baseline,"empty new scene clears stale shadows");settings.visualize=true;check(shadows.configure(d.Get(),settings)&&shadows.render(c.Get(),camera,direction,sun,bounds,casters)&&draw(&shadows)!=baseline,"cascade diagnostic is connected");
 settings.enabled=false;check(shadows.configure(d.Get(),settings)&&draw(&shadows)==baseline&&!shadows.statistics().allocatedBytes,"OFF frees depth and restores exact Legacy pixels");
 settings.enabled=true;settings.resolution=8192;settings.cascades=6;check(shadows.configure(d.Get(),settings)&&shadows.statistics().reduced&&shadows.statistics().allocatedBytes<=(256ull<<20),"GPU capacity fallback allocates bounded map");check(shadows.render(c.Get(),camera,direction,sun,bounds,casters)&&shadows.statistics().drawCalls==12,"all six array slices submitted");check(!shadows.render(c.Get(),camera,{0,0,0},sun,bounds,casters)&&draw(&shadows)==baseline,"failed frame cannot sample old shadow maps");
 ComPtr<ID3D11Device> oldDevice;ComPtr<ID3D11DeviceContext> oldContext;const D3D_FEATURE_LEVEL requested=D3D_FEATURE_LEVEL_10_0;ok(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,&requested,1,D3D11_SDK_VERSION,&oldDevice,&level,&oldContext));CharacterRenderer legacy(oldDevice.Get(),floor);legacy.resize_target(oldDevice.Get(),640,360);legacy.render(oldContext.Get(),0,false,&camera);auto oldPixels=pixels(oldDevice.Get(),oldContext.Get(),legacy);check(std::any_of(oldPixels.begin(),oldPixels.end(),[](auto p){return p>0;}),"feature level 10 retains Legacy shader");mgo2mt::shadows::Renderer oldShadow;check(!oldShadow.configure(oldDevice.Get(),settings)&&!oldShadow.depth_view(),"unsupported feature level refuses CSM");settings.enabled=false;check(oldShadow.configure(oldDevice.Get(),settings),"unsupported hardware accepts OFF");
 std::cout<<"CSM PASS: stable fitting, 2-6 cascades, memory fallback, PCF shadows, ambient preservation, alpha, posed geometry, reset, exact OFF; changed="<<changed<<'\n';return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
