#include "sop_visuals.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
using namespace mgo2win;using Microsoft::WRL::ComPtr;
namespace {
void check(bool b,const char*why){if(!b)throw std::runtime_error(why);}
void ok(HRESULT h){check(SUCCEEDED(h),"SOP WARP test failure");}
using Pixels=std::vector<uint8_t>;
Pixels capture(ID3D11Device*d,ID3D11DeviceContext*c,const CharacterRenderer&r){
 ComPtr<ID3D11Resource> resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D> texture;ok(resource.As(&texture));D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> staging;ok(d->CreateTexture2D(&desc,nullptr,&staging));c->CopyResource(staging.Get(),texture.Get());
 D3D11_MAPPED_SUBRESOURCE map{};ok(c->Map(staging.Get(),0,D3D11_MAP_READ,0,&map));Pixels pixels(616*392*4);for(size_t y=0;y<392;++y)std::copy_n(static_cast<uint8_t*>(map.pData)+y*map.RowPitch,616*4,pixels.data()+y*616*4);c->Unmap(staging.Get(),0);return pixels;
}
void bitmap(const std::filesystem::path&p,const Pixels&rgba){if(p.empty())return;auto bgra=rgba;for(size_t i=0;i<bgra.size();i+=4)std::swap(bgra[i],bgra[i+2]);BITMAPFILEHEADER f{};BITMAPINFOHEADER b{};b.biSize=40;b.biWidth=616;b.biHeight=-392;b.biPlanes=1;b.biBitCount=32;b.biSizeImage=DWORD(bgra.size());f.bfType=0x4d42;f.bfOffBits=sizeof(f)+sizeof(b);f.bfSize=f.bfOffBits+b.biSizeImage;std::ofstream out(p,std::ios::binary);out.write(reinterpret_cast<const char*>(&f),sizeof(f));out.write(reinterpret_cast<const char*>(&b),sizeof(b));out.write(reinterpret_cast<const char*>(bgra.data()),bgra.size());check(bool(out),"SOP BMP write");}
std::vector<char> read(const std::filesystem::path&p){std::ifstream in(p,std::ios::binary);check(bool(in),"SOP original input");return {(std::istreambuf_iterator<char>(in)),{}};}
size_t difference(const Pixels&a,const Pixels&b){size_t n=0;check(a.size()==b.size(),"pixel extent");for(size_t i=0;i<a.size();i+=4)if(!std::equal(a.begin()+i,a.begin()+i+4,b.begin()+i))++n;return n;}
CharacterModel panel(float z=1500,float extent=5000){CharacterModel m;m.bounds={-extent,-extent,z,extent,extent,z};for(auto xy:std::array<std::array<float,2>,4>{{{-extent,-extent},{extent,-extent},{extent,extent},{-extent,extent}}}){ModelVertex v{};v.x=xy[0];v.y=xy[1];v.z=z;v.nz=-1;v.lr=.1f;v.lg=.15f;v.lb=.3f;v.lit=1;m.vertices.push_back(v);}m.indices={0,1,2,0,2,3};m.parts.push_back({0,6,0,0});m.textures.push_back({4,4,9,{255,255,255,255,0,0,0,0}});return m;}
PreparedCharacter fixture(){PreparedCharacter b;constexpr uint32_t keys[]={0xa89233,0x7011c4,0x6c02b2,0xf8d3cc,0xf5d387,0x019543,0x027a4c,0xfafa8b,0xfbfa42,0x619d43,0x62824c,0x5b028c,0x5c0243,0x449d08,0xf7f0c4,0xfb4232,0xf81206,0x459d14,0xfaf104,0x5b4a33,0xfb1246};constexpr sop::Vec3 p[]={{0,850,0},{0,1000,0},{0,1150,0},{0,1400,0},{0,1500,0},{-120,1250,0},{-220,1250,0},{-430,1120,0},{-620,1000,0},{120,1250,0},{220,1250,0},{430,1120,0},{620,1000,0},{-120,830,0},{-130,440,0},{-130,80,0},{-130,60,180},{120,830,0},{130,440,0},{130,80,0},{130,60,180}};for(unsigned i=0;i<21;++i)b.bonePositions[keys[i]]=p[i];return b;}
}
int main(int argc,char**argv){try{
 std::filesystem::path out=argc>1?argv[1]:"";if(!out.empty())std::filesystem::create_directories(out);
 for(unsigned mask=0;mask<16;++mask)check(sop::eligible({bool(mask&1),bool(mask&2),bool(mask&4),bool(mask&8)})==(mask==7),"fail-closed linked friendly alive unjammed gate");
 auto body=fixture();auto mesh=sop::doll_mesh(body);check(mesh&&mesh->vertices.size()==1040&&mesh->indices.size()==5616,"bounded 13-piece native doll");auto bad=body;bad.bonePositions.erase(0x5b4a33);check(!sop::doll_mesh(bad),"missing bone rejects full doll");bad=body;bad.bonePositions.begin()->second[0]=std::numeric_limits<float>::quiet_NaN();check(!sop::doll_mesh(bad),"nonfinite bone rejected");
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;ok(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));
 sop::Renderer overlay(d.Get());sop::Gate gate{true,true,true,false};auto wallModel=panel();CharacterRenderer wall(d.Get(),wallModel);WorldView view{{0,900,0},{0,0,1}};sop::Vec3 origin{0,0,2600};
 auto base=[&]{wall.render(c.Get(),0,false,&view);return capture(d.Get(),c.Get(),wall);};auto baseline=base();
 for(unsigned mask=0;mask<16;++mask)if(mask!=7){sop::Gate no{bool(mask&1),bool(mask&2),bool(mask&4),bool(mask&8)};check(!overlay.doll(c.Get(),body,wall,view,origin,0,no)&&capture(d.Get(),c.Get(),wall)==baseline,"forbidden doll leaves target identical");check(!overlay.scan(c.Get(),wall,view,{{0,0,0},1600,500,.5f},no)&&capture(d.Get(),c.Get(),wall)==baseline,"forbidden scan leaves target identical");}
 check(overlay.doll(c.Get(),body,wall,view,origin,0,gate),"linked doll through wall");auto doll=capture(d.Get(),c.Get(),wall);check(difference(baseline,doll)>1500,"visible wall-occluded doll silhouette");
 // No part-overlap brightening: the mask composes each covered pixel once.
 unsigned minR=255,maxR=0;for(size_t i=0;i<doll.size();i+=4)if(doll[i]!=baseline[i]){minR=std::min(minR,unsigned(doll[i]));maxR=std::max(maxR,unsigned(doll[i]));check(doll[i]>doll[i+1]&&doll[i+1]>doll[i+2],"orange native tint");}check(maxR-minR<=1,"uniform alpha despite joint/capsule overlap");
 auto behindModel=panel(3000,800);for(auto&v:behindModel.vertices){v.lr=1;v.lg=0;v.lb=0;}CharacterRenderer behind(d.Get(),behindModel);behind.render(c.Get(),0,false,&view,&wall);check(capture(d.Get(),c.Get(),wall)==doll,"doll leaves original world depth unchanged");
 check(!overlay.doll(c.Get(),bad,wall,view,origin,0,gate)&&capture(d.Get(),c.Get(),wall)==doll,"bad pose leaves target untouched");
 base();overlay.doll(c.Get(),body,wall,view,{450,0,2600},.7f,gate);check(difference(doll,capture(d.Get(),c.Get(),wall))>1000,"doll follows actor position and yaw");
 base();check(overlay.scan(c.Get(),wall,view,{{0,900,0},1600,500,.4f},gate),"world scan draw");auto scan=capture(d.Get(),c.Get(),wall);check(difference(scan,baseline)>1000,"scan is visible on stage geometry");base();overlay.scan(c.Get(),wall,view,{{0,900,0},2400,200,.4f},gate);auto scan2=capture(d.Get(),c.Get(),wall);check(difference(scan,scan2)>1000,"scan radius advances in world coordinates");
 // Retain stage transparency/depth holes: the mirrored alpha test cannot create
 // a surface where the ordinary pass discarded an alpha-tested texel.
 auto transparentModel=panel();for(auto&v:transparentModel.vertices)v.lit=0;transparentModel.textures[0].pixels={0,0,0,0,255,255,255,255};CharacterRenderer transparent(d.Get(),transparentModel);transparent.render(c.Get(),0,false,&view);auto transparentBase=capture(d.Get(),c.Get(),transparent);overlay.scan(c.Get(),transparent,view,{{0,900,0},1600,500,.4f},gate);check(capture(d.Get(),c.Get(),transparent)==transparentBase,"scan does not fill alpha-cutout holes");
 base();check(!overlay.scan(c.Get(),wall,view,{{0,0,0},-1,500,.4f},gate)&&capture(d.Get(),c.Get(),wall)==baseline,"invalid scan no target changes");check(base()==baseline,"normal renderer exact after SOP pass");
 if(!out.empty()){bitmap(out/"wall-baseline.bmp",baseline);bitmap(out/"doll-through-wall.bmp",doll);bitmap(out/"scan-near.bmp",scan);bitmap(out/"scan-far.bmp",scan2);}
 if(argc>=3){CharacterCatalog catalog(read(argv[2]));for(unsigned gender=0;gender<2;++gender){std::array<uint8_t,28> a{};a[0]=uint8_t(gender);a[2]=11;a[3]=22;a[15]=46;a[17]=57;auto original=catalog.assemble(a);catalog.pose(original,.1);auto rig=sop::doll_mesh(original);check(bool(rig),"original rig doll");float low=1e9f,high=-1e9f;for(auto p:rig->vertices){low=std::min(low,p[1]);high=std::max(high,p[1]);}auto rigView=view;rigView.eye[1]=(low+high)*.5f;wall.render(c.Get(),0,false,&rigView);overlay.doll(c.Get(),original,wall,rigView,origin,0,gate);auto before=capture(d.Get(),c.Get(),wall);catalog.pose(original,.6);wall.render(c.Get(),0,false,&rigView);overlay.doll(c.Get(),original,wall,rigView,origin,0,gate);auto after=capture(d.Get(),c.Get(),wall);check(difference(before,after)>50,"doll follows actual animated bones");if(!out.empty())bitmap(out/("original-rig-"+std::to_string(gender)+".bmp"),after);}}
 if(argc>=4){for(const auto*stage:{"n001a","n004a","n022a","n023a"}){auto path=std::filesystem::path(argv[3])/(std::string(stage)+".gwm");CharacterModel model(read(path));CharacterRenderer renderer(d.Get(),model);std::ifstream spawnFile(std::filesystem::path(argv[3])/(std::string(stage)+".tdm-spawns-v2.cfg"));std::string line,token;std::getline(spawnFile,line);unsigned ignored=0;sop::Vec3 center{};spawnFile>>token>>ignored>>ignored>>ignored>>ignored>>token>>center[0]>>center[1]>>center[2];check(bool(spawnFile),"original spawn camera reference");WorldView camera{center,{0,-.6f,1}};camera.eye[1]+=6000;camera.eye[2]-=8000;renderer.render(c.Get(),0,false,&camera);auto before=capture(d.Get(),c.Get(),renderer);check(overlay.scan(c.Get(),renderer,camera,{center,7000,3000,.35f},gate),"four-stage world scan");auto after=capture(d.Get(),c.Get(),renderer);check(difference(before,after)>10,"actual stage geometry receives scan");renderer.render(c.Get(),0,false,&camera);check(capture(d.Get(),c.Get(),renderer)==before,"actual stage colors restored exactly");if(!out.empty()){bitmap(out/(std::string(stage)+"-baseline.bmp"),before);bitmap(out/(std::string(stage)+"-scan.bmp"),after);}}}
 std::cout<<"SOP visuals PASS: gates, bone capsule doll, wall xray, uniform alpha, world-depth preservation, scan geometry/cutouts, restore, optional original rigs/four stages\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
