#include "gekko_test_profiles.h"
#include "combat_service.h"
#include "host_special_pc.h"
#include "remote_avatar.h"
#include "combat_initial_profile.h"
#include <iostream>
#include <stdexcept>
#include <cmath>
using namespace mgo2mt;using namespace mgo2mt::combat;
namespace {
void check(bool b,const char* s){if(!b)throw std::runtime_error(s);}
Identity id(unsigned n){return {uint8_t(n),uint16_t(n+1),100+n};}
std::shared_ptr<stage::Collision> scene(bool wall=false,bool ceiling=false){std::vector<stage::Vec3>v{{-100000,0,-100000},{-100000,0,100000},{100000,0,100000},{100000,0,-100000}};std::vector<stage::CollisionTriangle>t{{{0,1,2}},{{0,2,3}}};if(wall){v.insert(v.end(),{{-10000,0,1100},{10000,0,1100},{10000,10000,1100},{-10000,10000,1100}});t.push_back({{4,5,6}});t.push_back({{4,6,7}});}if(ceiling){auto n=unsigned(v.size());v.insert(v.end(),{{-10000,2500,-10000},{10000,2500,-10000},{10000,2500,10000},{-10000,2500,10000}});t.push_back({{n,n+1,n+2}});t.push_back({{n,n+2,n+3}});}return std::make_shared<stage::Collision>(stage::Collision::make(std::move(v),std::move(t)));}
Pose pose(float x=0,float z=0,float yaw=0){return {{x,2,z},yaw,0,{260,1700,2}};}
Weapon gun(){Weapon w;w.id=23;w.damage=100;w.intervalMs=100;w.reloadMs=500;w.magazine=30;w.reserve=60;w.range=20000;return w;}
void joined(Authority&h,unsigned n,Pose p,uint8_t team=1){check(h.join(id(n),team,p,1000,1000,std::array<uint16_t,1>{23},0),"join");}
void authority(){
 Authority h;h.begin(8,scene(),gekko_test_profiles(gun()));joined(h,0,pose());joined(h,1,pose(0,1800),2);h.active(true);
 check(h.assign_special(id(0),special_pc::Kind::gekko,false,1)==Reject::none,"HOST form assignment");auto p=*h.snapshot().players[0];check(p.specialPc.kind==special_pc::Kind::gekko&&!p.specialPc.nameVisible&&p.hp==1000&&p.maxHp==1000&&p.stamina==5000&&p.pose.capsule.radius==800,"native form vitals and size");
 check(h.fire(id(0),{8,1,23,{0,0,1}},1).reject==Reject::weapon&&h.reload(id(0),8,1).reject==Reject::unavailable&&p.weapon==128&&p.ammo==1000,"ordinary firearm blocked");
 check(h.pose(id(0),8,1,p.pose,100)==Reject::none,"form pose");check(h.special_action(id(0),8,1,{special_pc::Action::kick,1},100)==Reject::none,"kick admitted");
 auto turned=p.pose;turned.yaw=1;check(h.pose(id(0),8,2,turned,101)==Reject::unavailable,"action direction locked");
 check(h.special_action(id(0),8,1,{special_pc::Action::kick,1},100)==Reject::sequence,"duplicate edge rejected");
 check(h.advance_special_pc(100+special_pc::native_gekko.kickHitMs-1).events.empty(),"before impact no damage");
 auto action=h.advance_special_pc(100+special_pc::native_gekko.kickHitMs);check(action.events.size()==1&&action.events[0].kind==EventKind::damage&&h.snapshot().players[1]->hp==600,"HOST kick damage once");
 check(h.advance_special_pc(100+special_pc::native_gekko.kickHitMs+1).events.empty(),"held action cannot repeat damage");h.advance_special_pc(100+special_pc::native_gekko.kickMs);
 p=*h.snapshot().players[0];check(p.specialPc.action==special_pc::Action::none,"kick ends");check(h.assign_special(id(0),special_pc::Kind::human,true,2300)==Reject::none&&h.assign_special(id(0),special_pc::Kind::gekko,true,2301)==Reject::none,"reassign same life");
 p=*h.snapshot().players[0];check(h.sop_view(id(0))->specialPcRequest==0&&h.pose(id(0),8,2,p.pose,2400)==Reject::none&&h.special_action(id(0),8,2,{special_pc::Action::jump,1},2400)==Reject::none,"new form request counter restarts");
 float peak=0;for(unsigned t=0;t<=special_pc::native_gekko.jumpMs;t+=25){h.advance_special_pc(2400+t);peak=std::max(peak,h.snapshot().players[0]->pose.feet[1]);}h.advance_special_pc(2400+special_pc::native_gekko.jumpMs);check(peak>9900&&h.snapshot().players[0]->pose.feet[1]<5,"native10m curve jump returns to ground");
 const uint64_t second=2500+special_pc::native_gekko.jumpMs;p=*h.snapshot().players[0];check(h.pose(id(0),8,3,p.pose,second)==Reject::none&&h.special_action(id(0),8,3,{special_pc::Action::jump,2},second)==Reject::none,"second jump");h.advance_special_pc(second+1400);check(h.snapshot().players[0]->pose.feet[1]>500,"jump rises");const auto cancelledFeet=h.snapshot().players[0]->pose.feet;h.active(false);check(h.snapshot().players[0]->specialPc.action==special_pc::Action::none&&h.snapshot().players[0]->pose.feet==cancelledFeet,"inactive cancels without teleporting airborne pose");
 check(h.special_action(id(0),9,3,{special_pc::Action::jump,3},second+1500)==Reject::generation&&h.special_action(id(0),8,3,{special_pc::Action::jump,3},second+1500,2)==Reject::generation,"epoch and life reject");
 Authority low;low.begin(1,scene(false,true),gekko_test_profiles(gun()));joined(low,0,pose());check(low.assign_special(id(0),special_pc::Kind::gekko,true,0)==Reject::obstructed&&low.snapshot().players[0]->hp==1000,"low ceiling fails without partial mutation");
 Authority blocked;blocked.begin(1,scene(true),gekko_test_profiles(gun()));joined(blocked,0,pose());joined(blocked,1,pose(0,1800),2);blocked.active(true);check(blocked.assign_special(id(0),special_pc::Kind::gekko,true,0)==Reject::none,"wall safe form");p=*blocked.snapshot().players[0];check(blocked.pose(id(0),1,1,p.pose,100)==Reject::none&&blocked.special_action(id(0),1,1,{special_pc::Action::kick,1},100)==Reject::none,"wall kick");check(blocked.advance_special_pc(100+special_pc::native_gekko.kickHitMs).events.empty()&&blocked.snapshot().players[1]->hp==1000,"real wall blocks kick");
 for(float lateral:{859.f,861.f}){Authority side;side.begin(1,scene(),gekko_test_profiles(gun()));joined(side,0,pose());joined(side,1,pose(lateral,2400),2);side.active(true);check(side.assign_special(id(0),special_pc::Kind::gekko,true,0)==Reject::none,"side fixture form");p=*side.snapshot().players[0];check(side.pose(id(0),1,1,p.pose,100)==Reject::none&&side.special_action(id(0),1,1,{special_pc::Action::kick,1},100)==Reject::none,"side kick");check(side.advance_special_pc(999).events.empty(),"900ms strike not early");auto hit=side.advance_special_pc(1000);check((side.snapshot().players[1]->hp<1000)==(lateral<860),"kick half-width plus target radius boundary");if(!hit.events.empty()){auto frame=wire::Frame{side.snapshot(),wire::Status::active,hit.events,side.sop_view(id(0)).value()};check(std::get<wire::Frame>(wire::decode(wire::encode(frame)))==frame,"native melee event encodes with life IDs");}}
}
void operator_control(){
 Authority h;h.begin(8,scene(),gekko_test_profiles(gun()));joined(h,0,pose());joined(h,1,pose(5000));special_pc::Control control;std::array ids{id(0),id(1)};control.roster(ids);control.configure({true,false,true});check(control.apply(h,0),"random control update");auto v=control.state();check(std::count_if(v.players.begin(),v.players.end(),[](auto&p){return p.current==special_pc::Kind::gekko;})==1,"one random winner");
 check(control.assign(8,id(0),special_pc::Kind::gekko)&&control.assign(8,id(1),special_pc::Kind::gekko)&&control.apply(h,1),"explicit duplicate kinds allowed");check(h.snapshot().players[0]->specialPc.kind==special_pc::Kind::gekko&&h.snapshot().players[1]->specialPc.kind==special_pc::Kind::gekko,"both transformed");
 check(!control.assign(9,id(0),special_pc::Kind::human)&&!control.assign(8,{0,90,100},special_pc::Kind::human),"operator stale full context rejected");control.configure({false,true,false});control.apply(h,2);check(h.snapshot().players[0]->specialPc.kind==special_pc::Kind::human&&h.snapshot().players[1]->specialPc.kind==special_pc::Kind::human,"disabled returns to human");
 control.configure({true,true,false});control.apply(h,3);check(h.snapshot().players[0]->specialPc.kind==special_pc::Kind::gekko,"explicit choice retained");h.begin(9,scene(),gekko_test_profiles(gun()));control.apply(h,4);joined(h,0,pose());control.apply(h,5);check(h.snapshot().players[0]->specialPc.kind==special_pc::Kind::gekko,"same connected identity survives round epoch");control.roster({});h.leave(id(0));control.apply(h,6);check(!control.assign(9,id(0),special_pc::Kind::gekko),"departed identity not selectable");
 Authority deferred;deferred.begin(1,scene(),gekko_test_profiles(gun()));joined(deferred,0,pose());deferred.active(true);special_pc::Control delayed;delayed.roster(std::array{id(0)});delayed.configure({true,true,true});delayed.apply(deferred,0);auto p=*deferred.snapshot().players[0];check(deferred.pose(id(0),1,1,p.pose,100)==Reject::none&&deferred.special_action(id(0),1,1,{special_pc::Action::jump,1},100)==Reject::none,"disable during jump setup");delayed.configure({false,true,true});delayed.apply(deferred,100);check(deferred.snapshot().players[0]->specialPc.kind==special_pc::Kind::gekko,"active action finishes before form change");deferred.advance_special_pc(100+special_pc::native_gekko.jumpMs);delayed.apply(deferred,100+special_pc::native_gekko.jumpMs);check(deferred.snapshot().players[0]->specialPc.kind==special_pc::Kind::human,"disabled permission retried when action finishes");
 special_pc::Control lottery;lottery.roster(ids);lottery.configure({true,true,true});for(uint64_t epoch:{21,22}){Authority round;round.begin(epoch,scene(),gekko_test_profiles(gun()));joined(round,0,pose());joined(round,1,pose(5000));lottery.apply(round,0);const auto winner=weapon_accuracy::mix(epoch^id(0).character)<weapon_accuracy::mix(epoch^id(1).character)?0:1;check(round.snapshot().players[winner]->specialPc.kind==special_pc::Kind::gekko&&round.snapshot().players[1-winner]->specialPc.kind==special_pc::Kind::human,"lottery re-evaluated at each epoch");}check(lottery.assign(22,id(0),special_pc::Kind::gekko)&&!lottery.state().config.random,"direct operator choice switches random off");
 Authority later;later.begin(30,scene(),gekko_test_profiles(gun()));special_pc::Control waitWinner;waitWinner.roster(ids);waitWinner.configure({true,true,true});const auto winner=weapon_accuracy::mix(30^id(0).character)<weapon_accuracy::mix(30^id(1).character)?0u:1u;joined(later,1-winner,pose(float((1-winner)*5000)));waitWinner.apply(later,0);check(later.snapshot().players[1-winner]->specialPc.kind==special_pc::Kind::human,"earlier spawn cannot steal roster lottery");joined(later,winner,pose(float(winner*5000)));waitWinner.apply(later,1);check(later.snapshot().players[winner]->specialPc.kind==special_pc::Kind::gekko,"unspawned lottery winner applied on later spawn");
 auto low=scene(false,true);for(auto&vertex:low->vertices)if(vertex[1]==2500)vertex[1]=1200;later.world(std::make_shared<stage::Collision>(stage::Collision::make(low->vertices,low->triangles)));waitWinner.configure({false,true,true});waitWinner.apply(later,2);check(later.snapshot().players[winner]->specialPc.kind==special_pc::Kind::gekko,"new geometry blocks unsafe normal transition");later.world(scene());waitWinner.apply(later,3);check(later.snapshot().players[winner]->specialPc.kind==special_pc::Kind::human,"normal transition retries when obstruction clears");
}
void landing_on_peer(){for(bool cancel:{false,true}){Authority h;h.begin(1,scene(),gekko_test_profiles(gun()));joined(h,0,pose());h.active(true);check(h.assign_special(id(0),special_pc::Kind::gekko,true,0)==Reject::none,"landing form");auto p=*h.snapshot().players[0];check(h.pose(id(0),1,1,p.pose,100)==Reject::none&&h.special_action(id(0),1,1,{special_pc::Action::jump,1},100)==Reject::none,"landing jump");h.advance_special_pc(1500);check(h.snapshot().players[0]->pose.feet[1]>600,"space below jumper");auto prone=pose();prone.capsule={260,560,2};joined(h,1,prone,2);if(cancel)h.active(false);else h.advance_special_pc(100+special_pc::native_gekko.jumpMs);check(h.snapshot().players[0]->pose.feet[1]>=562&&h.snapshot().players[1]->pose.feet[1]==2,"normal or cancelled landing stops above prone participant");}}
void stunned_death(){auto weapon=gun();weapon.damage=600;weapon.staminaDamage=1000;Authority h;h.begin(1,scene(),gekko_test_profiles(weapon));joined(h,0,pose());joined(h,1,pose(0,1800),2);joined(h,2,pose(0,6000,3.14159265f));h.active(true);check(h.assign_special(id(0),special_pc::Kind::gekko,true,0)==Reject::none,"stun form");check(h.pose(id(2),1,1,pose(0,6000,3.14159265f),100)==Reject::none&&bool(h.fire(id(2),{1,1,23,{0,0,-1}},100)),"stun victim shot");check(h.snapshot().players[1]->stunned&&h.snapshot().players[1]->hp==400,"stunned living victim");auto p=*h.snapshot().players[0];check(h.pose(id(0),1,1,p.pose,100)==Reject::none&&h.special_action(id(0),1,1,{special_pc::Action::kick,1},100)==Reject::none,"finishing kick");auto d=h.advance_special_pc(1000);check(d.events.size()==2&&!h.snapshot().players[1]->alive&&!h.snapshot().players[1]->stunned,"kick death canonical flags");wire::Frame frame{h.snapshot(),wire::Status::active,d.events,h.sop_view(id(0)).value()};check(std::get<wire::Frame>(wire::decode(wire::encode(frame)))==frame,"stunned death remains transmissible");}
void wire_and_service(){
 Service service(8,Policy{false,6000,15000,500,true});service.configure(scene(),gekko_test_profiles(gun()));host::Roster roster;roster.complete=true;
 for(unsigned n=0;n<24;++n){joined(service.authority(),n,pose(float(n*3000)),0);check(service.admit(id(n))&&service.receive(id(n),wire::encode(wire::Accept{8}),0),"24 peers");check(service.authority().assign_special(id(n),special_pc::Kind::gekko,n!=0,0)==Reject::none,"24 forms");host::Player r{uint8_t(n),id(n).instance,id(n).character,"Fixture",""};r.appearance=std::array<uint8_t,28>{};roster.slots[n]=r;}
 service.authority().active(true);service.deliveries();for(unsigned n=0;n<24;++n){wire::Input input{8,1,service.authority().snapshot().players[n]->pose,128};input.specialPc={special_pc::Action::jump,1};check(service.receive(id(n),wire::encode(input),100),"action wire");}service.poll(100);auto deliveries=service.deliveries();check(service.authority().snapshot().players[0]->specialPc.action==special_pc::Action::jump,"service starts action");
 for(auto&d:deliveries){check(d.payload.size()<=2000,"24 action frames bounded");auto reply=wire::decode(d.payload);if(auto*f=std::get_if<wire::Frame>(&reply)){check(f->sop.recipient==d.recipient,"recipient footer");}}
 service.poll(1500);deliveries=service.deliveries();for(auto&d:deliveries)check(d.payload.size()<=2000,"no input still bounded host animation");auto snapshot=service.authority().snapshot();check(snapshot.players[0]->pose.feet[1]>500,"server physics progresses without input");
 snapshot.eventWatermark=1;Event e;e.epoch=8;e.id=1;e.source=id(0);e.weapon=23;auto frame=wire::Frame{snapshot,wire::Status::active,{e},service.authority().sop_view(id(0)).value()};auto bytes=wire::encode(frame);check(bytes.size()<=2000,"24 simultaneous Gekko action plus event and footer");auto decoded=std::get<wire::Frame>(wire::decode(bytes));check(decoded.snapshot==snapshot&&decoded.sop.specialPcRequest==1,"full state roundtrip");
 remote::Scene remote;check(remote.update(snapshot,roster,id(1),1500),"remote accepts Gekko");auto avatar=remote.sample(1550).front();check(avatar.specialPc.kind==special_pc::Kind::gekko&&avatar.specialPcSeconds>=1.4&&!avatar.specialPc.nameVisible,"remote motion clock and hidden name");
 auto broken=frame;broken.snapshot.players[0]->pose.capsule.height=1700;bool rejected=false;try{wire::encode(broken);}catch(const wire::Invalid&){rejected=true;}check(rejected,"special shape cannot be forged");
 wire::Input old{8,1,pose(),23},next{8,2,pose(),23};old.specialPc={special_pc::Action::kick,99};auto merged=wire::coalesce_input(old,next);check(merged.specialPc==old.specialPc,"pending edge coalesced");next.suspended=true;check(wire::coalesce_input(old,next).specialPc==special_pc::Intent{},"suspend drops unsent edge");
}
}
int main(){try{authority();operator_control();landing_on_peer();stunned_death();wire_and_service();std::cout<<"special PC HOST / collision / identity / operator / GWCB13 / 24 peers PASS\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
