#include "stage_environment.h"
#include "stage_weather.h"
#include "stage_precipitation.h"
#include <iostream>
#include <cmath>
using namespace mgo2mt;
namespace {void check(bool b,const char*m){if(!b)throw std::runtime_error(m);}bool close(float a,float b){return std::abs(a-b)<1e-5f;}}
int main(){try{
 auto original=std::make_shared<stage::Lighting>();original->back={.2f,.3f,.4f};original->front={.1f,.2f,.3f};original->direct={};original->hemispheres.resize(1);original->points.resize(1);original->points[0].flags=0;auto model=std::make_shared<CharacterModel>();ModelVertex up{},down{};up.ny=1;down.ny=-1;model->vertices={up,down};
 stage::EnvironmentCache cache;environment::Config c;cache.update(model,original,c);check(cache.model()==model&&cache.lighting()==original,"original returns exact authored objects");c.manualHemisphere=true;c.upper={255,0,0};c.lower={0,0,255};c.gainMilli=2000;c.time=environment::Time::night;cache.update(model,original,c);auto changed=cache.model();check(changed!=model&&cache.lighting()->hemispheres.empty()&&cache.lighting()->points.size()==1,"override replaces local hemisphere but retains installed lamps");check(close(changed->vertices[0].lr,2)&&close(changed->vertices[0].lb,0)&&close(changed->vertices[1].lb,2)&&close(changed->vertices[1].lr,0),"prebaked terrain uses upper-back and lower-front with exact gain");check(model->vertices[0].lit==0&&original->hemispheres.size()==1,"original geometry and lighting remain immutable");auto actor=cache.lighting()->sample({0,0,0},{0,1,0});check(close(actor.color[0],changed->vertices[0].lr),"actor and static terrain share same light");c.rain=true;c.time=environment::Time::day;cache.update(model,original,c);check(cache.model()==changed,"weather and lower-priority time changes do not rebake manual hemisphere");c={};cache.update(model,original,c);check(cache.model()==model&&cache.lighting()==original,"Original restores exact previous authored vertices");c.time=environment::Time::day;auto day=stage::environment_lighting(*original,c);c.time=environment::Time::night;auto night=stage::environment_lighting(*original,c);check(day.sample({0,0,0},{0,1,0}).color[0]>night.sample({0,0,0},{0,1,0}).color[0],"native time preset visibly changes environment");
 stage::weather::Controller weather;auto fog=weather.sample(true,false,12,{0,1800,0});check(fog.active&&fog.dust.empty()&&stage::weather::fog_amount(65000,fog)>.5f,"fog alone has distance haze without dust");auto sand=weather.sample(false,true,12,{0,1800,0});check(sand.active&&!sand.dust.empty()&&stage::weather::fog_amount(65000,sand)==0&&sand.skyAmount==0,"sand alone has original dust without fog");auto clear=weather.sample(false,false,12,{0,1800,0});check(!clear.active&&clear.dust.empty(),"independent all OFF");
 c={};check(stage::environment_weather("n022a",c).preset==stage::weather::Preset::fog_sand,"Original preserves requested QQ preset");c.weatherOverride=true;c.rain=c.snow=true;auto both=stage::environment_weather("n022a",c);check(both.rainEnabled==true&&both.snowEnabled==true&&both.preset==stage::weather::Preset::clear,"host independent flags override stage preset");auto rain=both;rain.snowEnabled=false;auto snow=both;snow.rainEnabled=false;auto a=stage::weather::precipitation(rain,5,{0,1800,0},nullptr),b=stage::weather::precipitation(snow,5,{0,1800,0},nullptr),all=stage::weather::precipitation(both,5,{0,1800,0},nullptr);check(!a.empty()&&!b.empty()&&all.size()==a.size()+b.size()&&all.size()<=256,"independent bounded rain plus snow particles");check(a[0].to[1]<a[0].from[1]&&a[0].widthPixels<b[0].widthPixels,"falling rain streak and snow point styles");both.rainEnabled=both.snowEnabled=false;check(stage::weather::precipitation(both,5,{0,1800,0},nullptr).empty(),"OFF stops airborne particles immediately");
 auto roof=stage::Collision::make({{-30000,2500,-30000},{30000,2500,-30000},{30000,2500,30000},{-30000,2500,30000}},{{{0,1,2}},{{0,2,3}}});check(stage::weather::precipitation(rain,5,{0,1800,0},&roof).empty(),"roof suppresses indoor precipitation");
 std::cout<<"HOST manual hemisphere/static bake/time/weather independence/native precipitation PASS\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
