#include "water_audio.h"
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <cmath>
using namespace mgo2mt::water_audio;
namespace {
void check(bool v,const char* why){if(!v)throw std::runtime_error(why);}
Actor fixture(){return {101,1,{0,2,0},{200.f,200.f,.65f,mgo2mt::stage::WaterFoot::inWater},true,true};}
uint32_t u32(const std::vector<uint8_t>&b,size_t n){return b[n]|uint32_t(b[n+1])<<8|uint32_t(b[n+2])<<16|uint32_t(b[n+3])<<24;}
}
int main(int argc,char**argv){try{
 Steps steps;Scope scope{1,1};std::array<Actor,1> actors{fixture()};
 check(steps.update(scope,actors,100,true).empty(),"late join in water is silent");actors[0].feet[2]=499;check(steps.update(scope,actors,116,true).empty(),"below native stride silent");actors[0].feet[2]=500;auto events=steps.update(scope,actors,132,true);check(events.size()==1&&events[0].identity==101&&events[0].life==1&&events[0].position[1]==203,"movement emits one water surface sound");
 auto sound=make_sound(events[0],L"data/native_water_step.wav",{0,203,500});check(sound&&sound->cue==0&&sound->gain==.32f,"explicit native cue and moderate gain");auto far=make_sound(events[0],L"data/native_water_step.wav",{0,203,1000});check(far&&far->gain<sound->gain,"distance attenuation");check(!make_sound(events[0],L"data/original_1372.wav",{0,0,0}),"cannot claim original cue through wrong filename");check(!make_sound(events[0],L"data/native_water_step.wav",{0,0,50000}),"distant sound rejected");
 actors[0].feet[2]=1000;check(steps.update(scope,actors,200,true).empty(),"cadence cooldown");check(steps.update(scope,actors,372,true).size()==1,"distance retained during cooldown");check(steps.update(scope,actors,372,true).empty(),"same clock drains once");check(steps.update(scope,actors,400,true).empty(),"stationary no repeat");
 actors[0].water={};check(steps.update(scope,actors,410,true).empty(),"dry clears pending water cadence");actors[0].water=fixture().water;check(steps.update(scope,actors,426,true).size()==1,"new wet entry emits after dry baseline");
 actors[0].alive=false;check(steps.update(scope,actors,426,true).empty(),"same-clock death is silent");actors[0].alive=true;++actors[0].life;check(steps.update(scope,actors,427,true).empty(),"new life cannot replay previous water sound");actors[0].feet[2]+=500;check(steps.update(scope,actors,443,true).size()==1,"new life movement can sound");
 actors[0].grounded=false;actors[0].feet[2]+=500;check(steps.update(scope,actors,459,true).empty(),"airborne never creates water foot sound");actors[0].grounded=true;check(steps.update(scope,actors,460,true).size()==1,"landing in confirmed water emits once");
 ++scope.scene;check(steps.update(scope,actors,470,true).empty(),"scene reset silent");++scope.epoch;check(steps.update(scope,actors,480,true).empty(),"room reset silent");actors[0].feet[2]+=3000;check(steps.update(scope,actors,496,true).empty(),"teleport silent");actors[0].feet[2]+=500;check(steps.update(scope,actors,800,true).empty(),"stall discards backlog");check(steps.update(scope,actors,799,true).empty(),"clock rollback discards backlog");
 check(steps.update(scope,actors,815,false).empty(),"inactive clears state");check(steps.update(scope,actors,831,true).empty(),"resume in water establishes baseline");check(steps.update(scope,{},832,true).empty(),"leave clears actor");check(steps.update(scope,actors,833,true).empty(),"rejoin same actor has no stale sound");
 actors[0].water.level=300.f;check(steps.update(scope,actors,834,true).empty(),"water height replacement silent");actors[0].water.horizontalScale=NAN;actors[0].feet[2]+=500;check(steps.update(scope,actors,850,true).empty(),"invalid water no sound");actors[0].feet[0]=NAN;check(steps.update(scope,actors,866,true).empty(),"invalid feet resets state");
 std::vector<Actor> crowd;for(unsigned i=0;i<24;++i){auto a=fixture();a.identity=i+1;crowd.push_back(a);}check(steps.update(scope,crowd,900,true).empty(),"full roster baseline");for(auto&a:crowd)a.feet[2]+=500;events=steps.update(scope,crowd,916,true);check(events.size()==Steps::maximumEvents,"simultaneous audio bounded at four");check(steps.update(scope,crowd,932,true).empty(),"dropped budget events never replay later");
 crowd.push_back(crowd[0]);check(steps.update(scope,crowd,948,true).empty(),"oversize roster resets");crowd.resize(2);crowd[1]=crowd[0];check(steps.update(scope,crowd,964,true).empty(),"duplicate identity rejects whole batch");
 {Steps posture;std::array<Actor,1> a{fixture()};check(valid_wet(a[0]),"shared current wet guard");posture.update(scope,a,100,true);a[0].water.horizontalScale=0;check(valid_wet(a[0])&&posture.update(scope,a,116,true).empty(),"blocked prone keeps valid wet contact without an entry sound");a[0].water.horizontalScale=.65f;check(posture.update(scope,a,132,true).empty(),"standing from blocked prone cannot fabricate a wet entry sound");a[0].alive=false;check(!valid_wet(a[0]),"voice guard rejects dead actor");a[0].alive=true;a[0].grounded=false;check(!valid_wet(a[0]),"voice guard rejects airborne actor");a[0].grounded=true;a[0].water.level.reset();check(!valid_wet(a[0]),"voice guard rejects missing water");}
 auto wave=native_step_wav();check(wave==native_step_wav(),"generated local asset is deterministic");check(wave.size()==44+5292*2&&std::string(wave.begin(),wave.begin()+4)=="RIFF"&&std::string(wave.begin()+8,wave.begin()+12)=="WAVE","complete PCM container");check(u32(wave,4)==wave.size()-8&&u32(wave,24)==22050&&wave[22]==1&&wave[34]==16&&u32(wave,40)==5292*2,"mono PCM16 exact duration and sizes");
 int peak=0;double energy=0;for(size_t i=44;i<wave.size();i+=2){int sample=int16_t(uint16_t(wave[i])|uint16_t(wave[i+1])<<8);peak=std::max(peak,std::abs(sample));energy+=double(sample)*sample;}check(peak>500&&peak<=10000&&energy>1000000,"real nonzero bounded-amplitude sound");check(wave[44]==0&&wave[45]==0&&std::abs(int16_t(uint16_t(wave[wave.size()-2])|uint16_t(wave.back())<<8))<=1,"envelope has silent boundaries");
 if(argc>1){std::filesystem::create_directories(argv[1]);std::ofstream f(std::filesystem::path(argv[1])/filename,std::ios::binary);f.write(reinterpret_cast<const char*>(wave.data()),wave.size());check(bool(f),"write offline generated asset");}
 std::cout<<"water_audio_test PASS: native PCM peak="<<peak<<", wet distance cadence, bounded roster/audio, life/scene/leave/focus/teleport and no original cue substitution\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
