#include "water_renderer.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
using namespace mgo2win;using Microsoft::WRL::ComPtr;
namespace {
void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
void ok(HRESULT h){check(SUCCEEDED(h),"WARP operation");}
using Pixels=std::vector<uint8_t>;
Pixels capture(ID3D11Device*d,ID3D11DeviceContext*c,const CharacterRenderer&r){
 ComPtr<ID3D11Resource> resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D> texture;ok(resource.As(&texture));D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> staging;ok(d->CreateTexture2D(&desc,nullptr,&staging));c->CopyResource(staging.Get(),texture.Get());D3D11_MAPPED_SUBRESOURCE map{};ok(c->Map(staging.Get(),0,D3D11_MAP_READ,0,&map));Pixels pixels(desc.Width*desc.Height*4);for(size_t y=0;y<desc.Height;++y)std::copy_n(static_cast<uint8_t*>(map.pData)+y*map.RowPitch,desc.Width*4,pixels.data()+y*desc.Width*4);c->Unmap(staging.Get(),0);return pixels;
}
void bitmap(const std::filesystem::path&p,const Pixels&rgba){auto pixels=rgba;for(size_t i=0;i<pixels.size();i+=4)std::swap(pixels[i],pixels[i+2]);BITMAPFILEHEADER f{};BITMAPINFOHEADER b{};b.biSize=40;b.biWidth=616;b.biHeight=-392;b.biPlanes=1;b.biBitCount=32;b.biSizeImage=DWORD(pixels.size());f.bfType=0x4d42;f.bfOffBits=sizeof(f)+sizeof(b);f.bfSize=f.bfOffBits+b.biSizeImage;std::ofstream out(p,std::ios::binary);out.write(reinterpret_cast<const char*>(&f),sizeof(f));out.write(reinterpret_cast<const char*>(&b),sizeof(b));out.write(reinterpret_cast<const char*>(pixels.data()),pixels.size());check(bool(out),"bitmap write");}
size_t differences(const Pixels&a,const Pixels&b){size_t count=0;for(size_t i=0;i<a.size();i+=4)if(!std::equal(a.begin()+i,a.begin()+i+4,b.begin()+i))++count;return count;}
CharacterModel panel(float z,float extent=10000){CharacterModel m;m.bounds={-extent,-extent,z,extent,extent,z};for(auto xy:std::array<std::array<float,2>,4>{{{-extent,-extent},{extent,-extent},{extent,extent},{-extent,extent}}}){ModelVertex v{};v.x=xy[0];v.y=xy[1];v.z=z;v.nz=-1;v.lr=.1f;v.lg=.15f;v.lb=.3f;v.lit=1;m.vertices.push_back(v);}m.indices={0,1,2,0,2,3};m.parts.push_back({0,6,0,0});m.textures.push_back({4,4,9,{255,255,255,255,0,0,0,0}});return m;}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::invalid_argument&){rejected=true;}check(rejected,"invalid input rejected");}
}
int main(int argc,char**argv){try{
 std::filesystem::path out=argc>1?argv[1]:"";if(!out.empty())std::filesystem::create_directories(out);
 auto fields=stage::Water::make({{{0,0,2500},{500,500,500}},{{0,0,2500},{500,500,500}}});auto mesh=water_visuals::mesh(&fields,nullptr);check(mesh.indices.size()==6,"finite duplicate FIELD rendered once");check(water_visuals::mesh(nullptr,nullptr).indices.empty(),"missing water stays empty");
 auto slope=stage::WaterSurface::make({{{{{-500,300,2000},{500,500,2000},{0,700,3000}}}}});auto sloped=water_visuals::mesh(nullptr,&slope);check(sloped.vertices[0][1]==300&&sloped.vertices[1][1]==500&&sloped.vertices[2][1]==700,"authored slope retained exactly");
 auto repeated=stage::WaterSurface::make({{{{mesh.vertices[0],mesh.vertices[1],mesh.vertices[2]}}}});check(water_visuals::mesh(&fields,&repeated).indices.size()==6,"coincident FIELD/GWS triangle no double alpha");
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;ok(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));
 water_visuals::Renderer water(d.Get(),mesh);auto background=panel(6000);CharacterRenderer surface(d.Get(),background);WorldView view{{0,1500,0},{0,-.4f,1}};
 auto base=[&]{surface.render(c.Get(),0,false,&view);return capture(d.Get(),c.Get(),surface);};auto before=base();check(water.render(c.Get(),surface,view),"water draw");auto after=capture(d.Get(),c.Get(),surface);const auto count=differences(before,after);check(count>1000&&count<616*392/3,"finite visible water footprint");
 for(size_t i=0;i<after.size();i+=4)if(!std::equal(before.begin()+i,before.begin()+i+4,after.begin()+i)){for(size_t channel=0;channel<3;++channel)check(std::abs(float(after[i+channel])-(127.5f*.35f+before[i+channel]*.65f))<=2,"gray alpha .35 exactly one layer");const auto pixel=i/4;check(pixel%616>0&&pixel%616<615&&pixel/616>0&&pixel/616<391,"finite water never fills screen edges");}
 auto bad=mesh;bad.vertices[0][0]=std::numeric_limits<float>::quiet_NaN();rejects([&]{water_visuals::Renderer invalid(d.Get(),bad);});bad=mesh;bad.indices[0]=9999;rejects([&]{water_visuals::Renderer invalid(d.Get(),bad);});bad=mesh;bad.indices[1]=bad.indices[0];rejects([&]{water_visuals::Renderer invalid(d.Get(),bad);});bad=mesh;bad.indices.resize((water_visuals::maximum_triangles+1)*3);rejects([&]{water_visuals::Renderer invalid(d.Get(),bad);});rejects([&]{water_visuals::Renderer invalid(d.Get(),mesh,{.5f,1.1f});});
 water_visuals::Renderer empty(d.Get(),{}),transparent(d.Get(),mesh,{.5f,0});check(!empty.render(c.Get(),surface,view)&&!transparent.render(c.Get(),surface,view)&&capture(d.Get(),c.Get(),surface)==after,"empty or opacity zero is exact no-op");auto invalidView=view;invalidView.aspect=0;check(!water.render(c.Get(),surface,invalidView)&&capture(d.Get(),c.Get(),surface)==after,"invalid camera leaves target intact");
 auto wallModel=panel(1000);CharacterRenderer wall(d.Get(),wallModel);wall.render(c.Get(),0,false,&view);auto wallBefore=capture(d.Get(),c.Get(),wall);water.render(c.Get(),wall,view);check(capture(d.Get(),c.Get(),wall)==wallBefore,"opaque foreground completely occludes water");
 auto redModel=panel(4000);for(auto&v:redModel.vertices){v.lr=1;v.lg=0;v.lb=0;}CharacterRenderer red(d.Get(),redModel);red.render(c.Get(),0,false,&view,&surface);auto depthAfter=capture(d.Get(),c.Get(),surface);base();red.render(c.Get(),0,false,&view,&surface);check(capture(d.Get(),c.Get(),surface)==depthAfter,"water does not write world depth");check(base()==before,"normal renderer restored unchanged");
 view.aspect*=2;auto wideBefore=base();water.render(c.Get(),surface,view);auto wide=capture(d.Get(),c.Get(),surface);const auto wideCount=differences(wideBefore,wide);check(wideCount>count*45/100&&wideCount<count*55/100,"world aspect doubles and footprint width halves");
 view={{0,-500,0},{0,.4f,1}};auto underBefore=base();water.render(c.Get(),surface,view);auto under=capture(d.Get(),c.Get(),surface);check(differences(underBefore,under)>1000,"both-sided water visible below plane");
 if(!out.empty()){bitmap(out/"baseline.bmp",before);bitmap(out/"gray-water.bmp",after);bitmap(out/"occluded.bmp",wallBefore);bitmap(out/"wide-aspect.bmp",wide);bitmap(out/"underwater.bmp",under);}
 for(int arg=2;arg<argc;++arg){std::ifstream in(argv[arg],std::ios::binary);auto authored=stage::WaterSurface::read(in);auto originalMesh=water_visuals::mesh(nullptr,&authored);check(!originalMesh.indices.empty(),"original water surface available");water_visuals::Renderer original(d.Get(),originalMesh);water_visuals::Vec3 low{1e7f,1e7f,1e7f},high{-1e7f,-1e7f,-1e7f};for(auto p:originalMesh.vertices)for(unsigned axis=0;axis<3;++axis){low[axis]=std::min(low[axis],p[axis]);high[axis]=std::max(high[axis],p[axis]);}const float span=std::max(high[0]-low[0],high[2]-low[2]);WorldView camera{{(low[0]+high[0])*.5f,high[1]+span,(low[2]+high[2])*.5f-span},{0,-1,1}};auto authoredBackground=panel(high[2]+span,1e6f);CharacterRenderer destination(d.Get(),authoredBackground);destination.render(c.Get(),0,false,&camera);auto originalBefore=capture(d.Get(),c.Get(),destination);original.render(c.Get(),destination,camera);auto originalAfter=capture(d.Get(),c.Get(),destination);check(differences(originalBefore,originalAfter)>100,"original finite surface rendered");if(!out.empty())bitmap(out/(std::filesystem::path(argv[arg]).stem().string()+"-original-gray.bmp"),originalAfter);std::cout<<"authored "<<std::filesystem::path(argv[arg]).filename().string()<<": "<<originalMesh.indices.size()/3<<" triangles\n";}
 std::cout<<"Water renderer PASS: finite/dedup/slope/gray/alpha/depth occlusion/no depth writes/aspect/both sides/invalid input\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}

