#include "combat_particle_renderer.h"
#include "combat_light_effects.h"
#include <algorithm>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace mgo2mt;
using Microsoft::WRL::ComPtr;
namespace {
void check(bool ok,const char*message){if(!ok)throw std::runtime_error(message);}
void hr(HRESULT status){check(SUCCEEDED(status),"WARP capture failure");}
std::vector<uint8_t> read(const std::filesystem::path&path){std::ifstream f(path,std::ios::binary|std::ios::ate);auto n=f.tellg();check(n>0&&n<16*1024*1024,"original bundle extent");std::vector<uint8_t>b(size_t(n),0);f.seekg(0);check(bool(f.read(reinterpret_cast<char*>(b.data()),n)),"read original bundle");return b;}
void original_to_dds(const std::filesystem::path&bundle,const std::filesystem::path&out){
 auto data=read(bundle);size_t at=4;auto u32=[&](){check(at+4<=data.size(),"GWFX read");uint32_t n;std::memcpy(&n,data.data()+at,4);at+=4;return n;};check(!std::memcmp(data.data(),"GWFX",4)&&u32()==1,"GWFX version");auto count=u32();for(unsigned i=0;i<count;++i){auto key=u32(),w=u32(),h=u32(),codec=u32(),size=u32();check(size<=data.size()-at,"GWFX payload");if(key==0x510d60){check(codec==11,"original explosion BC3");std::vector<uint8_t>dds(128);auto put=[&](size_t where,uint32_t value){std::memcpy(dds.data()+where,&value,4);};put(0,0x20534444);put(4,124);put(8,0x81007);put(12,h);put(16,w);put(20,size);put(76,32);put(80,4);put(84,0x35545844);put(108,0x1000);dds.insert(dds.end(),data.begin()+at,data.begin()+at+size);std::ofstream file(out,std::ios::binary);file.write(reinterpret_cast<char*>(dds.data()),dds.size());check(bool(file),"write imported original image");return;}at+=size;}throw std::runtime_error("original flame absent");
}
struct Image{unsigned width=0,height=0;std::vector<uint8_t>rgba;};
Image capture(ID3D11Device*d,ID3D11DeviceContext*c,const CharacterRenderer&r){ComPtr<ID3D11Resource>resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D>texture;hr(resource.As(&texture));D3D11_TEXTURE2D_DESC desc;texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>staging;hr(d->CreateTexture2D(&desc,nullptr,&staging));c->CopyResource(staging.Get(),texture.Get());D3D11_MAPPED_SUBRESOURCE m;hr(c->Map(staging.Get(),0,D3D11_MAP_READ,0,&m));Image image{desc.Width,desc.Height,std::vector<uint8_t>(size_t(desc.Width)*desc.Height*4)};for(size_t y=0;y<desc.Height;++y)std::copy_n(static_cast<uint8_t*>(m.pData)+y*m.RowPitch,desc.Width*4,image.rgba.data()+y*desc.Width*4);c->Unmap(staging.Get(),0);return image;}
void save(const std::filesystem::path&path,Image image){for(size_t i=0;i<image.rgba.size();i+=4)std::swap(image.rgba[i],image.rgba[i+2]);BITMAPFILEHEADER b{};BITMAPINFOHEADER h{};h.biSize=sizeof(h);h.biWidth=LONG(image.width);h.biHeight=-LONG(image.height);h.biPlanes=1;h.biBitCount=32;h.biSizeImage=DWORD(image.rgba.size());b.bfType=0x4d42;b.bfOffBits=sizeof(b)+sizeof(h);b.bfSize=b.bfOffBits+h.biSizeImage;std::ofstream f(path,std::ios::binary);f.write(reinterpret_cast<char*>(&b),sizeof(b));f.write(reinterpret_cast<char*>(&h),sizeof(h));f.write(reinterpret_cast<char*>(image.rgba.data()),image.rgba.size());check(bool(f),"BMP capture write");}
CharacterModel background(){CharacterModel m;m.bounds={-20000,-10000,12000,20000,10000,12000};for(auto p:std::array<std::array<float,2>,4>{{{-20000,-10000},{20000,-10000},{20000,10000},{-20000,10000}}}){ModelVertex v{};v.x=p[0];v.y=p[1];v.z=12000;v.nz=-1;v.lr=.13f;v.lg=.15f;v.lb=.18f;v.lit=1;m.vertices.push_back(v);}m.indices={0,1,2,0,2,3};m.parts.push_back({0,6,0,0});m.textures.push_back({4,4,9,{255,255,255,255,0,0,0,0}});return m;}
const char*settings=R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{
 "muzzle":[{"texture":592620,"count":2,"lifetimeMs":850,"radius":180,"stretch":[3,0.4],"color":[1,0.8,0.45,1],"additive":true,"sizeRandom":0.1,"stretchRandom":0.2,"rotationRandom":0.25,"sizeCurve":[[0,0.5],[0.25,1.5],[1,2]],"alphaCurve":[[0,1],[0.3,0.9],[1,0]],"atlas":{"columns":2,"rows":2,"frames":4,"randomStart":true}}],
 "smoke":[],"casing":[],
 "humanBlood":[{"texture":354954,"count":4,"emissionMs":80,"lifetimeMs":850,"radius":130,"speed":400,"spread":0.9,"gravity":900,"velocity":[0,120,0],"color":[0.7,0.025,0.02,0.9],"rotationRandom":1,"sizeCurve":[[0,0.7],[0.4,2.5],[1,4]],"alphaCurve":[[0,1],[0.3,1],[1,0]]}],
 "explosion":[{"texture":"imported-flame.dds","count":2,"lifetimeMs":850,"radius":420,"stretch":[1.6,0.65],"additive":true,"velocity":[0,300,0],"rotationRandom":0.2,"atlas":{"columns":2,"rows":2,"frames":4,"fps":4},"sizeCurve":[[0,0.6],[0.4,1.6],[1,2.4]],"alphaCurve":[[0,1],[0.3,0.9],[1,0]]}]
 },"lights":{"shot":{"delayMs":50,"durationMs":250,"intensity":3},"explosion":{"durationMs":700,"intensity":3}}}})";
}
int main(int argc,char**argv){try{check(argc==4,"original bundle, blood bundle and output directory required");namespace fs=std::filesystem;fs::path out=argv[3];fs::create_directories(out);original_to_dds(argv[1],out/"imported-flame.dds");{std::ofstream json(out/"weapon_effects.json");json<<settings;check(bool(json),"saved effect configuration");}
 auto config=std::make_shared<weapon_effect::Config>();std::string error;check(config->load(out/"weapon_effects.json",error),error.c_str());ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;hr(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));combat::particles::Renderer renderer(d.Get(),argv[1]);renderer.add_bundle(argv[2]);renderer.add_textures(*config,out);CharacterRenderer surface(d.Get(),background());surface.resize_target(d.Get(),1280,720);WorldView view{{0,0,0},{0,0,1},16.f/9,.75f};
 combat::Snapshot state;state.epoch=1;state.eventWatermark=3;combat::Player p;p.identity={0,1,100};p.life=1;p.alive=true;state.players[0]=p;combat::Event shot;shot.epoch=1;shot.id=1;shot.source=p.identity;shot.sourceLife=1;shot.weapon=25;shot.kind=combat::EventKind::shot;shot.position={-2400,0,6000};shot.normal={0,0,1};auto explosion=shot;explosion.id=2;explosion.weapon=52;explosion.kind=combat::EventKind::explosion;explosion.position={0,0,6000};auto blood=shot;blood.id=3;blood.kind=combat::EventKind::damage;blood.target=p.identity;blood.targetLife=1;blood.hpDamage=100;blood.position={2400,0,6000};blood.normal={0,0,-1};std::array events{shot,explosion,blood};combat::particles::Pool pool;pool.configure(config);pool.synchronize(1,1,0,0);pool.dispatch(events,state,1000);combat::LightEffects lights;lights.configure(config);lights.synchronize(1,1,0,0);lights.dispatch(events,state,1000);
 surface.render(c.Get(),0,false,&view);const auto base=capture(d.Get(),c.Get(),surface);std::vector<Image>frames;std::ofstream report(out/"validation.json");report<<"{\"runtime\":\"WARP D3D11 + game Pool + shared evaluator\",\"importedOriginalBcPayloadPreserved\":true,\"frames\":[";unsigned number=0;
 for(uint64_t age:{60ull,300ull,760ull}){surface.render(c.Get(),0,false,&view);auto sprites=pool.sprites(state,1000+age);check(sprites.size()>=6,"blood flame muzzle all sampled");check(renderer.render(c.Get(),surface,view,sprites),"edited effect sprites rendered");auto pixels=capture(d.Get(),c.Get(),surface);uint64_t changed=0,energy=0;for(size_t i=0;i<pixels.rgba.size();i+=4){bool diff=false;for(unsigned k=0;k<3;++k){auto delta=std::abs(int(pixels.rgba[i+k])-int(base.rgba[i+k]));energy+=delta;diff|=delta!=0;}changed+=diff;}check(changed>100,"visible edited effect pixels");const auto file="0"+std::to_string(++number)+"-"+std::to_string(age)+"ms.bmp";save(out/file,pixels);if(number>1)report<<',';report<<"{\"ageMs\":"<<age<<",\"sprites\":"<<sprites.size()<<",\"changedPixels\":"<<changed<<",\"energy\":"<<energy<<",\"activeLights\":"<<lights.sample(1000+age).size()<<",\"file\":\""<<file<<"\"}";frames.push_back(std::move(pixels));}
 check(frames[0].rgba!=frames[1].rgba&&frames[1].rgba!=frames[2].rgba,"expansion animation and fade differ at all three times");check(pool.sprites(state,1930).empty()&&lights.sample(1930).empty(),"entire sequence expires");report<<"],\"completeExpiry\":true}\n";check(bool(report),"capture report saved");std::cout<<"Edited muzzle/blood/imported original explosion: 60/300/760ms real WARP screenshots, expansion/fade and complete expiry PASS\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
