#include "weapon_effect_config.h"
#include "combat_particle_effects.h"
#include "combat_light_effects.h"
#include <cmath>
#include <iostream>
#include <stdexcept>

using namespace mgo2mt;
namespace {
unsigned checks=0;
void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
bool near(float a,float b){return std::abs(a-b)<.001f;}
const char*fixture=R"({"format":"MGO2MT.WeaponEffects","version":1,
 "defaults":{"particles":{"humanBlood":[{"texture":5403745,"lifetimeMs":2000,"radius":50,"speed":1000,"gravity":1000,"sizeCurve":[[0,1],[1,3]],"alphaCurve":[[0,1],[1,0]]}],"gekkoBlood":[{"texture":354954,"radius":200}]},"sounds":{"shot":{"cue":44,"gain":0.5}}},
 "weapons":[{"id":25,"particles":{"muzzle":[{"texture":592620,"count":3,"delayMs":100,"emissionMs":200,"lifetimeMs":1000,"radius":100,"stretch":[2,0.5],"velocity":[10,20,30],"sizeCurve":[[0,1],[0.5,3],[1,2]],"alphaCurve":[[0,1],[1,0]],"atlas":{"columns":2,"rows":2,"frames":4,"fps":10}}],"smoke":[]},"lights":{"shot":{"delayMs":100,"durationMs":200,"radius":3333,"intensity":4,"color":[0.2,0.4,0.9],"intensityCurve":[[0,1],[0.5,0.25],[1,0]]}},"sounds":{"shot":{"path":"audio/custom.wav","delayMs":42,"gain":0.25},"click":{"enabled":false}}},
 {"id":52,"particles":{"explosion":[{"texture":"fx/imported.png","count":4,"emissionMs":300,"lifetimeMs":700,"radius":500,"sizeRandom":0.5,"stretchRandom":0.5,"alphaRandom":0.5,"rotationRandom":3.14,"speed":2000,"spread":1,"gravity":2000}],"smoke":[]},"lights":{"explosion":{"enabled":false}}}]})";
}
int main(){try{
 std::string error;auto config=std::make_shared<weapon_effect::Config>();check(config->load_text(fixture,error),error.c_str());
 check(config->particles(9,"muzzle")==nullptr,"missing channel retains legacy");check(config->particles(25,"smoke")&&config->particles(25,"smoke")->empty(),"empty override disables smoke");check(config->particles(52,"humanBlood")->size()==1,"defaults inherited individually");
 check(config->sound(9,"shot")->cue==44,"default sound cue");check(config->sound(25,"shot")->path=="audio/custom.wav"&&config->sound(25,"shot")->delayMs==42,"weapon WAV override");check(!config->sound(25,"click")->enabled,"explicit click disable");check(config->textures().at("fx/imported.png")==0xf0000001,"imported image has stable non-original namespace");
 for(const char*bad:{R"({"format":"MGO2MT.WeaponEffects","version":1,"weapons":[{"id":25},{"id":25}]})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"sounds":{"shot":{"cue":1,"path":"audio/a.wav"}}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"sounds":{"shot":{"path":"../outside.wav"}}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"muzzle":[{"texture":1,"atlas":{"frames":2}}]}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"muzzle":[{"texture":1,"sizeCurve":[[0,1],[0,2],[1,1]]}]}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"muzzle":[{"texture":1,"count":33}]}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"lights":{"shot":{"intensity":17}}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"lights":{"shot":{"durationMS":2}}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"muzzle":[{"texture":"C:/outside.png"}]}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"muzzle":[{"texture":"fx/CON.png"}]}}})",R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"muzzle":[{"texture":1,"count":32},{"texture":1,"count":32},{"texture":1,"count":32},{"texture":1,"count":32},{"texture":1,"count":1}]}}})"}){
  check(!config->load_text(bad,error)&&!error.empty(),"malformed schema rejected");check(config->sound(25,"shot")->delayMs==42,"failed validation preserves prior valid config");
 }
 const auto&emitters=*config->particles(25,"muzzle");auto preview=weapon_effect::sample(emitters,{0,0,0},{0,0,1},123,99);check(preview.empty(),"delay hides particles");preview=weapon_effect::sample(emitters,{0,0,0},{0,0,1},123,100);check(preview.size()==1&&preview[0].radius==100,"first emission exact start");preview=weapon_effect::sample(emitters,{0,0,0},{0,0,1},123,600);check(preview.size()==3&&near(preview[0].radius,300)&&near(preview[0].rgba[3],.5f),"emission duration and interpolated independent size alpha curves");check(preview[0].position==weapon_effect::Vec3{5,10,15}&&preview[0].stretch==std::array<float,2>{2,.5f},"velocity and rectangular board");check(preview[0].uv==std::array<float,4>{.5f,.5f,1,1},"atlas clamps to final frame");check(weapon_effect::sample(emitters,{},{0,0,1},123,1300).empty(),"last emitted particle ends exactly");
 auto randomized=weapon_effect::sample(*config->particles(52,"explosion"),{},{0,1,0},2,500);auto again=weapon_effect::sample(*config->particles(52,"explosion"),{},{0,1,0},2,500);check(randomized.size()==4&&again.size()==4,"burst population");bool distinct=false;for(size_t i=0;i<randomized.size();++i){check(randomized[i].position==again[i].position&&randomized[i].radius==again[i].radius&&randomized[i].rotation==again[i].rotation&&randomized[i].rgba==again[i].rgba,"same seed preview deterministic");if(i&&randomized[i].rotation!=randomized[0].rotation)distinct=true;}check(distinct,"per particle random variation");check(weapon_effect::sample(*config->particles(52,"explosion"),{},{0,1,0},3,500)[0].radius!=randomized[0].radius,"distinct event variation");
 combat::Snapshot snapshot;snapshot.epoch=7;snapshot.eventWatermark=1;combat::Player player;player.identity={0,3,123};player.life=2;player.alive=true;snapshot.players[0]=player;
 combat::Event event;event.epoch=7;event.id=1;event.kind=combat::EventKind::shot;event.source=player.identity;event.sourceLife=2;event.weapon=25;event.position={0,1500,0};event.normal={0,0,1};combat::particles::Pool pool;pool.configure(config);pool.synchronize(7,1,0,0);pool.dispatch({&event,1},snapshot,1000);check(pool.sprites(snapshot,1099).empty(),"live pool honors configured delay and smoke disable");auto actual=pool.sprites(snapshot,1600);auto same=weapon_effect::sample(emitters,event.position,event.normal,event.id^(snapshot.epoch*0x9e3779b97f4a7c15ull),600);check(actual.size()==same.size()&&actual[0].position==same[0].position&&actual[0].radius==same[0].radius&&actual[0].stretch==same[0].stretch,"live game uses exact editor evaluator");pool.dispatch({&event,1},snapshot,1600);check(pool.sprites(snapshot,1600).size()==actual.size(),"duplicate accepted event cannot reemit");snapshot.players[0]->life=3;check(pool.sprites(snapshot,1601).empty(),"life change clears delayed particles");snapshot.players[0]->life=2;
 pool.clear();pool.synchronize(7,1,0,0);event.kind=combat::EventKind::damage;event.target=player.identity;event.targetLife=2;event.hpDamage=100;pool.dispatch({&event,1},snapshot,2000);actual=pool.sprites(snapshot,3000);check(actual.size()==1&&near(actual[0].radius,100)&&near(actual[0].rgba[3],.5f)&&near(actual[0].position[1],1000)&&near(actual[0].position[2],1000),"body blood follows edited lifetime radius gravity velocity");snapshot.players[0]->alive=false;check(pool.sprites(snapshot,3001).size()==1,"lethal contact blood continues");snapshot.players[0]->life=3;check(pool.sprites(snapshot,3002).empty(),"respawn blood removed");snapshot.players[0]->life=2;snapshot.players[0]->alive=true;
 combat::LightEffects lights;lights.configure(config);lights.synchronize(7,1,0,0);event.kind=combat::EventKind::shot;lights.dispatch({&event,1},snapshot,1000);check(lights.sample(1099).empty(),"light delay invisible");auto pulse=lights.sample(1100);check(pulse.size()==1&&pulse[0].intensity==4&&pulse[0].radius==3333&&pulse[0].color==std::array<float,3>{.2f,.4f,.9f},"edited point light start");check(near(lights.sample(1200)[0].intensity,1),"light curve midpoint");check(lights.sample(1300).empty(),"light exact lifetime");event.id=2;snapshot.eventWatermark=2;event.weapon=52;event.kind=combat::EventKind::explosion;lights.dispatch({&event,1},snapshot,1400);check(lights.sample(1400).empty(),"explicit explosion light disabled");
 lights.clear();lights.synchronize(7,1,0,0);event.weapon=25;event.id=4;snapshot.eventWatermark=4;event.kind=combat::EventKind::shot;lights.dispatch({&event,1},snapshot,2000);snapshot.players[0]->life=3;lights.dispatch({},snapshot,2050);check(lights.sample(2100).empty(),"respawn cancels pending light");snapshot.players[0]->life=2;
 lights.clear();lights.synchronize(7,1,0,0);event.id=4;lights.dispatch({&event,1},snapshot,2200);event.id=3;lights.dispatch({&event,1},snapshot,2200);check(lights.sample(2300).size()==2,"out of order light event chunks both play once");lights.dispatch({&event,1},snapshot,2300);check(lights.sample(2300).size()==2,"late light duplicate suppressed");
 // Legacy fallback aliases continue to use the requested weapon's configuration.
 combat::particles::Pool alias;alias.configure(config);alias.effect_source(200,25);alias.synchronize(7,1,0,0);event.weapon=200;event.kind=combat::EventKind::shot;alias.dispatch({&event,1},snapshot,2000);check(alias.sprites(snapshot,2000).size()==2,"unknown ID with original action alias emits legacy graphics");
 // Casing sound contacts sweep the original CNP trajectory once, never through
 // a floor lacking Floor/Sound flags; death/respawn invalidates stale contacts.
 auto floor=stage::Collision::make({{-10000,0,-10000},{10000,0,-10000},{10000,0,10000},{-10000,0,10000}},{{{0,1,2},stage::attribute::floor},{{0,2,3},stage::attribute::floor}});
 combat::particles::Pool cases;cases.synchronize(7,1,0,0);event.weapon=25;event.id=3;snapshot.eventWatermark=3;cases.dispatch({&event,1},snapshot,2000,[](const auto&)->std::optional<combat::particles::CasingEmission>{return combat::particles::CasingEmission{{0,1000,0},{1,0,0}};});check(cases.casing_contacts(snapshot,2100,floor).empty(),"no casing sound before contact");auto contacts=cases.casing_contacts(snapshot,2500,floor);check(contacts.size()==1&&near(contacts[0].position[1],0)&&contacts[0].weapon==25&&contacts[0].sourceLife==2,"swept casing contact identifies actual weapon and life");check(cases.casing_contacts(snapshot,2501,floor).empty(),"contact audio never repeats");auto lines=cases.sample(snapshot,2501);auto c=std::find_if(lines.begin(),lines.end(),[](const auto&p){return p.kind==combat::particles::Kind::casing;});check(c!=lines.end()&&near((c->from[1]+c->to[1])*.5f,0),"landed casing remains on floor");
 auto invisible=std::make_shared<weapon_effect::Config>();check(invisible->load_text(R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"particles":{"casing":[]}}})",error),"invisible casing fixture");cases.configure(invisible);cases.clear();cases.synchronize(7,1,0,0);event.id=4;snapshot.eventWatermark=4;cases.dispatch({&event,1},snapshot,3000,[](const auto&)->std::optional<combat::particles::CasingEmission>{return combat::particles::CasingEmission{{0,1000,0},{1,0,0}};});check(cases.casing_contacts(snapshot,3500,floor).size()==1,"muting casing image does not implicitly mute independent drop sound");
 weapon_effect::Config styled;check(styled.load_text(R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"reticle":{"color":[0.2,1,0.3,0.7],"thickness":3,"length":12,"minGap":4,"centerDot":false}},"weapons":[{"id":25,"reticle":{"enabled":false}}]})",error),"reticle style parser");check(styled.reticle(3)&&styled.reticle(3)->thickness==3&&!styled.reticle(3)->centerDot&&styled.reticle(3)->color[3]==.7f,"reticle default style inherited");check(!styled.reticle(25)->enabled,"weapon reticle hidden independently");check(!styled.load_text(R"({"format":"MGO2MT.WeaponEffects","version":1,"defaults":{"reticle":{"thickness":17}}})",error),"out of range reticle size rejected");check(styled.reticle(3)->thickness==3,"failed reticle edit preserves prior configuration");
 std::cout<<checks<<" weapon effect schema, evaluator/game parity, particles, light and physical casing checks PASS\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
