using MgoUi;
using System.Security.Cryptography;
using System.Text.Json;
int checks = 0;
void Check(bool b, string label) { checks++; if (!b) throw new Exception(label); }
void Reject(Action a, string label) { bool rejected = false; try { a(); } catch (InvalidDataException) { rejected = true; } catch (JsonException) { rejected = true; } Check(rejected, label); }
var sample = Samples.Create(); var text = Serialization.Encode(sample); var parsed = Serialization.Decode(text); Check(parsed.Elements.Count == 14, "sample all screens"); Check(text == Serialization.Encode(parsed), "lossless JSON roundtrip");
foreach (var anchor in LayoutRules.Anchors) { var e = new Element { Anchor = anchor, X = 17, Y = -33, Width = 213, Height = 87 }; var original = LayoutRules.Bounds(e); LayoutRules.SetAnchorPreservePosition(e, "center"); Check(LayoutRules.Bounds(e) == original, "anchor preserves position " + anchor); LayoutRules.SetAnchorPreservePosition(e, anchor); Check(e.X == 17 && e.Y == -33, "anchor exact roundtrip " + anchor); LayoutRules.SetBounds(e, new(80, 100, 300, 120)); Check(LayoutRules.Bounds(e) == new RectF(80, 100, 300, 120), "resizing anchored rectangle " + anchor); }
foreach (var size in new[] { (1280, 720), (1920, 1080), (1600, 900), (800, 900), (2000, 720) }) { var view = Viewport.Contain(size.Item1, size.Item2); var design = new MgoUi.PointF(733, 331); var pixel = view.ToPixel(new(design.X, design.Y, 1, 1)); var actual = view.ToDesign(pixel.X, pixel.Y); Check(Math.Abs(actual.X - design.X) < .001 && Math.Abs(actual.Y - design.Y) < .001, "contain pointer inversion " + size); Check(view.Left >= 0 && view.Top >= 0, "letterbox " + size); }
var d = new LayoutDocument { Elements = [new() { Id = "a", X = 10, Y = 10, Z = 1 }, new() { Id = "b", X = 10, Y = 10, Z = 1 }] }; var flags = new HashSet<string>(); Check(LayoutRules.Hit(d, new(20, 20), "title", "default", flags)?.Id == "b", "equal z later draw hit"); d.Elements[0].Z = 2; Check(LayoutRules.Hit(d, new(20, 20), "title", "default", flags)?.Id == "a", "higher z wins"); d.Elements[0].FlagsAll = ["alive"]; Check(LayoutRules.Hit(d, new(20, 20), "title", "default", flags)?.Id == "b", "required flag"); flags.Add("alive"); Check(LayoutRules.Hit(d, new(20, 20), "title", "default", flags)?.Id == "a", "flag activation"); d.Elements[0].FlagsNone = ["menu"]; flags.Add("menu"); Check(!LayoutRules.Shown(d.Elements[0], "title", "default", flags), "excluded flag"); d.Elements[1].State = "selected"; Check(!LayoutRules.Shown(d.Elements[1], "title", "default", flags), "exact state"); Check(LayoutRules.Shown(d.Elements[1], "title", "selected", flags), "matching state");
var history = new History(); history.Reset(sample); sample.Elements[0].X = 8; history.Commit(sample); sample.Elements[0].X = 16; history.Commit(sample); Check(history.Undo().Elements[0].X == 8, "undo movement"); Check(history.Undo().Elements[0].X == 48, "undo to baseline"); Check(history.Redo().Elements[0].X == 8, "redo movement"); var fork = history.Current; fork.Elements[0].Y = 99; history.Commit(fork); Check(!history.CanRedo, "new edit truncates redo"); Check(history.Current.Elements[0].X == 8, "snapshot independent");
foreach (var path in new[] { "../a.dds", "/a.dds", "C:/a.dds", "x/../../a.dds", "x\\a.dds", "a//b.dds" }) Reject(() => LayoutRules.ValidateRelative(path), "unsafe texture path " + path);
var invalid = Samples.Create(); invalid.Elements.Add(new() { Id = invalid.Elements[0].Id }); Reject(() => LayoutRules.Validate(invalid), "duplicate IDs"); invalid = Samples.Create(); invalid.Elements[0].Width = 0; Reject(() => LayoutRules.Validate(invalid), "zero width"); invalid = Samples.Create(); invalid.Elements[0].Color = [255, 255, -1, 255]; Reject(() => LayoutRules.Validate(invalid), "color range"); invalid = Samples.Create(); invalid.Elements[0].FlagsAll = ["a"]; invalid.Elements[0].FlagsNone = ["a"]; Reject(() => LayoutRules.Validate(invalid), "contradictory flags"); Reject(() => Serialization.Decode(text.Replace("\"width\": 1280", "\"width\": 1920")), "wrong base dimensions"); Reject(() => Serialization.Decode(text.Insert(text.IndexOf('{') + 1, "\"unknown\":1,")), "unknown field");
var tmp = Path.Combine(Path.GetTempPath(), "mgo-ui-tests-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(tmp);
try { var source = Path.Combine(tmp, "source"); Directory.CreateDirectory(source); File.WriteAllBytes(Path.Combine(source, "owned.png"), [1, 2, 3, 4]); var exportDoc = new LayoutDocument { Elements = [new() { Id = "image", Kind = "image", Texture = "owned.png" }] }; var file = Path.Combine(tmp, "published", "layout.json"); Check(RuntimeExport.Export(file, exportDoc, source) == 1, "asset export count"); var loaded = Serialization.Decode(File.ReadAllText(file)); Check(loaded.Elements[0].Texture.StartsWith("layout.assets/"), "portable relative export"); Check(File.ReadAllBytes(LayoutRules.AssetPath(Path.GetDirectoryName(file)!, loaded.Elements[0].Texture)).SequenceEqual(new byte[] { 1, 2, 3, 4 }), "original bytes preserved"); Check(exportDoc.Elements[0].Texture == "owned.png", "export nonmutating"); var project = Path.Combine(tmp, "layout.mgoui"); Serialization.WriteProject(project, new() { AssetRoot = source, Layout = exportDoc }); Check(Serialization.ReadProject(project).AssetRoot == source, "project material root preserved"); Check(Serialization.ReadProject(file).AssetRoot == Path.GetDirectoryName(file), "runtime import asset root"); var before = File.ReadAllBytes(file); exportDoc.Elements[0].Texture = "absent.png"; try { RuntimeExport.Export(file, exportDoc, source); throw new Exception("Missing source accepted"); } catch (FileNotFoundException) { } Check(File.ReadAllBytes(file).SequenceEqual(before), "missing source leaves previous JSON intact"); } finally { Directory.Delete(tmp, true); }
var importTmp = Path.Combine(Path.GetTempPath(), "mgo-ui-import-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(importTmp);
try
{
    foreach (var extension in ImageImport.Extensions)
    {
        var source = Path.Combine(importTmp, "source" + extension); var original = new byte[] { 19, 28, 71, 255 }; File.WriteAllBytes(source, original);
        var root = Path.Combine(importTmp, "assets"); var relative = ImageImport.CopyOriginal(source, root);
        Check(Path.GetExtension(relative) == extension && File.ReadAllBytes(LayoutRules.AssetPath(root, relative)).SequenceEqual(original), "original import bytes/extension " + extension);
        Check(ImageImport.CopyOriginal(source, root) == relative, "same input reused " + extension);
        File.WriteAllBytes(source, [90, 1, 2, 3]); var other = ImageImport.CopyOriginal(source, root);
        Check(other != relative && File.ReadAllBytes(LayoutRules.AssetPath(root, relative)).SequenceEqual(original), "name collision does not overwrite " + extension);
        var exportDoc = new LayoutDocument { Elements = [new() { Id = "image", Kind = "image", Texture = relative }] }; var output = Path.Combine(importTmp, "export-" + extension[1..], "layout.json"); RuntimeExport.Export(output, exportDoc, root);
        Check(Serialization.ReadProject(output).Layout.Elements[0].Texture.EndsWith(extension), "runtime export original format " + extension);
    }
    Reject(() => ImageImport.CopyOriginal(Path.Combine(importTmp, "not-supported.svg"), importTmp), "unsupported vector rejected");
}
finally { Directory.Delete(importTmp, true); }
var controls = new LayoutDocument { Elements = [new() { Id="button", Kind="button", Text="開始", DelayMs=500, HoverColor=[50,80,90,255], PressedColor=[80,120,140,255], ShadowColor=[0,0,0,120], ShadowX=4, ShadowY=6, TextColor=[240,250,250,255], OnClick=[new() { Type="delay", Ms=200 },new() { Type="playSound", Sound="confirmation.wav", WaitForEnd=true, Volume=.4f },new() { Type="emitEvent", Name="title.start" }] },new() { Id="dropdown", Kind="dropdown", Bind="weather", Options=[new() { Value="clear", Label="晴れ" },new() { Value="rain", Label="雨" }], Selected="rain", DelayMs=250, OnChange=[new() { Type="playSound", Sound="confirmation.mp3", WaitForEnd=true },new() { Type="emitEvent", Name="weather_changed" }] }] };
Reject(()=>Serialization.Encode(new(){Elements=Enumerable.Range(0,300).Select(i=>new Element{Id="large"+i,Kind="text",Width=1,Height=1,Text=new string('a',4096)}).ToList()}),"oversized JSON rejected before save/export");
Reject(()=>LayoutRules.Validate(new(){Elements=Enumerable.Range(0,10).Select(i=>new Element{Id="raster"+i,Kind="text",Width=1280,Height=720,Text="x"}).ToList()}),"aggregate text raster budget");
Reject(()=>LayoutRules.Validate(new(){Elements=Enumerable.Range(0,33).Select(i=>new Element{Id="paint"+i,Width=1280,Height=720}).ToList()}),"aggregate paint budget");
Reject(()=>LayoutRules.Validate(new(){Elements=Enumerable.Range(0,513).Select(i=>new Element{Id="image"+i,Kind="image",Width=1,Height=1,Texture=i+".png"}).ToList()}),"distinct image limit");
Check(Serialization.Encode(Serialization.Clone(controls)) == Serialization.Encode(controls), "controls audio delay lossless roundtrip");
foreach (var bad in new UiAction[] { new() { Type="delay", Ms=-1 },new() { Type="delay", Ms=60001 },new() { Type="delay" },new() { Type="delay",Ms=5,Name="wrong" },new() { Type="emitEvent",Name="event",Ms=2 },new() { Type="playSound",Sound="../a.wav" },new() { Type="playSound",Sound="a.ogg" },new() { Type="playSound",Sound="a.wav",Volume=float.NaN },new() { Type="emitEvent",Name="bad\nname" } }) Reject(()=>AudioRules.Validate(bad),"strict action rejection " + bad.Type);
foreach (var modify in new Action<LayoutDocument>[] { x=>x.Elements[0].DelayMs=-1, x=>x.Elements[0].DelayMs=60001, x=>x.Elements[0].ShadowY=257, x=>x.Elements[0].PressedColor=[1,2,3], x=>x.Elements[1].Options[1].Value="clear", x=>x.Elements[1].Selected="missing", x=>x.Elements[1].Options=[], x=>x.Elements[0].Options=[new(){Value="bad",Label="bad"}], x=>x.Elements[0].OnChange=[new(){Type="emitEvent",Name="bad"}], x=>x.Elements[1].OnChange=[new(){Type="setVisible",Target="missing"}] }) { var changed=Serialization.Clone(controls); modify(changed); Reject(()=>LayoutRules.Validate(changed),"strict control fields"); }
var audioTmp=Path.Combine(Path.GetTempPath(),"mgo-ui-audio-"+Guid.NewGuid().ToString("N")); Directory.CreateDirectory(audioTmp);
try
{
    foreach(var ext in AudioRules.Extensions) { var source=Path.Combine(audioTmp,"confirmation"+ext); var bytes=new byte[]{11,22,33,44}; File.WriteAllBytes(source,bytes); var imported=AudioImport.CopyOriginal(source,audioTmp); Check(Path.GetExtension(imported)==ext&&File.ReadAllBytes(LayoutRules.AssetPath(audioTmp,imported)).SequenceEqual(bytes),"audio import original bytes " + ext); Check(AudioImport.CopyOriginal(source,audioTmp)==imported,"audio import deduplicated " + ext); }
    var output=Path.Combine(audioTmp,"export","layout.json"); Check(RuntimeExport.Export(output,controls,audioTmp)==2,"both onClick and onChange audio exported"); var exported=Serialization.ReadProject(output); Check(exported.Layout.Elements[0].OnClick[1].Sound!.EndsWith(".wav")&&exported.Layout.Elements[1].OnChange[0].Sound!.EndsWith(".mp3"),"audio formats preserved through export");
    var bytesBefore=File.ReadAllBytes(output); var missing=Serialization.Clone(controls); missing.Elements[1].OnChange[0].Sound="absent.wav"; try { RuntimeExport.Export(output,missing,audioTmp); throw new Exception("missing OnChange audio accepted"); } catch(FileNotFoundException) { } Check(File.ReadAllBytes(output).SequenceEqual(bytesBefore),"failed OnChange export preserves previous JSON");
    File.WriteAllBytes(Path.Combine(audioTmp,"empty.wav"),[]); Reject(()=>AudioImport.CopyOriginal(Path.Combine(audioTmp,"empty.wav"),audioTmp),"empty audio rejected");
    var outside=Path.Combine(audioTmp,"outside"); var rooted=Path.Combine(audioTmp,"root"); Directory.CreateDirectory(outside); Directory.CreateDirectory(rooted); File.WriteAllBytes(Path.Combine(outside,"secret.wav"),[51,52]);
    var link=Path.Combine(rooted,"designer_audio"); var junction=System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("cmd.exe",$"/c mklink /J \"{link}\" \"{outside}\""){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true})!; junction.WaitForExit(); Check(junction.ExitCode==0,"create local junction fixture");
    try { Reject(()=>LayoutRules.AssetPath(rooted,"designer_audio/secret.wav"),"junction export escape rejected"); Reject(()=>AudioImport.CopyOriginal(Path.Combine(audioTmp,"confirmation.wav"),rooted),"junction import write escape rejected"); Check(Directory.GetFiles(outside).Length==1,"external junction target unchanged"); }
    finally { Directory.Delete(link); }
}
finally { Directory.Delete(audioTmp,true); }
La2ImportTests.Run(Check);
var legacyJson=Serialization.Encode(Samples.Create()).Replace("MGO2MT.UI_LAYOUT.1","MGO2WIN.UI_LAYOUT.1",StringComparison.Ordinal);var migratedLayout=Serialization.Decode(legacyJson);Check(migratedLayout.Format=="MGO2MT.UI_LAYOUT.1","legacy layout migrated in memory");Check(Serialization.Encode(migratedLayout)==Serialization.Encode(Samples.Create()),"legacy layout values preserved");
var legacyRoot=Path.Combine(Path.GetTempPath(),"mgo-ui-legacy-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(legacyRoot);
try
{
    string layoutFile=Path.Combine(legacyRoot,"legacy.json"),projectFile=Path.Combine(legacyRoot,"legacy.mgoui");File.WriteAllText(layoutFile,legacyJson);Check(Serialization.ReadProject(layoutFile).Layout.Format=="MGO2MT.UI_LAYOUT.1","legacy runtime file accepted");Check(File.ReadAllText(layoutFile)==legacyJson,"legacy source not changed by loading");
    var project=new ProjectDocument{AssetRoot=".",Layout=Samples.Create()};var oldProject=JsonSerializer.Serialize(project,Serialization.Options).Replace("MGO2MT.UI_PROJECT.1","MGO2WIN.UI_PROJECT.1",StringComparison.Ordinal).Replace("MGO2MT.UI_LAYOUT.1","MGO2WIN.UI_LAYOUT.1",StringComparison.Ordinal);File.WriteAllText(projectFile,oldProject);var migratedProject=Serialization.ReadProject(projectFile);Check(migratedProject.Format=="MGO2MT.UI_PROJECT.1"&&migratedProject.Layout.Format=="MGO2MT.UI_LAYOUT.1","legacy authoring project migrated");Check(migratedProject.AssetRoot==legacyRoot,"legacy relative asset root preserved");Check(File.ReadAllText(projectFile)==oldProject,"legacy project not overwritten by reading");Serialization.WriteProject(Path.Combine(legacyRoot,"new.mgoui"),migratedProject);Check(!File.ReadAllText(Path.Combine(legacyRoot,"new.mgoui")).Contains("MGO2WIN",StringComparison.Ordinal),"resaved project uses new identity");
}
finally{Directory.Delete(legacyRoot,true);}
if (args.Length > 0) { Directory.CreateDirectory(args[0]); File.WriteAllText(Path.Combine(args[0], "sample.json"), Serialization.Encode(Samples.Create())); File.WriteAllText(Path.Combine(args[0], "core-tests.json"), JsonSerializer.Serialize(new { status = "pass", checks, externalPackages = 0 })); }
Console.WriteLine($"PASS: {checks} model/anchor/contain/condition/history/export checks");


