#include "mounted_preview.h"
#include "mounted_renderer.h"
#include "mounted_input.h"
#include "gameplay_config.h"
#include "gameplay_presentation.h"
#include "stage_normals.h"
#include "stage_floor_blend.h"
#include "stage_surface_alpha.h"
#include "stage_navigation.h"
#include "combat_particle_renderer.h"
#include "combat_light_effects.h"
#include "combat_audio.h"
#include "character_catalog.h"
#include "weapon_hand_renderer.h"
#include "menu_font.h"
#include "mounted_flight_presentation.h"
#include "mortar_shell_renderer.h"
#include <fstream>
#include <iostream>
#include <cstring>
using Microsoft::WRL::ComPtr;
namespace mgo2mt {namespace {
void require(bool v,const char*s){if(!v)throw std::runtime_error(s);}
std::vector<char> read(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);require(bool(f),"Mounted preview input missing");return {std::istreambuf_iterator<char>(f),{}};}
void capture(ID3D11Device*d,ID3D11DeviceContext*c,const CharacterRenderer&r,const std::filesystem::path&p,const wchar_t*title){
 ComPtr<ID3D11Resource> resource;r.view()->GetResource(&resource);ComPtr<ID3D11Texture2D>texture;require(SUCCEEDED(resource.As(&texture)),"Mounted preview texture");D3D11_TEXTURE2D_DESC desc{};texture->GetDesc(&desc);desc.BindFlags=0;desc.Usage=D3D11_USAGE_STAGING;desc.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>copy;require(SUCCEEDED(d->CreateTexture2D(&desc,nullptr,&copy)),"Mounted preview readback");c->CopyResource(copy.Get(),texture.Get());D3D11_MAPPED_SUBRESOURCE map{};require(SUCCEEDED(c->Map(copy.Get(),0,D3D11_MAP_READ,0,&map)),"Mounted preview map");
 HDC dc=CreateCompatibleDC(nullptr);BITMAPINFO bi{};bi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bi.bmiHeader.biWidth=LONG(desc.Width);bi.bmiHeader.biHeight=-LONG(desc.Height);bi.bmiHeader.biPlanes=1;bi.bmiHeader.biBitCount=32;void*raw=nullptr;HBITMAP bmp=CreateDIBSection(dc,&bi,DIB_RGB_COLORS,&raw,nullptr,0);require(bmp&&raw,"Mounted preview DIB");auto old=SelectObject(dc,bmp);auto pixels=static_cast<uint32_t*>(raw);
 for(unsigned y=0;y<desc.Height;++y)for(unsigned x=0;x<desc.Width;++x){const auto*src=static_cast<const unsigned char*>(map.pData)+y*map.RowPitch+x*4;pixels[size_t(y)*desc.Width+x]=0xff000000u|(uint32_t(src[0])<<16)|(uint32_t(src[1])<<8)|src[2];}c->Unmap(copy.Get(),0);
 auto font=create_menu_font(27,FW_BOLD);auto previous=SelectObject(dc,font);SetBkMode(dc,TRANSPARENT);RECT label{24,20,LONG(desc.Width)-24,100};SetTextColor(dc,RGB(0,0,0));OffsetRect(&label,2,2);DrawTextW(dc,title,-1,&label,DT_LEFT|DT_TOP);OffsetRect(&label,-2,-2);SetTextColor(dc,RGB(255,210,100));DrawTextW(dc,title,-1,&label,DT_LEFT|DT_TOP);GdiFlush();
 BITMAPFILEHEADER fh{};fh.bfType=0x4d42;fh.bfOffBits=sizeof(fh)+sizeof(BITMAPINFOHEADER);fh.bfSize=fh.bfOffBits+desc.Width*desc.Height*4;std::ofstream out(p,std::ios::binary);out.write(reinterpret_cast<const char*>(&fh),sizeof(fh));out.write(reinterpret_cast<const char*>(&bi.bmiHeader),sizeof(bi.bmiHeader));out.write(static_cast<const char*>(raw),std::streamsize(desc.Width)*desc.Height*4);require(bool(out),"Mounted preview output");SelectObject(dc,previous);DeleteObject(font);SelectObject(dc,old);DeleteObject(bmp);DeleteDC(dc);
}
}
int run_mortar_catapult_preview(const std::filesystem::path&data,const std::filesystem::path&output){try{
 std::filesystem::create_directories(output);gameplay::Config config;mounted::Registry registry;std::string error;
 require(config.load(data/"gameplay.json",error),error.c_str());require(registry.load(data/"mounted_weapons.json",error),error.c_str());
 auto bytes=read(data/"stage/n022a.gwm");CharacterModel model(bytes);stage::load_original_normals(model,bytes,data/"stage/n022a.gwn");stage::load_floor_blend(model,bytes,data/"stage/n022a.gfb");stage::load_surface_alpha(model,bytes,data/"stage/n022a.gsa");
 std::ifstream cf(data/"stage/n022a.collision.cfg"),lf(data/"stage/n022a.lighting.cfg");auto collision=std::make_shared<const stage::Collision>(stage::Collision::read(cf));auto light=stage::Lighting::read(lf);for(auto&v:model.vertices){auto l=light.sample({v.x,v.y,v.z},{v.nx,v.ny,v.nz});v.lr=l.color[0];v.lg=l.color[1];v.lb=l.color[2];v.lit=1;}
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;require(SUCCEEDED(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c)),"Launcher preview WARP");CharacterRenderer ground(d.Get(),model);ground.resize_target(d.Get(),1280,720);mounted::Renderer machines(d.Get(),data,registry);
 CharacterCatalog catalog(read(data/"character/appearance.gwc"));std::array<uint8_t,28> appearance{};appearance[2]=11;appearance[3]=22;appearance[15]=46;appearance[17]=57;auto body=catalog.assemble(appearance);require(body.ready(),"Launcher original character");CharacterRenderer person(d.Get(),body.model);combat::particles::Renderer effects(d.Get(),data/config.resources().effectsManifest);
 combat::Effects audio;require(audio.load_manifest(data/config.resources().audioManifest),"Launcher original audio");require(audio.files().contains(19046)&&audio.files().contains(948),"Original mortar/catapult shot audio present");menu_font_resources().load(data/"fonts");
 std::ofstream report(output/"capture.json");report<<"{\"offlineRenderFixture\":true,\"map\":20,\"frames\":[";unsigned frames=0;bool exploded=false,landed=false;float highest=0;unsigned mortarEvents=0;bool shellVisible=false;
 for(const auto& instance:registry.scene(20)){
  const auto&type=*registry.find(instance.type);if(type.kind==mounted::Kind::gun)continue;
  audio.clear();combat::Authority authority;authority.begin(12,collision,config.profiles(20));require(authority.configure_mounted(registry,20),"Launcher configure");const combat::Identity self{0,1,101};combat::Pose pose;pose.feet=mounted::operator_position(instance,type);pose.yaw=instance.yaw;
  stage::Navigation nav;const bool placed=nav.place(*collision,pose.feet,30000);std::cout<<"placement "<<type.id<<" expected "<<pose.feet[0]<<' '<<pose.feet[1]<<' '<<pose.feet[2]<<" ground "<<(placed?nav.feet()[1]:-999999)<<std::endl;
  const uint16_t inventory[]{25,3,52};require(authority.join(self,1,pose,1000,1000,inventory,0),"Launcher placement feet/headroom");authority.active(true);require(authority.pose(self,12,1,pose,100)==combat::Reject::none,"Launcher admitted pose");auto mounted=authority.mount(self,12,1,{mounted::Action::mount,instance.id,1},100);if(mounted!=combat::Reject::none)throw std::runtime_error("Launcher mount rejected "+type.id+" code "+std::to_string(int(mounted)));
  auto snapshot=authority.snapshot();pose=snapshot.players[0]->pose;combat::particles::Pool particles;for(const auto&w:config.definitions())particles.textures(w.visual.effectId?w.visual.effectId:w.weapon.id,w.visual.flashTexture,w.visual.smokeTexture);particles.synchronize(12,instance.id,snapshot.eventWatermark,100);combat::LightEffects lights;lights.synchronize(12,instance.id,snapshot.eventWatermark,100);mounted::FlightPresentation flight;flight.update(12,&*snapshot.players[0],100);std::unique_ptr<mortar_shells::Renderer> shells;if(type.kind==mounted::Kind::mortar&&!type.projectileModel.empty()){shells=std::make_unique<mortar_shells::Renderer>(d.Get(),data/type.projectileModel,config.find(type.weapon)->weapon.range);shells->update(c.Get(),{},&snapshot,registry,20,collision,100,instance.id);}
  auto draw=[&](const char*name,const wchar_t*label,uint64_t now,double fired){
   snapshot=authority.snapshot();const auto&p=*snapshot.players[0];pose=p.pose;machines.update(c.Get(),20,&snapshot);auto frame=flight.update(12,&p,now);auto motion=frame?machines.action_pose(20,frame->instance,body.gender,frame->landing?PlayerMotion::Roll:PlayerMotion::Run,frame->seconds):machines.pose(20,instance.id,body.gender,fired);require(bool(motion),"Launcher original motion");catalog.pose(body,*motion);if(p.mountedId)mounted::operator_pitch(body,catalog.skeleton(body.gender),type,p.pose.pitch);person.update_vertices(c.Get(),body.model.vertices);
   auto target=p.pose.feet;target[1]+=type.kind==mounted::Kind::mortar?550:1000;float radius=type.kind==mounted::Kind::mortar?3100.f:6500.f,side=instance.yaw+1.25f;WorldView camera;camera.aspect=16.f/9.f;camera.verticalFov=1;camera.eye={target[0]-std::sin(side)*radius,target[1]+radius*.4f,target[2]-std::cos(side)*radius};for(float turn:{1.25f,-1.25f,2.4f,-2.4f,3.14159f,0.f}){auto candidate=stage::Vec3{target[0]-std::sin(instance.yaw+turn)*radius,target[1]+radius*.4f,target[2]-std::cos(instance.yaw+turn)*radius};auto delta=candidate;float length=0;for(unsigned n=0;n<3;++n){delta[n]-=target[n];length+=delta[n]*delta[n];}length=std::sqrt(length);for(auto&v:delta)v/=length;auto hit=collision->ray(target,delta,length);if(!hit||hit->distance>=length-20){camera.eye=candidate;break;}}camera.direction={target[0]-camera.eye[0],target[1]-camera.eye[1],target[2]-camera.eye[2]};auto pointLights=lights.sample(now);ground.render(c.Get(),0,false,&camera,nullptr,nullptr,pointLights);auto env=light.environment(p.pose.feet);person.render(c.Get(),p.pose.yaw,false,&camera,&ground,&p.pose.feet,pointLights,nullptr,nullptr,&env);
   std::vector<shadows::Caster> objects;machines.shadow_casters(objects);if(shells)shells->shadow_casters(objects);for(const auto&o:objects){auto illumination=light.environment(o.origin);o.renderer->render(c.Get(),o.yaw,false,&camera,&ground,&o.origin,pointLights,nullptr,nullptr,&illumination);}auto sprites=particles.sprites(snapshot,now);if(!sprites.empty())require(effects.render(c.Get(),ground,camera,sprites),"Launcher original effect rendering");capture(d.Get(),c.Get(),ground,output/name,label);if(frames++)report<<',';report<<"{\"file\":\""<<name<<"\",\"instance\":"<<instance.id<<",\"flightId\":"<<p.flightId<<",\"feet\":["<<p.pose.feet[0]<<','<<p.pose.feet[1]<<','<<p.pose.feet[2]<<"],\"hp\":"<<p.hp<<",\"sprites\":"<<sprites.size()<<'}';
  };
  draw(type.kind==mounted::Kind::mortar?"01-mortar-ready.bmp":"04-catapult-ready.bmp",type.kind==mounted::Kind::mortar?L"迫撃砲 / 原モデル・CNP銃口・原姿勢":L"カタパルト / 原モデル・搭乗姿勢",100,-1);
  const auto direction=stage::Vec3{std::sin(pose.yaw)*std::cos(pose.pitch),std::sin(pose.pitch),std::cos(pose.yaw)*std::cos(pose.pitch)};auto result=authority.fire(self,{12,1,snapshot.players[0]->weapon,direction},200);if(!result)throw std::runtime_error("Launcher fire rejected "+type.id+" code "+std::to_string(int(result.reject)));require(!result.events.empty(),"Launcher accepted event");snapshot=authority.snapshot();if(shells){shells->update(c.Get(),result.events,&snapshot,registry,20,collision,200,instance.id);shellVisible|=shells->size()>0;}particles.dispatch(result.events,snapshot,200);lights.dispatch(result.events,snapshot,200);size_t sounds=0;audio.dispatch(result.events,pose.feet,[&](const auto&){++sounds;});require(sounds>0,"Accepted launch resolves original WAV");
  if(type.kind==mounted::Kind::mortar){draw("02-mortar-fire.bmp",L"迫撃砲 / HOST弾道・原マズル画像・発射音",200,.02);mortarEvents=unsigned(result.events.size());}
  uint32_t sequence=1;bool airFrame=false;
  for(uint64_t now=220;now<=12200;now+=20){
   authority.advance(now);auto current=authority.snapshot();if(current.players[0]->mountedId&&now%100==0)authority.pose(self,12,++sequence,current.players[0]->pose,now);
   auto events=authority.advance_projectiles(now).events;current=authority.snapshot();if(shells)shells->update(c.Get(),events,&current,registry,20,collision,now,instance.id);particles.dispatch(events,current,now);lights.dispatch(events,current,now);
   for(const auto&e:events)if(e.kind==combat::EventKind::explosion&&e.weapon==103){exploded=true;std::cout<<"mortar_impact "<<e.position[0]<<' '<<e.position[1]<<' '<<e.position[2]<<" at "<<now<<std::endl;}
   const auto&p=*current.players[0];highest=std::max(highest,p.pose.feet[1]-pose.feet[1]);flight.update(12,&p,now);
   if(type.kind==mounted::Kind::mortar&&now==700)draw("03-mortar-reload.bmp",L"迫撃砲 / 原装填モーション",now,.5);
   if(type.kind==mounted::Kind::catapult){if(p.flightId&&now>=560&&!airFrame){draw("05-catapult-flight.bmp",L"カタパルト / HOST承認の飛行・原飛行姿勢",now,-1);airFrame=true;}if(!p.flightId){landed=true;require(airFrame&&p.alive,"Catapult default flight and live landing");draw("06-catapult-land.bmp",L"カタパルト / 衝突判定・原着地姿勢",now,-1);break;}}
   if(type.kind==mounted::Kind::mortar&&exploded&&now>=700)break;
  }
  require(type.kind==mounted::Kind::mortar?exploded:landed,"Launcher flight completes");
 }
 require(frames>=6&&exploded&&landed&&shellVisible,"Both launchers captured");report<<"],\"mortarEvents\":"<<mortarEvents<<",\"mortarExploded\":true,\"catapultLanded\":true,\"catapultHeight\":"<<highest<<",\"passed\":true}\n";std::cout<<"Original mortar/catapult runtime capture PASS, frames="<<frames<<std::endl;return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
int run_mounted_preview(const std::filesystem::path&data,const std::filesystem::path&output){try{
 std::filesystem::create_directories(output);gameplay::Config config;mounted::Registry registry;std::string error;require(config.load(data/"gameplay.json",error),error.c_str());require(registry.load(data/"mounted_weapons.json",error),error.c_str());auto scene=registry.scene(20);require(!scene.empty(),"QQ mounted placement missing");const auto&instance=scene.front();const auto&type=*registry.find(instance.type);
 auto bytes=read(data/"stage/n022a.gwm");CharacterModel model(bytes);stage::load_original_normals(model,bytes,data/"stage/n022a.gwn");stage::load_floor_blend(model,bytes,data/"stage/n022a.gfb");stage::load_surface_alpha(model,bytes,data/"stage/n022a.gsa");std::ifstream cf(data/"stage/n022a.collision.cfg"),lf(data/"stage/n022a.lighting.cfg");auto collision=std::make_shared<const stage::Collision>(stage::Collision::read(cf));auto light=stage::Lighting::read(lf);for(auto&v:model.vertices){auto l=light.sample({v.x,v.y,v.z},{v.nx,v.ny,v.nz});v.lr=l.color[0];v.lg=l.color[1];v.lb=l.color[2];v.lit=1;}
 combat::Authority authority;auto profiles=config.profiles(20);authority.begin(12,collision,profiles);require(authority.configure_mounted(registry,20),"Mounted fixture configure");const combat::Identity self{0,1,101};combat::Pose pose;pose.feet=mounted::operator_position(instance,type);pose.yaw=instance.yaw;const uint16_t inventory[]{25,3,52};require(authority.join(self,1,pose,1000,1000,inventory,0),"Mounted placement feet/headroom");authority.active(true);require(authority.pose(self,12,1,pose,100)==combat::Reject::none,"Mounted fixture admitted pose");const auto attached=authority.mount(self,12,1,{mounted::Action::mount,instance.id,1},100);if(attached!=combat::Reject::none)throw std::runtime_error("QQ mounted placement denied: "+std::to_string(int(attached)));auto snapshot=authority.snapshot();auto player=*snapshot.players[0];
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level;require(SUCCEEDED(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c)),"Mounted preview WARP");CharacterRenderer ground(d.Get(),model);ground.resize_target(d.Get(),1280,720);mounted::Renderer weapons(d.Get(),data,registry);weapons.update(c.Get(),20,&snapshot);require(weapons.size()==scene.size(),"All mounted placements drawn");
 CharacterCatalog catalog(read(data/"character/appearance.gwc"));std::array<uint8_t,28> appearance{};appearance[2]=11;appearance[3]=22;appearance[15]=46;appearance[17]=57;auto body=catalog.assemble(appearance);require(body.ready(),"Mounted original character");auto held=weapons.pose(20,instance.id,body.gender);require(bool(held),"Mounted original hold");catalog.pose(body,*held);CharacterRenderer person(d.Get(),body.model);
 for(auto key:{0xfbfa42u,0x5c0243u})if(auto p=body.bone_position(key))std::cout<<"mounted_wrist_model "<<key<<' '<<(*p)[0]<<' '<<(*p)[1]<<' '<<(*p)[2]<<'\n';
 combat::particles::Renderer effects(d.Get(),data/config.resources().effectsManifest);combat::particles::Pool particles;for(const auto&definition:config.definitions())particles.textures(definition.visual.effectId?definition.visual.effectId:definition.weapon.id,definition.visual.flashTexture,definition.visual.smokeTexture);combat::LightEffects lights;particles.synchronize(12,1,snapshot.eventWatermark,100);lights.synchronize(12,1,snapshot.eventWatermark,100);
 combat::Effects audio;require(audio.load_manifest(data/config.resources().audioManifest),"Mounted original audio manifest");require(audio.files().contains(config.find(type.weapon)->weapon.shotCue),"Mounted shot cue available");menu_font_resources().load(data/"fonts");
 std::ofstream report(output/"capture.json");report<<"{\"offlineRenderFixture\":true,\"map\":20,\"weapon\":"<<type.weapon<<",\"instance\":"<<instance.id<<",\"frames\":[";
 for(unsigned mode=0;mode<3;++mode){std::vector<combat::Event> events;
  if(mode){pose.yaw=instance.yaw+(mode==1?.55f:0);pose.pitch=mode==1?.1f:0;require(authority.pose(self,12,mode+1,pose,200+mode*100)==combat::Reject::none,"Mounted fixture aim");pose=authority.snapshot().players[0]->pose;auto shot=authority.fire(self,{12,mode,type.weapon,{std::sin(pose.yaw)*std::cos(pose.pitch),std::sin(pose.pitch),std::cos(pose.yaw)*std::cos(pose.pitch)}},200+mode*100);require(bool(shot)&&!shot.events.empty(),"Mounted HOST firing");events=shot.events;snapshot=authority.snapshot();weapons.update(c.Get(),20,&snapshot);gameplay::effects(&config,events);particles.dispatch(events,snapshot,200+mode*100);lights.dispatch(events,snapshot,200+mode*100);}
  auto hold=weapons.pose(20,instance.id,body.gender,mode?.02:-1);catalog.pose(body,*hold);require(mounted::operator_pitch(body,catalog.skeleton(body.gender),type,pose.pitch),"Mounted elevation pose");person.update_vertices(c.Get(),body.model.vertices);WorldView camera;camera.aspect=16.f/9.f;camera.verticalFov=1.f;
  const auto target=mounted::pivot_position(instance,type);const float side=instance.yaw+1.15f;camera.eye={target[0]-std::sin(side)*3800,target[1]+1100,target[2]-std::cos(side)*3800};camera.direction={target[0]-camera.eye[0],target[1]-camera.eye[1]-250,target[2]-camera.eye[2]};
  if(mode==2){auto offset=type.eye;for(unsigned j=0;j<3;++j)offset[j]-=type.pivot[j];offset=mounted::rotate(offset,pose.yaw,pose.pitch);for(unsigned j=0;j<3;++j)camera.eye[j]=target[j]+offset[j];camera.direction={std::sin(pose.yaw),0,std::cos(pose.yaw)};}
  auto pointLights=lights.sample(mode?200+mode*100:100);ground.render(c.Get(),0,false,&camera,nullptr,nullptr,pointLights);auto env=light.environment(pose.feet);
  if(mode<2)person.render(c.Get(),pose.yaw,false,&camera,&ground,&pose.feet,pointLights,nullptr,nullptr,&env);
  else {auto arms=weapon_hand::first_person_arms(body,catalog.skeleton(body.gender));CharacterRenderer armRenderer(d.Get(),arms);armRenderer.render(c.Get(),pose.yaw,false,&camera,&ground,&pose.feet,pointLights,nullptr,nullptr,&env);}
  std::vector<shadows::Caster> guns;weapons.shadow_casters(guns);for(const auto&g:guns){auto illumination=light.environment(g.origin);g.renderer->render(c.Get(),g.yaw,false,&camera,&ground,&g.origin,pointLights,nullptr,nullptr,&illumination);}
  if(mode){const auto sprites=particles.sprites(snapshot,200+mode*100);require(!sprites.empty()&&effects.render(c.Get(),ground,camera,sprites),"Mounted original muzzle sprites");}
  const char*names[]={"01-m2-mounted.bmp","02-m2-firing.bmp","03-m2-first-person.bmp"};const wchar_t*labels[]={L"M2 BROWNING / 原モデル・原搭乗姿勢",L"M2 BROWNING / HOST承認の射撃・原マズル画像",L"M2 BROWNING / 主観視点"};capture(d.Get(),c.Get(),ground,output/names[mode],labels[mode]);if(mode)report<<',';report<<"{\"file\":\""<<names[mode]<<"\",\"shotEvents\":"<<events.size()<<'}';
 }
 require(authority.release_mounted(self)&&authority.snapshot().players[0]->weapon==25&&authority.snapshot().players[0]->ammo==30,"Original inventory restored after M2");report<<"],\"passed\":true}\n";std::cout<<"Mounted original model/rig/hold/fire/audio/FP and host mount/dismount PASS\n";return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
}
