#include "product_identity.h"
#include "weapon_effect_config.h"
#include "multi_ui_json.h"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <fstream>
#include <set>
#include <stdexcept>

namespace mgo2mt::weapon_effect {
namespace {
using V=multi_ui::json::Value;
[[noreturn]]void bad(const std::string& at,const char* why){throw std::runtime_error(at+": "+why);}
void object(const V&v,const std::string&at,std::initializer_list<std::string_view>keys){if(v.type!=V::object)bad(at,"expected object");for(const auto&[key,val]:v.o)if(std::find(keys.begin(),keys.end(),key)==keys.end())bad(at+"."+key,"unknown field");}
const V&get(const V&v,const char*key,const std::string&at){auto i=v.o.find(key);if(i==v.o.end())bad(at+"."+key,"missing field");return i->second;}
float number(const V&v,const std::string&at,float lo,float hi){if(v.type!=V::number||!std::isfinite(v.n)||v.n<lo||v.n>hi)bad(at,"number out of range");return float(v.n);}
uint32_t integer(const V&v,const std::string&at,uint32_t lo,uint32_t hi){if(v.type!=V::number||!std::isfinite(v.n)||v.n<lo||v.n>hi||std::floor(v.n)!=v.n)bad(at,"integer out of range");return uint32_t(v.n);}
bool boolean(const V&v,const std::string&at){if(v.type!=V::boolean)bad(at,"expected boolean");return v.b;}
std::string text(const V&v,const std::string&at){if(v.type!=V::string||v.s.empty()||v.s.size()>240)bad(at,"expected nonempty text");return v.s;}
template<size_t N>std::array<float,N> array(const V&v,const std::string&at,float lo,float hi){if(v.type!=V::array||v.a.size()!=N)bad(at,"wrong vector length");std::array<float,N>out;for(size_t i=0;i<N;++i)out[i]=number(v.a[i],at,lo,hi);return out;}
Curve parse_curve(const V&v,const std::string&at,float max){if(v.type!=V::array||v.a.size()<2||v.a.size()>16)bad(at,"curve requires 2..16 points");Curve out;float last=-1;for(const auto&p:v.a){if(p.type!=V::array||p.a.size()!=2)bad(at,"curve point is [age,value]");float time=number(p.a[0],at,0,1),value=number(p.a[1],at,0,max);if(time<=last)bad(at,"curve times must increase");last=time;out.push_back({time,value});}if(out.front()[0]!=0||out.back()[0]!=1)bad(at,"curve must start at 0 and end at 1");return out;}
std::string resource(const V&v,const std::string&at){auto p=text(v,at);if(!relative_path(p))bad(at,"expected safe data-relative path");return p;}
Emitter emitter(const V&v,const std::string&at,std::map<std::string,uint32_t,std::less<>>&textures){
 object(v,at,{"enabled","texture","count","delayMs","emissionMs","lifetimeMs","additive","atlas","radius","stretch","color","velocity","speed","spread","gravity","rotation","rotationSpeed","sizeRandom","stretchRandom","alphaRandom","rotationRandom","sizeCurve","alphaCurve"});Emitter e;
 for(const auto&[k,x]:v.o){auto a=at+"."+k;
  if(k=="enabled")e.enabled=boolean(x,a);else if(k=="additive")e.additive=boolean(x,a);
  else if(k=="texture"){if(x.type==V::number)e.texture=integer(x,a,1,0x00ffffff);else{e.texturePath=resource(x,a);auto ext=std::filesystem::path(e.texturePath).extension().string();std::transform(ext.begin(),ext.end(),ext.begin(),[](unsigned char c){return char(std::tolower(c));});if(ext!=".png"&&ext!=".dds"&&ext!=".jpg"&&ext!=".jpeg"&&ext!=".bmp"&&ext!=".gif"&&ext!=".tif"&&ext!=".tiff"&&ext!=".ico")bad(a,"unsupported image extension");auto imported=textures.emplace(e.texturePath,0xf0000000u+uint32_t(textures.size())+1);e.texture=imported.first->second;if(textures.size()>64)bad(a,"at most 64 imported textures");}}
  else if(k=="count")e.count=integer(x,a,1,32);else if(k=="delayMs")e.delayMs=integer(x,a,0,10000);else if(k=="emissionMs")e.emissionMs=integer(x,a,0,10000);else if(k=="lifetimeMs")e.lifetimeMs=integer(x,a,1,60000);
  else if(k=="radius")e.radius=number(x,a,.01f,20000);else if(k=="stretch")e.stretch=array<2>(x,a,.01f,16);else if(k=="color")e.color=array<4>(x,a,0,1);else if(k=="velocity")e.velocity=array<3>(x,a,-50000,50000);
  else if(k=="speed")e.speed=number(x,a,0,50000);else if(k=="spread")e.spread=number(x,a,0,3.1415927f);else if(k=="gravity")e.gravity=number(x,a,-50000,50000);else if(k=="rotation")e.rotation=number(x,a,-100,100);else if(k=="rotationSpeed")e.rotationSpeed=number(x,a,-100,100);
  else if(k=="sizeRandom")e.sizeRandom=number(x,a,0,1);else if(k=="stretchRandom")e.stretchRandom=number(x,a,0,1);else if(k=="alphaRandom")e.alphaRandom=number(x,a,0,1);else if(k=="rotationRandom")e.rotationRandom=number(x,a,0,3.1415927f);
  else if(k=="sizeCurve")e.sizeCurve=parse_curve(x,a,16);else if(k=="alphaCurve")e.alphaCurve=parse_curve(x,a,1);
  else if(k=="atlas"){object(x,a,{"columns","rows","frames","fps","loop","randomStart"});for(const auto&[ak,av]:x.o){auto aa=a+"."+ak;if(ak=="columns")e.atlas.columns=integer(av,aa,1,64);else if(ak=="rows")e.atlas.rows=integer(av,aa,1,64);else if(ak=="frames")e.atlas.frames=integer(av,aa,1,4096);else if(ak=="fps")e.atlas.fps=number(av,aa,0,240);else if(ak=="loop")e.atlas.loop=boolean(av,aa);else e.atlas.randomStart=boolean(av,aa);}}
 }
 if(e.enabled&&!e.texture)bad(at,"enabled emitter requires texture");if(e.atlas.frames>e.atlas.columns*e.atlas.rows)bad(at,"atlas frames exceed grid");return e;
}
Light light(const V&v,const std::string&at){object(v,at,{"enabled","delayMs","durationMs","radius","intensity","color","intensityCurve"});Light e;for(const auto&[k,x]:v.o){auto a=at+"."+k;if(k=="enabled")e.enabled=boolean(x,a);else if(k=="delayMs")e.delayMs=integer(x,a,0,10000);else if(k=="durationMs")e.durationMs=integer(x,a,1,60000);else if(k=="radius")e.radius=number(x,a,1,100000);else if(k=="intensity")e.intensity=number(x,a,0,16);else if(k=="color")e.color=array<3>(x,a,0,1);else e.intensityCurve=parse_curve(x,a,1);}return e;}
Sound sound(const V&v,const std::string&at){object(v,at,{"enabled","cue","path","delayMs","gain"});Sound e;for(const auto&[k,x]:v.o){auto a=at+"."+k;if(k=="enabled")e.enabled=boolean(x,a);else if(k=="cue")e.cue=integer(x,a,0,1000000);else if(k=="path"){e.path=resource(x,a);auto ext=std::filesystem::path(e.path).extension().string();std::transform(ext.begin(),ext.end(),ext.begin(),[](unsigned char c){return char(std::tolower(c));});if(ext!=".wav")bad(a,"imported sound must be WAV");}else if(k=="delayMs")e.delayMs=integer(x,a,0,60000);else e.gain=number(x,a,0,4);}if(e.enabled&&((e.cue!=0)==!e.path.empty()))bad(at,"enabled sound requires exactly one cue or WAV path");return e;}
Definition definition(const V&v,const std::string&at,bool weapon,std::map<std::string,uint32_t,std::less<>>&textures){if(weapon)object(v,at,{"id","particles","lights","sounds","reticle"});else object(v,at,{"particles","lights","sounds","reticle"});Definition d;
 if(auto i=v.o.find("particles");i!=v.o.end()){object(i->second,at+".particles",{"muzzle","smoke","casing","explosion","smokeCloud","humanBlood","gekkoBlood"});for(const auto&[key,rows]:i->second.o){auto a=at+".particles."+key;if(rows.type!=V::array||rows.a.size()>8)bad(a,"expected 0..8 emitter layers");auto&out=d.particles[key];unsigned count=0;for(size_t n=0;n<rows.a.size();++n){out.push_back(emitter(rows.a[n],a+"["+std::to_string(n)+"]",textures));if(out.back().enabled)count+=out.back().count;}if(count>128)bad(a,"at most 128 particles per event channel");}}
 if(auto i=v.o.find("lights");i!=v.o.end()){object(i->second,at+".lights",{"shot","explosion"});for(const auto&[key,x]:i->second.o)d.lights[key]=light(x,at+".lights."+key);}
 if(auto i=v.o.find("sounds");i!=v.o.end()){object(i->second,at+".sounds",{"shot","reload","click","casing","explosion"});for(const auto&[key,x]:i->second.o)d.sounds[key]=sound(x,at+".sounds."+key);}
 if(auto i=v.o.find("reticle");i!=v.o.end()){const auto a=at+".reticle";object(i->second,a,{"enabled","color","thickness","length","centerDot","minGap"});Reticle r;for(const auto&[key,x]:i->second.o){auto p=a+"."+key;if(key=="enabled")r.enabled=boolean(x,p);else if(key=="centerDot")r.centerDot=boolean(x,p);else if(key=="color")r.color=array<4>(x,p,0,1);else if(key=="thickness")r.thickness=number(x,p,.5f,16);else if(key=="length")r.length=number(x,p,1,100);else r.minGap=number(x,p,0,100);}d.reticle=r;}
 return d;
}
uint64_t mix(uint64_t x){x+=0x9e3779b97f4a7c15ull;x=(x^(x>>30))*0xbf58476d1ce4e5b9ull;x=(x^(x>>27))*0x94d049bb133111ebull;return x^(x>>31);}
float random(uint64_t&seed){seed=mix(seed);return float(seed>>40)*(1.f/16777216.f);}
Vec3 unit(Vec3 a){float n=std::hypot(a[0],a[1],a[2]);if(!std::isfinite(n)||n<1e-6f)return {0,1,0};for(auto&x:a)x/=n;return a;}
Vec3 cross(Vec3 a,Vec3 b){return {a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]};}
}
bool relative_path(std::string_view s)noexcept{if(s.empty()||s.size()>240||s.front()=='/'||s.back()=='/'||s.find_first_of("\\:<>\"|?*")!=s.npos)return false;for(unsigned char c:s)if(c<32||c==127)return false;size_t start=0;for(;;){auto end=s.find('/',start);auto part=s.substr(start,end==s.npos?s.size()-start:end-start);if(part.empty()||part=="."||part==".."||part.back()=='.'||part.back()==' ')return false;auto stem=part.substr(0,part.find('.'));std::string upper(stem);for(auto&c:upper)c=char(std::toupper(static_cast<unsigned char>(c)));if(upper=="CON"||upper=="PRN"||upper=="AUX"||upper=="NUL"||upper=="CONIN$"||upper=="CONOUT$"||(upper.size()==4&&(upper.starts_with("COM")||upper.starts_with("LPT"))&&upper[3]>='1'&&upper[3]<='9')||(upper.size()==5&&(upper.starts_with("COM")||upper.starts_with("LPT"))&&(upper.substr(3)=="\xc2\xb9"||upper.substr(3)=="\xc2\xb2"||upper.substr(3)=="\xc2\xb3")))return false;if(end==s.npos)break;start=end+1;}return true;}
bool Config::load(const std::filesystem::path&p,std::string&error){try{std::ifstream in(p,std::ios::binary|std::ios::ate);auto size=in.tellg();if(size<=0||size>1024*1024)throw std::runtime_error("effect JSON missing or exceeds 1 MiB");std::string source(size_t(size),'\0');in.seekg(0);if(!in.read(source.data(),size))throw std::runtime_error("effect JSON read failed");return load_text(source,error);}catch(const std::exception&e){error=e.what();return false;}}
bool Config::load_text(std::string_view source,std::string&error){try{if(source.size()>1024*1024)throw std::runtime_error("effect JSON exceeds 1 MiB");Config next;auto root=multi_ui::json::parse(source);object(root,"$",{"format","version","defaults","weapons"});if(text(get(root,"format","$"),"$.format")!=mgo2mt::brand::Format{"MGO2MT.WeaponEffects"})bad("$.format","unsupported format");integer(get(root,"version","$"),"$.version",1,1);if(auto i=root.o.find("defaults");i!=root.o.end())next.defaults_=definition(i->second,"$.defaults",false,next.textures_);if(auto i=root.o.find("weapons");i!=root.o.end()){if(i->second.type!=V::array||i->second.a.size()>128)bad("$.weapons","expected 0..128 weapons");for(size_t n=0;n<i->second.a.size();++n){auto at="$.weapons["+std::to_string(n)+"]";auto&r=i->second.a[n];if(r.type!=V::object)bad(at,"expected object");auto id=uint16_t(integer(get(r,"id",at),at+".id",1,511));if(next.weapons_.contains(id))bad(at,"duplicate weapon ID");next.weapons_[id]=definition(r,at,true,next.textures_);}}*this=std::move(next);error.clear();return true;}catch(const std::exception&e){error=std::string("Weapon effects: ")+e.what();return false;}}
const std::vector<Emitter>*Config::particles(uint16_t id,std::string_view channel)const{if(auto w=weapons_.find(id);w!=weapons_.end())if(auto i=w->second.particles.find(channel);i!=w->second.particles.end())return &i->second;if(auto i=defaults_.particles.find(channel);i!=defaults_.particles.end())return &i->second;return nullptr;}
const Light*Config::light(uint16_t id,std::string_view event)const{if(auto w=weapons_.find(id);w!=weapons_.end())if(auto i=w->second.lights.find(event);i!=w->second.lights.end())return &i->second;if(auto i=defaults_.lights.find(event);i!=defaults_.lights.end())return &i->second;return nullptr;}
const Sound*Config::sound(uint16_t id,std::string_view event)const{if(auto w=weapons_.find(id);w!=weapons_.end())if(auto i=w->second.sounds.find(event);i!=w->second.sounds.end())return &i->second;if(auto i=defaults_.sounds.find(event);i!=defaults_.sounds.end())return &i->second;return nullptr;}
const Reticle*Config::reticle(uint16_t id)const{if(auto w=weapons_.find(id);w!=weapons_.end()&&w->second.reticle)return &*w->second.reticle;return defaults_.reticle?&*defaults_.reticle:nullptr;}
float curve(const Curve&c,float age)noexcept{if(c.empty())return 1;if(!std::isfinite(age)||age<=c.front()[0])return c.front()[1];for(size_t i=1;i<c.size();++i)if(age<=c[i][0]){float t=(age-c[i-1][0])/(c[i][0]-c[i-1][0]);return c[i-1][1]+t*(c[i][1]-c[i-1][1]);}return c.back()[1];}
uint64_t duration(const std::vector<Emitter>&emitters)noexcept{uint64_t n=0;for(const auto&e:emitters)if(e.enabled)n=(std::max)(n,uint64_t(e.delayMs)+e.emissionMs+e.lifetimeMs);return n;}
std::vector<ParticleSample> sample(const std::vector<Emitter>&emitters,Vec3 origin,Vec3 direction,uint64_t seed,uint64_t ageMs){
 std::vector<ParticleSample>out;if(emitters.size()>8||!std::all_of(origin.begin(),origin.end(),[](float x){return std::isfinite(x)&&std::abs(x)<1000000;}))return out;direction=unit(direction);auto right=unit(cross(std::abs(direction[1])>.999f?Vec3{1,0,0}:Vec3{0,1,0},direction));auto up=cross(direction,right);
 for(size_t layer=0;layer<emitters.size();++layer){const auto&e=emitters[layer];if(!e.enabled||!e.texture||!e.lifetimeMs||!e.atlas.columns||!e.atlas.rows||!e.atlas.frames)continue;for(uint32_t n=0;n<(std::min)(32u,e.count)&&out.size()<128;++n){uint64_t born=e.delayMs+(e.count>1?uint64_t(e.emissionMs)*n/(e.count-1):0);if(ageMs<born||ageMs-born>=e.lifetimeMs)continue;float t=float(ageMs-born)*.001f,age=float(ageMs-born)/float(e.lifetimeMs);uint64_t rng=mix(seed^mix(layer+1)^mix(uint64_t(n)+0x10000));auto signedRandom=[&](){return 2*random(rng)-1;};float size=1+e.sizeRandom*signedRandom(),stretchX=1+e.stretchRandom*signedRandom(),stretchY=1+e.stretchRandom*signedRandom(),alpha=1-e.alphaRandom*random(rng),rotation=e.rotation+e.rotationRandom*signedRandom()+e.rotationSpeed*t;float cosine=1-random(rng)*(1-std::cos(e.spread)),sine=std::sqrt((std::max)(0.f,1-cosine*cosine)),angle=random(rng)*6.2831853f;Vec3 velocity;for(unsigned axis=0;axis<3;++axis)velocity[axis]=e.velocity[axis]+e.speed*(direction[axis]*cosine+(right[axis]*std::cos(angle)+up[axis]*std::sin(angle))*sine);
   ParticleSample p;p.position=origin;for(unsigned axis=0;axis<3;++axis)p.position[axis]+=velocity[axis]*t;p.position[1]-=.5f*e.gravity*t*t;p.radius=(std::min)(20000.f,e.radius*size*curve(e.sizeCurve,age));p.stretch={(std::max)(.001f,e.stretch[0]*stretchX),(std::max)(.001f,e.stretch[1]*stretchY)};p.rotation=rotation;p.rgba=e.color;p.rgba[3]=std::clamp(p.rgba[3]*alpha*curve(e.alphaCurve,age),0.f,1.f);p.texture=e.texture;p.additive=e.additive;uint64_t frame=uint64_t(t*e.atlas.fps)+(e.atlas.randomStart?uint64_t(random(rng)*e.atlas.frames):0);frame=e.atlas.loop?frame%e.atlas.frames:(std::min)(uint64_t(e.atlas.frames-1),frame);p.uv={float(frame%e.atlas.columns)/e.atlas.columns,float(frame/e.atlas.columns)/e.atlas.rows,float(frame%e.atlas.columns+1)/e.atlas.columns,float(frame/e.atlas.columns+1)/e.atlas.rows};if(p.radius>0&&p.rgba[3]>0&&std::all_of(p.position.begin(),p.position.end(),[](float x){return std::isfinite(x)&&std::abs(x)<1000000;}))out.push_back(p);
  }}return out;
}
}
